// Code generated by abstraction-idl from abstraction-inference/job.thrift. DO NOT EDIT.

use std::collections::BTreeMap;

// An opaque payload is bytes the contract forbids us to reinterpret, and String
// would refuse to hold one that is not UTF-8 rather than carry it back out.
pub type Raw = Vec<u8>;

const HEX: &[u8; 16] = b"0123456789abcdef";

fn esc_byte(out: &mut Vec<u8>, c: u8) {
    match c {
        b'"' => out.extend_from_slice(b"\\\""),
        b'\\' => out.extend_from_slice(b"\\\\"),
        0x08 => out.extend_from_slice(b"\\b"),
        0x0c => out.extend_from_slice(b"\\f"),
        b'\n' => out.extend_from_slice(b"\\n"),
        b'\r' => out.extend_from_slice(b"\\r"),
        b'\t' => out.extend_from_slice(b"\\t"),
        _ if c < 0x20 => {
            out.extend_from_slice(b"\\u00");
            out.push(HEX[(c >> 4) as usize]);
            out.push(HEX[(c & 0x0F) as usize]);
        }
        _ => out.push(c),
    }
}

fn num(out: &mut Vec<u8>, n: i64) {
    out.extend_from_slice(n.to_string().as_bytes());
}

fn pad(out: &mut Vec<u8>, depth: i32) {
    for _ in 0..depth * 2 {
        out.push(b' ');
    }
}

fn strs(out: &mut Vec<u8>, v: &[String], depth: i32) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, s) in v.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, s);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

fn ws(c: u8) -> bool {
    c == b' ' || c == b'\t' || c == b'\n' || c == b'\r'
}

fn esc(out: &mut Vec<u8>, s: &str) {
    out.push(b'"');
    for c in s.as_bytes() {
        esc_byte(out, *c);
    }
    out.push(b'"');
}

fn strmap(out: &mut Vec<u8>, m: &BTreeMap<String, String>, depth: i32) {
    if m.is_empty() {
        out.extend_from_slice(b"{}");
        return;
    }
    out.extend_from_slice(b"{\n");
    for (i, (k, v)) in m.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, k);
        out.extend_from_slice(b": ");
        esc(out, v);
        if i + 1 < m.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b'}');
}

fn enc_list<T>(out: &mut Vec<u8>, v: &[T], depth: i32, enc: fn(&mut Vec<u8>, &T, i32)) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, x) in v.iter().enumerate() {
        pad(out, depth + 1);
        enc(out, x, depth + 1);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

/// The closed vocabulary Profile. A reader refuses a name it does not list.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Profile {
    Video,
    ImageBatch,
}

impl Profile {
    /// Every member, in declaration order.
    pub const ALL: [Self; 2] = [Self::Video, Self::ImageBatch];

    /// The member's name on the wire.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Video => "video",
            Self::ImageBatch => "image_batch",
        }
    }

    /// The member a wire name spells, or `None` for a name this vocabulary refuses.
    pub fn from_wire(name: &str) -> Option<Self> {
        match name {
            "video" => Some(Self::Video),
            "image_batch" => Some(Self::ImageBatch),
            _ => None,
        }
    }
}

impl std::fmt::Display for Profile {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl PartialEq<str> for Profile {
    fn eq(&self, other: &str) -> bool {
        self.as_str() == other
    }
}

impl PartialEq<&str> for Profile {
    fn eq(&self, other: &&str) -> bool {
        self.as_str() == *other
    }
}

/// The closed vocabulary Mode. A reader refuses a name it does not list.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Mode {
    Generate,
    Edit,
}

impl Mode {
    /// Every member, in declaration order.
    pub const ALL: [Self; 2] = [Self::Generate, Self::Edit];

    /// The member's name on the wire.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Generate => "generate",
            Self::Edit => "edit",
        }
    }

    /// The member a wire name spells, or `None` for a name this vocabulary refuses.
    pub fn from_wire(name: &str) -> Option<Self> {
        match name {
            "generate" => Some(Self::Generate),
            "edit" => Some(Self::Edit),
            _ => None,
        }
    }
}

impl std::fmt::Display for Mode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl PartialEq<str> for Mode {
    fn eq(&self, other: &str) -> bool {
        self.as_str() == other
    }
}

impl PartialEq<&str> for Mode {
    fn eq(&self, other: &&str) -> bool {
        self.as_str() == *other
    }
}

/// Names of the open vocabulary RequestGuarantee. A reader keeps a name it has never heard
/// of, so fields carry `String` and a match needs an arm for the rest.
pub mod request_guarantee {
    pub const LOCAL_ONLY: &str = "abstraction.inference/local-only@1";
    pub const HOSTED_ALLOWED: &str = "abstraction.inference/hosted-allowed@1";
    /// Every name this definition declares, in declaration order.
    pub const ALL: [&str; 2] = [LOCAL_ONLY, HOSTED_ALLOWED];
}

pub const KINDS: [&str; 1] = ["inference"];

pub const EXECUTION_GUARANTEES: [&str; 1] = ["abstraction.inference/recoverable-upstream@1"];

/// The durable image-shaped request. Its fields and bounds match
/// abstraction.inference/image@1 ImageRequest. Keeping this job document
/// self-contained lets the job SDK persist and reconcile it without importing a
/// service transport codec.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ImageRequest {
    pub model: String,
    pub mode: Mode,
    pub prompt: String,
    pub size: String,
    pub count: i64,
    pub image_digest: String,
    pub image_media_type: String,
    pub mask_digest: String,
    pub mask_media_type: String,
    pub guarantees: Vec<String>,
    pub credential: String,
    pub required_extensions: Vec<String>,
    pub extensions: BTreeMap<String, String>,
}

/// A typed result reference with the same meaning as
/// abstraction.inference/image@1 Delivery.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Delivery {
    pub digest: String,
    pub media_type: String,
    pub size: i64,
    pub location: String,
}

/// Durable inference work submitted as job kind inference. video carries an
/// image-shaped generate request and duration_ms of 1..600000; image_batch
/// carries duration zero and count 1..10. The embedded request retains its
/// digest, guarantee, credential and extension bounds. The recoverable-upstream
/// guarantee means the executor durably marks submission before the paid call,
/// records a returned provider handle, resumes a known handle, and invokes the
/// adapter's reconciliation path after an uncertain submit. It does not promise
/// eventual resolution: an adapter such as Replicate that offers no lookup by
/// caller operation keeps the job waiting as upstream:uncertain and never
/// blindly submits it again. No URL, path, header, credential bytes or inline
/// media crosses this value.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Request {
    pub profile: Profile,
    pub image: ImageRequest,
    pub duration_ms: i64,
}

/// The immutable successful result returned by the job operation. deliveries
/// are ordered typed references committed for the original caller. Local
/// references are canonical SHA-256 digests readable through that caller's
/// authorized content reader; remote locations state their owning trust domain.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct JobResult {
    pub profile: Profile,
    pub deliveries: Vec<Delivery>,
    pub host: String,
    pub model: String,
}

/// Exactly one of request or result is present. Request documents are opaque
/// job submission spec bytes. Result documents are immutable operation result
/// bytes read through abstraction.job/operation@1. The job layer does not parse
/// either variant.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Document {
    pub request: Option<Request>,
    pub result: Option<JobResult>,
}

fn enc_image_request(out: &mut Vec<u8>, v: &ImageRequest, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "model");
    out.extend_from_slice(b": ");
    esc(out, &v.model);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "mode");
    out.extend_from_slice(b": ");
    esc(out, v.mode.as_str());
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "prompt");
    out.extend_from_slice(b": ");
    esc(out, &v.prompt);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "size");
    out.extend_from_slice(b": ");
    esc(out, &v.size);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "count");
    out.extend_from_slice(b": ");
    num(out, v.count);
    if !v.image_digest.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "image_digest");
        out.extend_from_slice(b": ");
        esc(out, &v.image_digest);
    }
    if !v.image_media_type.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "image_media_type");
        out.extend_from_slice(b": ");
        esc(out, &v.image_media_type);
    }
    if !v.mask_digest.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "mask_digest");
        out.extend_from_slice(b": ");
        esc(out, &v.mask_digest);
    }
    if !v.mask_media_type.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "mask_media_type");
        out.extend_from_slice(b": ");
        esc(out, &v.mask_media_type);
    }
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "guarantees");
    out.extend_from_slice(b": ");
    strs(out, &v.guarantees, depth + 1);
    if !v.credential.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "credential");
        out.extend_from_slice(b": ");
        esc(out, &v.credential);
    }
    if !v.required_extensions.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "required_extensions");
        out.extend_from_slice(b": ");
        strs(out, &v.required_extensions, depth + 1);
    }
    if !v.extensions.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "extensions");
        out.extend_from_slice(b": ");
        strmap(out, &v.extensions, depth + 1);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_delivery(out: &mut Vec<u8>, v: &Delivery, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "digest");
    out.extend_from_slice(b": ");
    esc(out, &v.digest);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "media_type");
    out.extend_from_slice(b": ");
    esc(out, &v.media_type);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "size");
    out.extend_from_slice(b": ");
    num(out, v.size);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "location");
    out.extend_from_slice(b": ");
    esc(out, &v.location);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_request(out: &mut Vec<u8>, v: &Request, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "profile");
    out.extend_from_slice(b": ");
    esc(out, v.profile.as_str());
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "image");
    out.extend_from_slice(b": ");
    enc_image_request(out, &v.image, depth + 1);
    if v.duration_ms != 0 {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "duration_ms");
        out.extend_from_slice(b": ");
        num(out, v.duration_ms);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_job_result(out: &mut Vec<u8>, v: &JobResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "profile");
    out.extend_from_slice(b": ");
    esc(out, v.profile.as_str());
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "deliveries");
    out.extend_from_slice(b": ");
    enc_list(out, &v.deliveries, depth + 1, enc_delivery);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "host");
    out.extend_from_slice(b": ");
    esc(out, &v.host);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "model");
    out.extend_from_slice(b": ");
    esc(out, &v.model);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_document(out: &mut Vec<u8>, v: &Document, depth: i32) {
    out.push(b'{');
    let mut first = true;
    if let Some(value) = &v.request {
        first = false;
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "request");
        out.extend_from_slice(b": ");
        enc_request(out, value, depth + 1);
    }
    if let Some(value) = &v.result {
        if !first {
            out.push(b',');
        }
        first = false;
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "result");
        out.extend_from_slice(b": ");
        enc_job_result(out, value, depth + 1);
    }
    if !first {
        out.push(b'\n');
        pad(out, depth);
    }
    out.push(b'}');
}

pub fn encode(v: &Document) -> Vec<u8> {
    let mut out = Vec::new();
    enc_document(&mut out, v, 0);
    out.push(b'\n');
    out
}

const DEPTH_LIMIT: i32 = 64;

#[derive(Debug)]
pub struct Refusal {
    pub word: &'static str,
    pub offset: usize,
}

impl std::fmt::Display for Refusal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "refused: {} at byte {}", self.word, self.offset)
    }
}

impl std::error::Error for Refusal {}

fn append_rune(out: &mut Vec<u8>, cp: u32) {
    if cp < 0x80 {
        out.push(cp as u8);
    } else if cp < 0x800 {
        out.push(0xC0 | (cp >> 6) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else if cp < 0x10000 {
        out.push(0xE0 | (cp >> 12) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else {
        out.push(0xF0 | (cp >> 18) as u8);
        out.push(0x80 | ((cp >> 12) & 0x3F) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    }
}

struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
    depth: i32,
}

impl<'a> Reader<'a> {
    fn refuse<T>(&self, word: &'static str) -> Result<T, Refusal> {
        Err(Refusal { word, offset: self.pos })
    }

    fn at(&self) -> u8 {
        if self.pos < self.buf.len() { self.buf[self.pos] } else { 0 }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.buf.len() && ws(self.buf[self.pos]) {
            self.pos += 1;
        }
    }

    fn enter(&mut self) -> Result<(), Refusal> {
        self.depth += 1;
        if self.depth > DEPTH_LIMIT {
            return self.refuse("depth_exceeded");
        }
        Ok(())
    }

    fn string(&mut self) -> Result<String, Refusal> {
        if self.at() != b'"' {
            return self.refuse("wrong_type");
        }
        self.pos += 1;
        let mut out: Vec<u8> = Vec::new();
        loop {
            if self.pos >= self.buf.len() {
                return self.refuse("malformed");
            }
            let c = self.buf[self.pos];
            if c == b'"' {
                self.pos += 1;
                return match String::from_utf8(out) {
                    Ok(s) => Ok(s),
                    Err(_) => self.refuse("bad_string"),
                };
            }
            if c < 0x20 {
                return self.refuse("bad_string");
            }
            if c == b'\\' {
                self.escape(&mut out)?;
            } else {
                out.push(c);
                self.pos += 1;
            }
        }
    }

    fn escape(&mut self, out: &mut Vec<u8>) -> Result<(), Refusal> {
        self.pos += 1;
        if self.pos >= self.buf.len() {
            return self.refuse("malformed");
        }
        let c = self.buf[self.pos];
        self.pos += 1;
        match c {
            b'"' | b'\\' | b'/' => out.push(c),
            b'b' => out.push(0x08),
            b'f' => out.push(0x0c),
            b'n' => out.push(b'\n'),
            b'r' => out.push(b'\r'),
            b't' => out.push(b'\t'),
            b'u' => {
                let mut u = self.hex4()?;
                if (0xDC00..=0xDFFF).contains(&u) {
                    return self.refuse("bad_string");
                }
                if (0xD800..=0xDBFF).contains(&u) {
                    if self.pos + 1 >= self.buf.len()
                        || self.buf[self.pos] != b'\\'
                        || self.buf[self.pos + 1] != b'u'
                    {
                        return self.refuse("bad_string");
                    }
                    self.pos += 2;
                    let low = self.hex4()?;
                    if !(0xDC00..=0xDFFF).contains(&low) {
                        return self.refuse("bad_string");
                    }
                    u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
                }
                append_rune(out, u);
            }
            _ => return self.refuse("bad_string"),
        }
        Ok(())
    }

    fn hex4(&mut self) -> Result<u32, Refusal> {
        if self.pos + 4 > self.buf.len() {
            return self.refuse("bad_string");
        }
        let mut u: u32 = 0;
        for i in 0..4 {
            let c = self.buf[self.pos + i];
            let d = match c {
                b'0'..=b'9' => c - b'0',
                b'a'..=b'f' => c - b'a' + 10,
                b'A'..=b'F' => c - b'A' + 10,
                _ => return self.refuse("bad_string"),
            };
            u = u << 4 | d as u32;
        }
        self.pos += 4;
        Ok(u)
    }

    fn integer(&mut self, low: i64, high: i64) -> Result<i64, Refusal> {
        let c = self.at();
        if c != b'-' && !c.is_ascii_digit() {
            return self.refuse("wrong_type");
        }
        let negative = c == b'-';
        if negative {
            self.pos += 1;
        }
        if !self.at().is_ascii_digit() {
            return self.refuse("malformed");
        }
        let mut u: u64 = 0;
        if self.at() == b'0' {
            self.pos += 1;
        } else {
            while self.at().is_ascii_digit() {
                if u > 922337203685477580 {
                    return self.refuse("number_spelling");
                }
                u = u * 10 + (self.at() - b'0') as u64;
                self.pos += 1;
            }
        }
        let after = self.at();
        if after == b'.' || after == b'e' || after == b'E' || after.is_ascii_digit() {
            return self.refuse("number_spelling");
        }
        if negative && u == 0 {
            return self.refuse("number_spelling");
        }
        let n = if negative {
            if u > 1u64 << 63 {
                return self.refuse("number_spelling");
            }
            if u == 1u64 << 63 { i64::MIN } else { -(u as i64) }
        } else {
            if u > i64::MAX as u64 {
                return self.refuse("number_spelling");
            }
            u as i64
        };
        if n < low || n > high {
            return self.refuse("number_spelling");
        }
        Ok(n)
    }

    fn str_list(&mut self) -> Result<Vec<String>, Refusal> {
        if self.at() != b'[' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = Vec::new();
        self.skip_ws();
        if self.at() != b']' {
            loop {
                self.skip_ws();
                out.push(self.string()?);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b']' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

}

fn str_map(r: &mut Reader) -> Result<BTreeMap<String, String>, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut out = BTreeMap::new();
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let k = r.string()?;
            if out.contains_key(&k) {
                return r.refuse("duplicate_key");
            }
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            let v = r.string()?;
            out.insert(k, v);
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(out)
}

fn decode_list<T>(
    r: &mut Reader,
    elem: fn(&mut Reader) -> Result<T, Refusal>,
) -> Result<Vec<T>, Refusal> {
    if r.at() != b'[' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut out = Vec::new();
    r.skip_ws();
    if r.at() != b']' {
        loop {
            r.skip_ws();
            out.push(elem(r)?);
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b']' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(out)
}

fn decode_image_request(r: &mut Reader) -> Result<ImageRequest, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_model: String = Default::default();
    let mut field_mode: Option<String> = None;
    let mut field_prompt: String = Default::default();
    let mut field_size: String = Default::default();
    let mut field_count: i64 = Default::default();
    let mut field_image_digest: String = Default::default();
    let mut field_image_media_type: String = Default::default();
    let mut field_mask_digest: String = Default::default();
    let mut field_mask_media_type: String = Default::default();
    let mut field_guarantees: Vec<String> = Default::default();
    let mut field_credential: String = Default::default();
    let mut field_required_extensions: Vec<String> = Default::default();
    let mut field_extensions: BTreeMap<String, String> = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "model" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_model = r.string()?;
                }
                "mode" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_mode = Some(r.string()?);
                }
                "prompt" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_prompt = r.string()?;
                }
                "size" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    field_size = r.string()?;
                }
                "count" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    field_count = r.integer(i64::MIN, i64::MAX)?;
                }
                "image_digest" => {
                    if seen & 32 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 32;
                    field_image_digest = r.string()?;
                }
                "image_media_type" => {
                    if seen & 64 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 64;
                    field_image_media_type = r.string()?;
                }
                "mask_digest" => {
                    if seen & 128 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 128;
                    field_mask_digest = r.string()?;
                }
                "mask_media_type" => {
                    if seen & 256 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 256;
                    field_mask_media_type = r.string()?;
                }
                "guarantees" => {
                    if seen & 512 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 512;
                    field_guarantees = r.str_list()?;
                }
                "credential" => {
                    if seen & 1024 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1024;
                    field_credential = r.string()?;
                }
                "required_extensions" => {
                    if seen & 2048 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2048;
                    field_required_extensions = r.str_list()?;
                }
                "extensions" => {
                    if seen & 4096 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4096;
                    field_extensions = str_map(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 543 != 543 {
        return r.refuse("missing_field");
    }
    let Some(field_mode) = field_mode.as_deref().and_then(Mode::from_wire) else {
        return r.refuse("bad_enum");
    };
    Ok(ImageRequest {
        model: field_model,
        mode: field_mode,
        prompt: field_prompt,
        size: field_size,
        count: field_count,
        image_digest: field_image_digest,
        image_media_type: field_image_media_type,
        mask_digest: field_mask_digest,
        mask_media_type: field_mask_media_type,
        guarantees: field_guarantees,
        credential: field_credential,
        required_extensions: field_required_extensions,
        extensions: field_extensions,
    })
}

fn decode_delivery(r: &mut Reader) -> Result<Delivery, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_digest: String = Default::default();
    let mut field_media_type: String = Default::default();
    let mut field_size: i64 = Default::default();
    let mut field_location: String = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "digest" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_digest = r.string()?;
                }
                "media_type" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_media_type = r.string()?;
                }
                "size" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_size = r.integer(i64::MIN, i64::MAX)?;
                }
                "location" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    field_location = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(Delivery {
        digest: field_digest,
        media_type: field_media_type,
        size: field_size,
        location: field_location,
    })
}

fn decode_request(r: &mut Reader) -> Result<Request, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_profile: Option<String> = None;
    let mut field_image: Option<ImageRequest> = None;
    let mut field_duration_ms: i64 = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "profile" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_profile = Some(r.string()?);
                }
                "image" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_image = Some(decode_image_request(r)?);
                }
                "duration_ms" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_duration_ms = r.integer(i64::MIN, i64::MAX)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    let Some(field_image) = field_image else {
        return r.refuse("missing_field");
    };
    let Some(field_profile) = field_profile.as_deref().and_then(Profile::from_wire) else {
        return r.refuse("bad_enum");
    };
    Ok(Request {
        profile: field_profile,
        image: field_image,
        duration_ms: field_duration_ms,
    })
}

fn decode_job_result(r: &mut Reader) -> Result<JobResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_profile: Option<String> = None;
    let mut field_deliveries: Vec<Delivery> = Default::default();
    let mut field_host: String = Default::default();
    let mut field_model: String = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "profile" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_profile = Some(r.string()?);
                }
                "deliveries" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_deliveries = decode_list(r, decode_delivery)?;
                }
                "host" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_host = r.string()?;
                }
                "model" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    field_model = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    let Some(field_profile) = field_profile.as_deref().and_then(Profile::from_wire) else {
        return r.refuse("bad_enum");
    };
    Ok(JobResult {
        profile: field_profile,
        deliveries: field_deliveries,
        host: field_host,
        model: field_model,
    })
}

fn decode_document(r: &mut Reader) -> Result<Document, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_request: Option<Request> = None;
    let mut field_result: Option<JobResult> = None;
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "request" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_request = Some(decode_request(r)?);
                }
                "result" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_result = Some(decode_job_result(r)?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(Document {
        request: field_request,
        result: field_result,
    })
}

pub fn decode(data: &[u8]) -> Result<Document, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let v = decode_document(&mut r)?;
    r.skip_ws();
    if r.pos < r.buf.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

