// Code generated by abstraction-idl from abstraction-inference/inference.thrift. DO NOT EDIT.

// abstraction.inference.api: declarations for index.mjs.

/** The frame transport a generated client calls: a facade binding or a connector's transport. */
interface FrameTransport {
  exchangeFrame(frame: Uint8Array): Promise<Uint8Array>;
  writeFrame(frame: Uint8Array): Promise<void>;
}

// accepted carries an operation id of 1..128 bytes, the chosen host and model,
// and the provider's bounds: an ended operation stays observable for
// retention_ms; an operation with no Observe in flight or received for idle_ms
// is cancelled with reason idle, and its upstream request closed; the newest
// retained_deltas deltas stay readable. Every refusal carries the same reason
// words as Reply, an empty operation, host and model, and zero bounds.
// exhausted means the caller's concurrent operations are at the provider's
// bound.
export interface Admission {
  outcome: StartOutcome;
  reason: string;
  operation: string;
  host: string;
  model: string;
  retentionMs: bigint;
  idleMs: bigint;
  retainedDeltas: bigint;
}

// One ordered speech output chunk. index starts at zero and data is 1..65536
// bytes. Concatenating chunks byte-for-byte yields the content named by
// SpeechReply.delivery.digest.
export interface AudioChunk {
  index: bigint;
  data: Uint8Array;
}

// profile is the host profile of the call; empty is chat. audio_seconds is the
// rounded-up input duration counted for transcription, characters is text sent
// for speech, and images is the generated image count. domain names the other
// trust domain of a decision: on the delegating runtime the remote host it went
// to, and on the remote runtime the caller its client certificate maps to.
// claim, on the remote runtime, is the program the delegating runtime says
// asked, attributed to domain; it decides nothing. route remote is a call that
// arrived over the remote transport, whose rung names that transport. One
// decision in journal order, at unix_ms milliseconds since the Unix epoch: an
// ended operation, an admission refusal, or a window refusal before admission.
// Entries carry names and counts, never headers, credentials or content.
export interface AuditEntry {
  sequence: bigint;
  unixMs: bigint;
  route: AuditRoute;
  rung: string;
  program: string;
  operation: string;
  host: string;
  model: string;
  credential: string;
  outcome: string;
  reason: string;
  tokensIn: bigint;
  tokensOut: bigint;
  wallMs: bigint;
  ceiling: string;
  domain: string;
  claim: string;
  profile: string;
  audioSeconds: bigint;
  characters: bigint;
  images: bigint;
}

export type AuditOutcome = (typeof AuditOutcome)[keyof typeof AuditOutcome];
export declare const AuditOutcome: Readonly<{ Page: "page"; Gap: "gap"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// page carries at most max_entries entries from sequence cursor in order. The
// runtime retains its newest entries across restarts; a cursor older than the
// oldest retained entry reads gap with next at the oldest retained sequence and
// no entries. at_end is true when no entry after the page exists yet. Other
// refusals carry no entries, next equal to cursor and at_end false.
export interface AuditPage {
  outcome: AuditOutcome;
  entries: AuditEntry[];
  next: bigint;
  atEnd: boolean;
}

export type AuditRoute = (typeof AuditRoute)[keyof typeof AuditRoute];
export declare const AuditRoute: Readonly<{ Native: "native"; Window: "window"; Remote: "remote" }>;

export type CancelOutcome = (typeof CancelOutcome)[keyof typeof CancelOutcome];
export declare const CancelOutcome: Readonly<{ Cancelled: "cancelled"; Ended: "ended"; Unknown: "unknown"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// cancelled means this call stopped the operation and closed its upstream
// request; the end delta reads cancelled with reason cancel. ended means the
// operation had already ended, and reply_outcome says how. Both carry
// reply_outcome; other outcomes carry none.
export interface Cancellation {
  outcome: CancelOutcome;
  replyOutcome: ReplyOutcome | null;
}

// A credential's daily limits per UTC day: tokens (input plus output), spend in
// currency millionths, requests, images, audio seconds and characters. Zero or
// absent means no limit in that unit. The provider enforces every configured
// unit at admission and records the applicable units when each profile ends.
export interface CeilingLimit {
  tokensPerDay: bigint;
  microsPerDay: bigint;
  requestsPerDay: bigint;
  imagesPerDay: bigint;
  audioSecondsPerDay: bigint;
  charactersPerDay: bigint;
}

/** Model calls performed by the receiving runtime for the bound caller. Operations are visible only to the account and program that started them. Every request to a hosted host carries headers from abstraction.credentials applier@1 applied for the bound caller, sent once and kept out of every reply, delta, record and log. Caller exit cancels: an operation nobody observes for idle_ms is closed, because a stream nobody reads is spend. A decision point that cannot answer reads unavailable, never permission. */
export declare class ChatClient {
  constructor(transport: FrameTransport);
  /** Admit one model call for the bound caller and begin it. In order: argument shape (invalid), guarantees and host selection through the router (no_host), host features and required extensions (unsupported_feature), the rights decision for abstraction.inference/complete on host:<name> (not_permitted, or unavailable when the decision point cannot answer), the credential's ceiling (budget_exceeded), the caller's concurrent operations (exhausted), then for a hosted host the credentials applier (not_permitted or unavailable). Nothing leaves the service before every check passes. Deltas are observed with Observe. */
  start(request: Request): Promise<Admission>;
  /** Read a bounded page of an operation's deltas from cursor. max_deltas is 1..256, max_bytes 1..65536 and wait_ms 0..30000. When no delta at cursor exists yet and the operation has not ended, wait up to wait_ms for one, then return what is there. An Observe in flight keeps the operation from idling; a caller that disconnects mid-wait stops the wait. Reconnecting with the last next resumes without loss inside retained_deltas. */
  observe(operation: string, cursor: bigint, maxDeltas: bigint, maxBytes: bigint, waitMs: bigint): Promise<DeltaPage>;
  /** Stop an operation the bound caller started and close its upstream request. Reports whether this call cancelled it or it had already ended. */
  cancel(operation: string): Promise<Cancellation>;
}

export declare const ChatService: Readonly<{ wireName: "abstraction.inference/chat@1"; Client: typeof ChatClient }>;

// Spend the host reported for this reply, in millionths of currency, an ISO
// 4217 code or the host's own credit unit. Absent when the host reports no
// cost.
export interface Cost {
  micros: bigint;
  currency: string;
}

// A typed result reference. Completed local work uses location local and a
// canonical sha256 digest readable through the caller's authorized content
// reader. Delegated work uses the remote trust domain as location; its digest
// is not claimed readable in the local store. Refusals carry empty strings and
// size zero.
export interface Delivery {
  digest: string;
  mediaType: string;
  size: bigint;
  location: string;
}

// sequence numbers an operation's deltas from 0 without gaps. chat operations
// use part, usage and end; transcription uses segment and transcription_end;
// speech uses audio chunks and speech_end; live uses transcript, audio and
// live_end; image uses image_progress, image_result and image_end. Text and
// audio bytes are bounded so every delta fits one service frame.
export interface Delta {
  sequence: bigint;
  kind: DeltaKind;
  index: bigint;
  part: Part | null;
  usage: Usage | null;
  end: Reply | null;
  segment: TranscriptSegment | null;
  transcriptionEnd: TranscriptionReply | null;
  audio: AudioChunk | null;
  speechEnd: SpeechReply | null;
  transcript: LiveTranscript | null;
  liveEnd: LiveReply | null;
  imageProgress: ImageProgress | null;
  imageResult: ImageResult | null;
  imageEnd: ImageReply | null;
}

export type DeltaKind = (typeof DeltaKind)[keyof typeof DeltaKind];
export declare const DeltaKind: Readonly<{ Part: "part"; Usage: "usage"; End: "end"; Segment: "segment"; Audio: "audio"; Transcript: "transcript"; ImageProgress: "image_progress"; ImageResult: "image_result" }>;

// page carries 0..max_deltas deltas from sequence cursor in order, within
// max_bytes of their compact JSON encoding except that a first delta larger
// than max_bytes is returned alone. next is the sequence after the last delta
// returned. at_end is true when the page holds the end delta or cursor is
// already past it. gap means cursor is older than the retained deltas: it
// carries no deltas and next set to the oldest retained sequence, from which a
// caller that accepts the loss continues. unknown means no operation of that id
// is visible to the caller: never started by it, retired after retention, or
// from an earlier provider epoch. Other refusals carry no deltas, next equal to
// cursor and at_end false.
export interface DeltaPage {
  outcome: PageOutcome;
  deltas: Delta[];
  next: bigint;
  atEnd: boolean;
}

export declare class DispatchError extends Error {
  constructor(code: string);
  code: string;
}

export type EditOutcome = (typeof EditOutcome)[keyof typeof EditOutcome];
export declare const EditOutcome: Readonly<{ Applied: "applied"; Conflict: "conflict"; Unknown: "unknown"; Invalid: "invalid"; NoSecureStore: "no_secure_store"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

export type EmbedOutcome = (typeof EmbedOutcome)[keyof typeof EmbedOutcome];
export declare const EmbedOutcome: Readonly<{ Completed: "completed"; Refused: "refused"; NotPermitted: "not_permitted"; BudgetExceeded: "budget_exceeded"; UnsupportedFeature: "unsupported_feature"; NoHost: "no_host"; Unavailable: "unavailable"; Invalid: "invalid"; Forbidden: "forbidden" }>;

// model is a model family or alias as in Request. inputs is 1..64 texts of
// 1..32768 bytes each. dimensions, when not zero, is 1..4096 and asks the host
// for vectors of that length; a reply of another length reads unavailable with
// reason upstream:dimensions. guarantees and credential select hosts and spend
// exactly as in Request. extensions holds vendor-prefixed keys <owner>/<name>
// with string values that a host ignores unless it knows them. The encoded
// request fits one 1 MiB control frame.
export interface EmbedRequest {
  model: string;
  inputs: string[];
  dimensions: bigint;
  guarantees: Array<RequestGuarantee | (string & {})>;
  credential: string;
  extensions: { [key: string]: string };
}

/** Text embeddings computed by a host the receiving runtime picks, for the bound caller. Every request to a hosted host carries headers from abstraction.credentials applier@1 applied once for the bound caller and kept out of every reply, record and log. A decision point that cannot answer reads unavailable, never permission. */
export declare class EmbedderClient {
  constructor(transport: FrameTransport);
  /** Embed texts for the bound caller in one bounded call. Admission follows Chat.Start's order for profile embed, without its feature and capacity steps: argument shape (invalid), guarantees and host selection (no_host), the host's wire (unsupported_feature), the rights decision for abstraction.inference/complete on host:<name> (not_permitted, or unavailable), the credential's ceiling (budget_exceeded), then for a hosted host the credentials applier with consumer abstraction.inference/embed@1. Nothing leaves the service before every check passes. The call returns when the host replies. */
  embed(request: EmbedRequest): Promise<Embeddings>;
}

export declare const EmbedderService: Readonly<{ wireName: "abstraction.inference/embed@1"; Client: typeof EmbedderClient }>;

// completed carries one vector per input, in input order, each the standard
// base64 of dimensions little-endian IEEE 754 float32 values, and dimensions of
// at least 1. The vectors of one reply hold at most 131072 values together; a
// larger upstream reply reads unavailable with reason upstream:too_large, and a
// caller embedding long vectors sends fewer inputs. usage.input is the input
// tokens the host counted. Every other outcome carries no vectors, zero
// dimensions, zero usage, and the reason words of Reply; unsupported_feature
// carries wire:<kind> for a host whose wire has no embeddings call. host and
// model name what served the call, and are empty when nothing did.
export interface Embeddings {
  outcome: EmbedOutcome;
  reason: string;
  vectors: string[];
  dimensions: bigint;
  usage: Usage;
  host: string;
  model: string;
  cost: Cost | null;
}

// applied carries the new setting revision; the runtime has opened or closed
// the window before replying. conflict means expected_revision is not current
// and carries the current revision. invalid carries the field in reason:
// address when it is not 127.0.0.1:<port>. unavailable carries listen:<detail>
// in reason when the setting was written and the window could not listen. Other
// outcomes carry an empty revision.
export interface GatewayChange {
  outcome: EditOutcome;
  revision: string;
  reason: string;
}

// page carries the gateway window setting kept in the runtime state at
// revision, and the window in this runtime now. open and address are the
// setting; it is off by default and address is empty until one is set.
// listening is true when the window accepts connections at listening_address. A
// window opened for this process by serve runtime --gateway reads listening
// with the setting unchanged. why names the failure when open is set and the
// window is not listening, as listen:<detail>. Refusals carry an empty
// revision, addresses and why, and open and listening false.
export interface GatewayState {
  outcome: ListOutcome;
  revision: string;
  open: boolean;
  address: string;
  listening: boolean;
  listeningAddress: string;
  why: string;
}

// applied carries the new configuration revision; the runtime reads the hosts
// again at once. conflict means expected_revision is not current, or AddHost
// named an existing host, and carries the current revision. unknown means
// RemoveHost named no host. invalid carries the field in reason. Other outcomes
// carry an empty revision. no_secure_store is not used by host edits.
export interface HostChange {
  outcome: EditOutcome;
  revision: string;
  reason: string;
}

// One host the runtime reaches, kept as an abstraction.facade/registry@1
// declaration of role host. A remote runtime is a declaration of role remote;
// router@1 Hosts lists its hosts as <name>/<host>. profiles holds 1..16
// distinct host_profiles members or <owner>/<name>@<n>; empty in AddHost
// selects the wire's default: openai-compatible and every local kind serve
// chat, embed, transcription, speech and image, and anthropic-messages and any
// other wire serve chat. declared_by is asserted by the runtime, operator for a
// host added through AddHost, and AddHost refuses a non-empty value as invalid.
// name is 1..64 bytes of a-z 0-9 _ - and unique. A local host (hosted false)
// names a local_host_kinds member as both name and kind, and the base URL of
// that runtime on this machine, and carries no credential or ceiling. A hosted
// host names a wire kind (router wire_kinds or <owner>/<name>@<n>), its https
// or loopback http API root, the abstraction.credentials name the service
// applies to it, and optionally that credential's ceiling. base carries no user
// information, query or fragment.
export interface HostEntry {
  name: string;
  hosted: boolean;
  kind: string;
  base: string;
  credential: string;
  ceiling: CeilingLimit | null;
  profiles: string[];
  declaredBy: string;
}

// page carries every configured host, at most 64, and the configuration
// revision AddHost and RemoveHost take. invalid is reserved for a request this
// provider cannot interpret. Refusals carry an empty revision and no hosts.
export interface HostList {
  outcome: ListOutcome;
  revision: string;
  hosts: HostState[];
}

// A configured host and the router's latest reading of it: up, or why not.
// spend is present for a hosted host that names a credential.
export interface HostState {
  entry: HostEntry;
  up: boolean;
  why: string;
  spend: Spend | null;
}

/** Image generation and edit with authorized digest inputs, bounded progress and typed result deliveries. Operations are visible only through this profile to the account and program that started them. */
export declare class ImageClient {
  constructor(transport: FrameTransport);
  /** Admit image generation or edit for the bound caller. Admission checks arguments, explicit host mode/size/count support, complete rights, authorized input and mask resolution, output-write preflight, ceiling, shared capacity and the profile-scoped credential before paid work. */
  start(request: ImageRequest): Promise<Admission>;
  /** Read retained progress, result and terminal deltas with the shared operation cursor, page, reconnect, wait and idle semantics. */
  observe(operation: string, cursor: bigint, maxDeltas: bigint, maxBytes: bigint, waitMs: bigint): Promise<DeltaPage>;
  /** Stop image work, including queue polling, and cancel the upstream job where its wire supports cancellation. */
  cancel(operation: string): Promise<Cancellation>;
}

export type ImageMode = (typeof ImageMode)[keyof typeof ImageMode];
export declare const ImageMode: Readonly<{ Generate: "generate"; Edit: "edit" }>;

// One bounded progress update. percent, when nonzero, is 1..100; zero means the
// backend reported no numeric progress. message is at most 4096 UTF-8 bytes and
// contains no submitted content or credential material.
export interface ImageProgress {
  percent: bigint;
  message: string;
}

// The terminal result of one image operation. Completed carries exactly count
// ordered deliveries equal to the streamed image_result deltas and images is
// the charged output count. Other outcomes carry no deliveries. host and model
// name what served the call.
export interface ImageReply {
  outcome: ReplyOutcome;
  reason: string;
  deliveries: Delivery[];
  images: bigint;
  usage: Usage;
  host: string;
  model: string;
  cost: Cost | null;
}

// One image generation or edit request. prompt is 1..32768 UTF-8 bytes. size is
// auto or WIDTHxHEIGHT with positive decimal dimensions. count is 1..10.
// Generate carries no input digests. Edit carries one canonical image SHA-256
// digest and media type and may carry one canonical mask digest and media type.
// Input media types are PNG, JPEG or WebP; masks are PNG. Digests are
// authorized and resolved only by the selected runtime. extensions holds
// declared vendor workflow or template controls; a named required extension
// absent from the selected adapter is refused before paid work. No URL, file
// path, key, header, inline image or workflow crosses this request.
export interface ImageRequest {
  model: string;
  mode: ImageMode;
  prompt: string;
  size: string;
  count: bigint;
  imageDigest: string;
  imageMediaType: string;
  maskDigest: string;
  maskMediaType: string;
  guarantees: Array<RequestGuarantee | (string & {})>;
  credential: string;
  requiredExtensions: string[];
  extensions: { [key: string]: string };
}

// One completed image in request order. index is 0..count-1. delivery
// identifies an authorized PNG, JPEG or WebP result and the runtime that owns
// it.
export interface ImageResult {
  index: bigint;
  delivery: Delivery;
}

export declare const ImageService: Readonly<{ wireName: "abstraction.inference/image@1"; Client: typeof ImageClient }>;

// applied carries the key, once, and its record. The key is the only secret
// operator@1 ever returns: the runtime minted it, it authorizes nothing by
// itself, and no later call reads it back. The operator gives it to the
// program, for example as that program's API key setting. conflict means the
// program holds an active key; revoke it first. invalid carries the field in
// reason. no_secure_store means the runtime has no platform store to hold it.
// Other outcomes carry no key and no record.
export interface KeyIssued {
  outcome: EditOutcome;
  reason: string;
  key: string;
  record: LocalKey | null;
}

// page carries every retained local key of the receiving account, at most 256,
// revoked ones included. Refusals carry no keys.
export interface KeyList {
  outcome: ListOutcome;
  keys: LocalKey[];
}

// applied destroys the key in the platform store; the window refuses it from
// the next request. unknown means the program holds no active key.
export interface KeyRevoked {
  outcome: EditOutcome;
}

export type KeyState = (typeof KeyState)[keyof typeof KeyState];
export declare const KeyState: Readonly<{ Active: "active"; Revoked: "revoked"; Lost: "lost" }>;

export type ListOutcome = (typeof ListOutcome)[keyof typeof ListOutcome];
export declare const ListOutcome: Readonly<{ Page: "page"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

/** Live audio through bounded native IPC calls. One session produces one final response. A new response starts a new session. Credentials and vendor WebSockets stay in the service. */
export declare class LiveClient {
  constructor(transport: FrameTransport);
  /** Admit a live session after host support, complete permission, output-write preflight, budget, shared capacity and credential checks. The service owns the upstream session. Observe reports setup failures after admission. */
  start(request: LiveRequest): Promise<Admission>;
  /** Append 1..65536 even-sized PCM bytes at the expected sequence. Bounded input and idle limits apply. Concurrent appends are serialized; only confirmed sends advance next_sequence. */
  append(operation: string, sequence: bigint, audio: Uint8Array): Promise<LiveInputResult>;
  /** Read retained transcript, audio and terminal deltas using shared cursor and wait semantics. */
  observe(operation: string, cursor: bigint, maxDeltas: bigint, maxBytes: bigint, waitMs: bigint): Promise<DeltaPage>;
  /** Close input and request the final response. A repeated Commit is duplicate. Observe continues until terminal delivery or failure; Commit does not wait for synthesis to finish. */
  commit(operation: string): Promise<LiveInputResult>;
  /** Immediately stop the live session and its upstream connection. Uses shared operation cancellation and ownership semantics. */
  cancel(operation: string): Promise<Cancellation>;
}

export type LiveFormat = (typeof LiveFormat)[keyof typeof LiveFormat];
export declare const LiveFormat: Readonly<{ Pcm1624000: "pcm16_24000" }>;

export type LiveInputOutcome = (typeof LiveInputOutcome)[keyof typeof LiveInputOutcome];
export declare const LiveInputOutcome: Readonly<{ Accepted: "accepted"; Duplicate: "duplicate"; OutOfOrder: "out_of_order"; Closed: "closed"; Invalid: "invalid"; Unknown: "unknown"; Forbidden: "forbidden"; Unavailable: "unavailable"; Exhausted: "exhausted" }>;

// next_sequence is the next Append sequence expected, starting at zero. A retry
// of the most recently acknowledged identical frame is duplicate and sends
// nothing upstream. Other repeated or skipped sequences are out_of_order. After
// Commit no Append is accepted. An uncertain upstream write ends the session as
// unavailable; the service never retries it.
export interface LiveInputResult {
  outcome: LiveInputOutcome;
  nextSequence: bigint;
}

// Final live-session outcome. Completed output audio is committed through the
// original caller's authorized content writer; delivery names those exact
// bytes. Failed sessions carry empty delivery. Input and output byte counts
// describe PCM processed, and usage carries upstream token counts.
export interface LiveReply {
  outcome: ReplyOutcome;
  reason: string;
  delivery: Delivery;
  usage: Usage;
  inputAudioBytes: bigint;
  outputAudioBytes: bigint;
  host: string;
  model: string;
}

// One live audio response session. pcm16_24000 is mono signed 16-bit
// little-endian PCM at 24000 Hz for input and output. Voice is 1..256 safe
// URL-component bytes. Guarantees and credential have Request meanings. Start
// creates one session; Commit finishes its input and requests one final model
// response.
export interface LiveRequest {
  model: string;
  voice: string;
  format: LiveFormat;
  guarantees: Array<RequestGuarantee | (string & {})>;
  credential: string;
  extensions: { [key: string]: string };
}

export declare const LiveService: Readonly<{ wireName: "abstraction.inference/live@1"; Client: typeof LiveClient }>;

// One bounded output transcript fragment, at most 16384 UTF-8 bytes. Fragments
// append in delta order. A final marker may have empty text. It marks
// transcript completion, not session completion.
export interface LiveTranscript {
  text: string;
  isFinal: boolean;
}

// A local key minted for one program. program is the normalized absolute
// executable path the window requires of the bound peer presenting the key.
// name is the abstraction.credentials record holding it as kind
// openabstractions/local-key@1. credential, when present, is the hosted
// credential name the window's requests may spend under; without it the
// window's requests are local-only. issued_unix_ms is when it was minted, in
// milliseconds since the Unix epoch. issued_by is the operator program that
// issued it. lost means the platform store no longer holds the key. Metadata
// only; no field derives from the key.
export interface LocalKey {
  program: string;
  name: string;
  credential: string;
  issuedUnixMs: bigint;
  issuedBy: string;
  state: KeyState;
}

// parts is 1..64 parts in a request. A reply message has role assistant.
export interface Message {
  role: Role;
  parts: Part[];
}

/** Administer the runtime's inference hosts, the gateway window and its local keys, and read the inference audit. Each call is a rights decision for the bound operator subject; same-account identity alone grants nothing. A decision point that cannot answer reads unavailable. */
export declare class OperatorClient {
  constructor(transport: FrameTransport);
  /** Read the configured hosts, their router state and each hosted credential's spend today, from the registry's declarations of role host. Gated by abstraction.inference/host.manage on resource account. */
  hosts(): Promise<HostList>;
  /** Conditionally add one host, kept as a registry declaration of role host. Gated by host.manage. For the bound operator program and the runtime's other operator programs it also writes the permit rule abstraction.inference/complete on host:<name>, and for a hosted host with a credential it writes the runtime's own permit rule abstraction.credentials/apply on credential:<name>, which the router's listing reads need. Existing rules are left as they are. */
  addHost(expectedRevision: string, host: HostEntry): Promise<HostChange>;
  /** Conditionally remove one host; operations already admitted run to their end. Gated by host.manage. A host the installation or a product declared is disabled by name instead of removed. Rules are left as they are. */
  removeHost(expectedRevision: string, name: string): Promise<HostChange>;
  /** Read the local keys of the receiving account. Gated by abstraction.inference/key.issue on resource account. */
  keys(): Promise<KeyList>;
  /** Mint a local key for program, an absolute executable path, and hold it in the platform store. credential, when not empty, names the hosted credential the window's requests for that program may spend under. Gated by key.issue. The key grants nothing: the window still binds the peer, requires that program, and decides abstraction.inference/complete and credentials apply for it. */
  issueKey(program: string, credential: string): Promise<KeyIssued>;
  /** Destroy the active local key of program. Gated by key.issue. */
  revokeKey(program: string): Promise<KeyRevoked>;
  /** Read retained inference decisions from both routes. Gated by abstraction.inference/audit.read on resource account. cursor 0 starts at the oldest retained entry; max_entries is 1..256. */
  audit(cursor: bigint, maxEntries: bigint): Promise<AuditPage>;
  /** Read the gateway window setting and whether the window listens now. Gated by abstraction.inference/host.manage on resource account. */
  gateway(): Promise<GatewayState>;
  /** Conditionally write the gateway window setting to the runtime state and apply it to the running runtime: open listens on address, and closed stops the listener and every window connection. address is 127.0.0.1:<port>; empty keeps the recorded address when opening, and 127.0.0.1:8793 when none is recorded. The setting survives a restart. Gated by host.manage. */
  setGateway(expectedRevision: string, open: boolean, address: string): Promise<GatewayChange>;
}

export declare const OperatorService: Readonly<{ wireName: "abstraction.inference/operator@1"; Client: typeof OperatorClient }>;

// max_output bounds output tokens (0 is the host's default). temperature, when
// absent, is the host's default. stop is 0..8 sequences. json_schema is a JSON
// Schema object as JSON text the reply must satisfy; a host without
// abstraction.inference/json-schema@1 refuses it.
export interface Options {
  maxOutput: bigint;
  temperature: Temperature | null;
  stop: string[];
  jsonSchema: string;
}

export type PageOutcome = (typeof PageOutcome)[keyof typeof PageOutcome];
export declare const PageOutcome: Readonly<{ Page: "page"; Gap: "gap"; Unknown: "unknown"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// One piece of a message. text: text. image: only in a user message; digest is
// a canonical lowercase sha256 digest, media_type is one of image/png,
// image/jpeg, image/gif or image/webp, and the bytes are resolved under the
// original caller's rights and verified before upstream. No image bytes travel
// in a request. tool_call: call_id, name and arguments, a JSON text.
// tool_result: call_id and text. Fields a kind does not name are empty. In a
// delta, a part extends the reply part at its index: text and arguments append,
// and call_id, name, digest and media_type are set by the first delta of that
// index.
export interface Part {
  kind: PartKind;
  text: string;
  digest: string;
  mediaType: string;
  callId: string;
  name: string;
  arguments: string;
}

export type PartKind = (typeof PartKind)[keyof typeof PartKind];
export declare const PartKind: Readonly<{ Text: "text"; Image: "image"; ToolCall: "tool_call"; ToolResult: "tool_result" }>;

export declare class Refusal extends Error {
  constructor(word: string, offset: number);
  word: "malformed" | "bad_string" | "bad_binary" | "number_spelling" | "wrong_type" | "depth_exceeded" | "duplicate_key" | "duplicate_field" | "unknown_field" | "missing_field" | "bad_enum" | "trailing_bytes";
  offset: number;
}

// The result of one operation. completed carries the assistant message and
// stop_reason other than no_stop; every other outcome carries no_stop. refused
// means the host answered and refused the request (reason upstream:<status>).
// not_permitted carries reason rights:<word> for the complete decision on
// host:<name>, or credential:<outcome>:<name> for an applier refusal.
// budget_exceeded carries ceiling:<unit>:<credential>. unsupported_feature
// carries feature:<name> or extension:<key>. no_host carries router:<verdict>.
// cancelled carries cancel, idle or caller. unavailable carries
// rights:unavailable, credential:unavailable:<name> or upstream:<detail>; parts
// already delivered stay delivered. host and model name what served it, and are
// empty when nothing did. In the terminal delta message.parts is empty; the
// parts arrived in the deltas before it.
export interface Reply {
  outcome: ReplyOutcome;
  reason: string;
  message: Message;
  stopReason: StopReason;
  usage: Usage;
  host: string;
  model: string;
  cost: Cost | null;
}

export type ReplyOutcome = (typeof ReplyOutcome)[keyof typeof ReplyOutcome];
export declare const ReplyOutcome: Readonly<{ Completed: "completed"; Refused: "refused"; NotPermitted: "not_permitted"; BudgetExceeded: "budget_exceeded"; UnsupportedFeature: "unsupported_feature"; NoHost: "no_host"; Cancelled: "cancelled"; Unavailable: "unavailable"; Invalid: "invalid"; Forbidden: "forbidden"; Exhausted: "exhausted" }>;

// model is a model family or any alias a host lists it under, as
// abstraction.router/router@1 folds names. messages is 1..512. tools is 0..128.
// extensions holds vendor-prefixed keys <owner>/<name> with string values; a
// host ignores a key it does not know unless required_extensions names it, and
// then refuses unsupported_feature with reason extension:<key>. guarantees
// holds RequestGuarantee members. credential names an abstraction.credentials
// entry of the caller's account that a hosted host may spend under. The request
// carries no base URL, key, header or host name, and the encoded request fits
// one 1 MiB control frame.
export interface Request {
  model: string;
  messages: Message[];
  tools: Tool[];
  options: Options | null;
  extensions: { [key: string]: string };
  requiredExtensions: string[];
  guarantees: Array<RequestGuarantee | (string & {})>;
  credential: string;
}

export type RequestGuarantee = (typeof RequestGuarantee)[keyof typeof RequestGuarantee];
export declare const RequestGuarantee: Readonly<{ LocalOnly: "abstraction.inference/local-only@1"; HostedAllowed: "abstraction.inference/hosted-allowed@1" }>;

export type Role = (typeof Role)[keyof typeof Role];
export declare const Role: Readonly<{ System: "system"; User: "user"; Assistant: "assistant"; Tool: "tool" }>;

export declare class ServiceError extends Error {
  constructor(code: string, message?: string);
  code: string;
}

export type ServiceErrorCode = (typeof ServiceErrorCode)[keyof typeof ServiceErrorCode];
export declare const ServiceErrorCode: Readonly<{ HandlerError: "handler_error"; InvalidResult: "invalid_result"; UnknownVersion: "unknown_version"; UnknownService: "unknown_service"; UnknownMethod: "unknown_method"; WrongMode: "wrong_mode" }>;

/** Streaming text-to-speech with bounded audio deltas and a final storage reference. Operations are visible only through this profile to the account and program that started them. */
export declare class SpeechClient {
  constructor(transport: FrameTransport);
  /** Admit text-to-speech for the bound caller. Admission follows chat order for profile speech: arguments, host and wire/format support, complete rights, authorized output-write preflight, ceiling, capacity, then the profile-scoped hosted credential. Nothing leaves the service before every check passes. */
  start(request: SpeechRequest): Promise<Admission>;
  /** Read retained audio and terminal deltas with the shared operation cursor, page, reconnect, wait and idle semantics. */
  observe(operation: string, cursor: bigint, maxDeltas: bigint, maxBytes: bigint, waitMs: bigint): Promise<DeltaPage>;
  /** Stop a speech operation and close its upstream request, using the shared operation cancellation outcomes. */
  cancel(operation: string): Promise<Cancellation>;
}

export type SpeechFormat = (typeof SpeechFormat)[keyof typeof SpeechFormat];
export declare const SpeechFormat: Readonly<{ Mp3: "mp3"; Opus: "opus"; Aac: "aac"; Flac: "flac"; Wav: "wav"; Pcm: "pcm" }>;

// The terminal result of one speech operation. completed carries the exact
// concatenated audio as a typed delivery and the Unicode scalar count charged.
// Other outcomes carry an empty delivery. host and model name what served the
// call.
export interface SpeechReply {
  outcome: ReplyOutcome;
  reason: string;
  delivery: Delivery;
  characters: bigint;
  usage: Usage;
  host: string;
  model: string;
  cost: Cost | null;
}

// One text-to-speech request. voice is a backend voice name or id of 1..256
// safe URL-component bytes. text is 1..4096 Unicode scalar values and at most
// 16384 UTF-8 bytes. format is a codec the selected host explicitly supports.
// guarantees, credential and extensions have Request's meanings. No URL, path,
// key or header crosses this request.
export interface SpeechRequest {
  model: string;
  voice: string;
  text: string;
  format: SpeechFormat;
  guarantees: Array<RequestGuarantee | (string & {})>;
  credential: string;
  extensions: { [key: string]: string };
}

export declare const SpeechService: Readonly<{ wireName: "abstraction.inference/speech@1"; Client: typeof SpeechClient }>;

// What a credential has spent on UTC day (YYYY-MM-DD), counted from provider
// replies: tokens, currency millionths, requests, generated images, whole audio
// seconds and characters.
export interface Spend {
  day: string;
  tokens: bigint;
  micros: bigint;
  requests: bigint;
  audioSeconds: bigint;
  characters: bigint;
  images: bigint;
}

export type StartOutcome = (typeof StartOutcome)[keyof typeof StartOutcome];
export declare const StartOutcome: Readonly<{ Accepted: "accepted"; NotPermitted: "not_permitted"; BudgetExceeded: "budget_exceeded"; UnsupportedFeature: "unsupported_feature"; NoHost: "no_host"; Unavailable: "unavailable"; Invalid: "invalid"; Forbidden: "forbidden"; Exhausted: "exhausted" }>;

export type StopReason = (typeof StopReason)[keyof typeof StopReason];
export declare const StopReason: Readonly<{ NoStop: "no_stop"; End: "end"; MaxOutput: "max_output"; StopSequence: "stop_sequence"; ToolCalls: "tool_calls"; ContentFilter: "content_filter"; Other: "other" }>;

// Sampling temperature in thousandths, 0..2000.
export interface Temperature {
  milli: bigint;
}

export type TimestampMode = (typeof TimestampMode)[keyof typeof TimestampMode];
export declare const TimestampMode: Readonly<{ None: "none"; Segment: "segment"; Word: "word"; SegmentAndWord: "segment_and_word" }>;

// A function the model may call. name is 1..64 bytes of A-Z a-z 0-9 _ -;
// parameters is a JSON Schema object as JSON text.
export interface Tool {
  name: string;
  description: string;
  parameters: string;
}

// One ordered transcript unit. index starts at zero separately for segment and
// word units. start_ms and end_ms are within the input duration, start_ms <=
// end_ms, and text is at most 32768 UTF-8 bytes so its delta fits a bounded
// page and service frame.
export interface TranscriptSegment {
  index: bigint;
  kind: TranscriptUnitKind;
  startMs: bigint;
  endMs: bigint;
  text: string;
}

export type TranscriptUnitKind = (typeof TranscriptUnitKind)[keyof typeof TranscriptUnitKind];
export declare const TranscriptUnitKind: Readonly<{ Segment: "segment"; Word: "word" }>;

/** Prerecorded speech-to-text over an authorized content digest. Operations use the shared retained-delta lifecycle and are visible only through this profile to the account and program that started them. */
export declare class TranscriptionClient {
  constructor(transport: FrameTransport);
  /** Admit one prerecorded transcription for the bound caller. Admission follows chat order for profile transcription: arguments, host and wire/format support, complete rights, authorized bounded content resolution and verification, ceiling, capacity, then the profile-scoped hosted credential. Nothing leaves the service before all checks pass. */
  start(request: TranscriptionRequest): Promise<Admission>;
  /** Read retained segment and terminal deltas with the shared operation cursor, page, reconnect, wait and idle semantics. */
  observe(operation: string, cursor: bigint, maxDeltas: bigint, maxBytes: bigint, waitMs: bigint): Promise<DeltaPage>;
  /** Stop a transcription operation and close its upstream request, using the shared operation cancellation outcomes. */
  cancel(operation: string): Promise<Cancellation>;
}

// The terminal result of one transcription operation. completed carries the
// detected or requested language and input duration in milliseconds. Other
// outcomes carry the common Reply outcome and reason words. unavailable reports
// malformed or inconsistent upstream results. host and model name what served
// the call, and are empty when nothing did.
export interface TranscriptionReply {
  outcome: ReplyOutcome;
  reason: string;
  language: string;
  durationMs: bigint;
  usage: Usage;
  host: string;
  model: string;
  cost: Cost | null;
}

// A prerecorded transcription input. audio_digest is a canonical lowercase
// sha256 reference read through storage under the original caller's authority;
// bytes never cross this request. media_type is audio/wav, audio/mpeg,
// audio/mp4, audio/webm, audio/ogg or audio/flac. language is empty for
// detection or a 1..35 byte BCP-47-like tag. timestamps selects no units,
// segments, words or both; segment has no additional upstream latency and word
// may cost more. guarantees, credential and extensions have Request's meanings.
// The encoded request fits one 1 MiB control frame.
export interface TranscriptionRequest {
  model: string;
  audioDigest: string;
  mediaType: string;
  language: string;
  timestamps: TimestampMode;
  guarantees: Array<RequestGuarantee | (string & {})>;
  credential: string;
  extensions: { [key: string]: string };
}

export declare const TranscriptionService: Readonly<{ wireName: "abstraction.inference/transcription@1"; Client: typeof TranscriptionClient }>;

// Token counts the host reported: input, output, and cached input tokens
// counted within input. Zero where the host reported none.
export interface Usage {
  input: bigint;
  output: bigint;
  cached: bigint;
}

export declare const claimExtensions: readonly ["openabstractions/claimed-program"];

export declare const credentialConsumers: readonly ["abstraction.inference/chat@1", "abstraction.inference/embed@1", "abstraction.inference/transcription@1", "abstraction.inference/speech@1", "abstraction.inference/live@1"];

export declare function decode(data: Uint8Array): Request;

export declare function encode(v: Request): Uint8Array;

export declare const features: readonly ["abstraction.inference/tools@1", "abstraction.inference/json-schema@1", "abstraction.inference/vision@1"];

export declare const hostDeclarers: readonly ["operator", "ollama", "lmstudio", "docker-model-runner", "foundry-local", "installation", "default"];

export declare const hostProfiles: readonly ["chat", "embed", "transcription", "speech", "image", "live"];

export declare const localHostKinds: readonly ["ollama", "lmstudio", "lemonade", "whispercpp", "piper", "comfyui", "swarmui", "docker-model-runner", "foundry-local"];

export declare const localKeyKinds: readonly ["openabstractions/local-key@1"];

export declare function newAdmission(): Admission;

export declare function newAudioChunk(): AudioChunk;

export declare function newAuditEntry(): AuditEntry;

export declare function newAuditPage(): AuditPage;

export declare function newCancellation(): Cancellation;

export declare function newCeilingLimit(): CeilingLimit;

export declare function newCost(): Cost;

export declare function newDelivery(): Delivery;

export declare function newDelta(): Delta;

export declare function newDeltaPage(): DeltaPage;

export declare function newEmbedRequest(): EmbedRequest;

export declare function newEmbeddings(): Embeddings;

export declare function newGatewayChange(): GatewayChange;

export declare function newGatewayState(): GatewayState;

export declare function newHostChange(): HostChange;

export declare function newHostEntry(): HostEntry;

export declare function newHostList(): HostList;

export declare function newHostState(): HostState;

export declare function newImageProgress(): ImageProgress;

export declare function newImageReply(): ImageReply;

export declare function newImageRequest(): ImageRequest;

export declare function newImageResult(): ImageResult;

export declare function newKeyIssued(): KeyIssued;

export declare function newKeyList(): KeyList;

export declare function newKeyRevoked(): KeyRevoked;

export declare function newLiveInputResult(): LiveInputResult;

export declare function newLiveReply(): LiveReply;

export declare function newLiveRequest(): LiveRequest;

export declare function newLiveTranscript(): LiveTranscript;

export declare function newLocalKey(): LocalKey;

export declare function newMessage(): Message;

export declare function newOptions(): Options;

export declare function newPart(): Part;

export declare function newReply(): Reply;

export declare function newRequest(): Request;

export declare function newSpeechReply(): SpeechReply;

export declare function newSpeechRequest(): SpeechRequest;

export declare function newSpend(): Spend;

export declare function newTemperature(): Temperature;

export declare function newTool(): Tool;

export declare function newTranscriptSegment(): TranscriptSegment;

export declare function newTranscriptionReply(): TranscriptionReply;

export declare function newTranscriptionRequest(): TranscriptionRequest;

export declare function newUsage(): Usage;

export declare const resourceActions: readonly ["abstraction.inference/complete", "abstraction.inference/host.manage", "abstraction.inference/key.issue", "abstraction.inference/audit.read"];

export {};
