// Code generated by abstraction-idl from abstraction-inference/job.thrift. DO NOT EDIT.

package job

type Raw = string

func escByte(out []byte, c byte) []byte {
	const hex = "0123456789abcdef"
	switch c {
	case '"':
		return append(out, '\\', '"')
	case '\\':
		return append(out, '\\', '\\')
	case 0x08:
		return append(out, '\\', 'b')
	case 0x0c:
		return append(out, '\\', 'f')
	case '\n':
		return append(out, '\\', 'n')
	case '\r':
		return append(out, '\\', 'r')
	case '\t':
		return append(out, '\\', 't')
	}
	if c < 0x20 {
		return append(out, '\\', 'u', '0', '0', hex[c>>4], hex[c&0xF])
	}
	return append(out, c)
}

func num(out []byte, n int64) []byte {
	if n == 0 {
		return append(out, '0')
	}
	var d [24]byte
	p := len(d)
	u := uint64(n)
	if n < 0 {
		u = -uint64(n)
	}
	for u > 0 {
		p--
		d[p] = byte('0' + u%10)
		u /= 10
	}
	if n < 0 {
		out = append(out, '-')
	}
	return append(out, d[p:]...)
}

func pad(out []byte, depth int) []byte {
	for i := 0; i < depth*2; i++ {
		out = append(out, ' ')
	}
	return out
}

func strs(out []byte, v []string, depth int) []byte {
	if len(v) == 0 {
		return append(out, '[', ']')
	}
	out = append(out, '[', '\n')
	for i, s := range v {
		out = pad(out, depth+1)
		out = esc(out, s)
		if i+1 < len(v) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, ']')
}

func enumStrs[T any](out []byte, v []T, depth int, word func(T) string) []byte {
	if len(v) == 0 {
		return append(out, '[', ']')
	}
	out = append(out, '[', '\n')
	for i, item := range v {
		out = pad(out, depth+1)
		out = esc(out, word(item))
		if i+1 < len(v) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, ']')
}

func raw(out []byte, s string, depth int) []byte {
	ws := func(c byte) bool { return c == ' ' || c == '\t' || c == '\n' || c == '\r' }
	for i := 0; i < len(s); {
		c := s[i]
		if ws(c) {
			i++
			continue
		}
		switch c {
		case '"':
			j := i + 1
			for j < len(s) {
				if s[j] == '\\' {
					j += 2
					continue
				}
				if s[j] == '"' {
					j++
					break
				}
				j++
			}
			out = append(out, s[i:j]...)
			i = j
		case '{', '[':
			out = append(out, c)
			i++
			j := i
			for j < len(s) && ws(s[j]) {
				j++
			}
			if j < len(s) && (s[j] == '}' || s[j] == ']') {
				out = append(out, s[j])
				i = j + 1
			} else {
				depth++
				out = append(out, '\n')
				out = pad(out, depth)
			}
		case '}', ']':
			depth--
			out = append(out, '\n')
			out = pad(out, depth)
			out = append(out, c)
			i++
		case ',':
			out = append(out, ',', '\n')
			out = pad(out, depth)
			i++
		case ':':
			out = append(out, ':', ' ')
			i++
		default:
			out = append(out, c)
			i++
		}
	}
	return out
}

func byteLess(a, b string) bool {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return a[i] < b[i]
		}
	}
	return len(a) < len(b)
}

func sortedKeys(m map[string]Raw) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && byteLess(keys[j], keys[j-1]); j-- {
			keys[j], keys[j-1] = keys[j-1], keys[j]
		}
	}
	return keys
}

func rawmap(out []byte, m map[string]Raw, depth int) []byte {
	keys := sortedKeys(m)
	if len(keys) == 0 {
		return append(out, '{', '}')
	}
	out = append(out, '{', '\n')
	for i, k := range keys {
		out = pad(out, depth+1)
		out = esc(out, k)
		out = append(out, ':', ' ')
		out = raw(out, m[k], depth+1)
		if i+1 < len(keys) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, '}')
}

func esc(out []byte, s string) []byte {
	out = append(out, '"')
	for i := 0; i < len(s); i++ {
		out = escByte(out, s[i])
	}
	return append(out, '"')
}

func strmap(out []byte, m map[string]string, depth int) []byte {
	keys := sortedKeys(m)
	if len(keys) == 0 {
		return append(out, '{', '}')
	}
	out = append(out, '{', '\n')
	for i, k := range keys {
		out = pad(out, depth+1)
		out = esc(out, k)
		out = append(out, ':', ' ')
		out = esc(out, m[k])
		if i+1 < len(keys) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, '}')
}

func encList[T any](out []byte, v []T, depth int, enc func([]byte, *T, int) []byte) []byte {
	if len(v) == 0 {
		return append(out, '[', ']')
	}
	out = append(out, '[', '\n')
	for i := range v {
		out = pad(out, depth+1)
		out = enc(out, &v[i], depth+1)
		if i+1 < len(v) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, ']')
}

// Profile is a closed vocabulary. Its numeric values are private implementation
// tags; String and ParseProfile preserve the exact wire words.
type Profile uint32

const (
	ProfileVideo      Profile = 1
	ProfileImageBatch Profile = 2
)

// String returns v's exact wire word, or the empty string for an invalid value.
func (v Profile) String() string {
	word, _ := v.WireName()
	return word
}

// WireName returns v's exact wire word and whether v names a member.
func (v Profile) WireName() (string, bool) {
	switch v {
	case ProfileVideo:
		return "video", true
	case ProfileImageBatch:
		return "image_batch", true
	}
	return "", false
}

// ParseProfile returns the member named by an exact wire word.
func ParseProfile(word string) (Profile, bool) {
	switch word {
	case "video":
		return ProfileVideo, true
	case "image_batch":
		return ProfileImageBatch, true
	}
	return Profile(0), false
}

// MarshalText preserves the member's exact wire word for standard text users,
// including JSON object keys. Invalid and zero values are refused.
func (v Profile) MarshalText() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return []byte(word), nil
}

// UnmarshalText accepts an exact wire word and refuses unknown text.
func (v *Profile) UnmarshalText(text []byte) error {
	word, ok := ParseProfile(string(text))
	if !ok {
		return &Refusal{Word: "bad_enum", Offset: 0}
	}
	*v = word
	return nil
}

// MarshalJSON keeps closed vocabularies as JSON strings rather than their
// private numeric implementation tags.
func (v Profile) MarshalJSON() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return esc(nil, word), nil
}

// UnmarshalJSON accepts only an exact JSON string member. Numbers, null and
// unknown strings are refused by the same codec rules as generated records.
func (v *Profile) UnmarshalJSON(data []byte) error {
	r := reader{buf: data}
	r.ws()
	word, err := r.str()
	if err != nil {
		return err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return r.refuse("trailing_bytes")
	}
	parsed, ok := ParseProfile(word)
	if !ok {
		return r.refuse("bad_enum")
	}
	*v = parsed
	return nil
}

// ProfileValues returns every member of Profile in declaration order, in a new slice.
func ProfileValues() []Profile {
	return []Profile{ProfileVideo, ProfileImageBatch}
}

// Known reports whether v is a member of Profile.
func (v Profile) Known() bool {
	_, ok := v.WireName()
	return ok
}

// Mode is a closed vocabulary. Its numeric values are private implementation
// tags; String and ParseMode preserve the exact wire words.
type Mode uint32

const (
	ModeGenerate Mode = 1
	ModeEdit     Mode = 2
)

// String returns v's exact wire word, or the empty string for an invalid value.
func (v Mode) String() string {
	word, _ := v.WireName()
	return word
}

// WireName returns v's exact wire word and whether v names a member.
func (v Mode) WireName() (string, bool) {
	switch v {
	case ModeGenerate:
		return "generate", true
	case ModeEdit:
		return "edit", true
	}
	return "", false
}

// ParseMode returns the member named by an exact wire word.
func ParseMode(word string) (Mode, bool) {
	switch word {
	case "generate":
		return ModeGenerate, true
	case "edit":
		return ModeEdit, true
	}
	return Mode(0), false
}

// MarshalText preserves the member's exact wire word for standard text users,
// including JSON object keys. Invalid and zero values are refused.
func (v Mode) MarshalText() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return []byte(word), nil
}

// UnmarshalText accepts an exact wire word and refuses unknown text.
func (v *Mode) UnmarshalText(text []byte) error {
	word, ok := ParseMode(string(text))
	if !ok {
		return &Refusal{Word: "bad_enum", Offset: 0}
	}
	*v = word
	return nil
}

// MarshalJSON keeps closed vocabularies as JSON strings rather than their
// private numeric implementation tags.
func (v Mode) MarshalJSON() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return esc(nil, word), nil
}

// UnmarshalJSON accepts only an exact JSON string member. Numbers, null and
// unknown strings are refused by the same codec rules as generated records.
func (v *Mode) UnmarshalJSON(data []byte) error {
	r := reader{buf: data}
	r.ws()
	word, err := r.str()
	if err != nil {
		return err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return r.refuse("trailing_bytes")
	}
	parsed, ok := ParseMode(word)
	if !ok {
		return r.refuse("bad_enum")
	}
	*v = parsed
	return nil
}

// ModeValues returns every member of Mode in declaration order, in a new slice.
func ModeValues() []Mode {
	return []Mode{ModeGenerate, ModeEdit}
}

// Known reports whether v is a member of Mode.
func (v Mode) Known() bool {
	_, ok := v.WireName()
	return ok
}

// RequestGuarantee is an open vocabulary: a reader keeps a word it has never heard, so
// a value may be none of the constants below. RequestGuarantee(word) and string(v)
// convert between the raw word and the vocabulary.
type RequestGuarantee string

const (
	RequestGuaranteeLocalOnly     RequestGuarantee = "abstraction.inference/local-only@1"
	RequestGuaranteeHostedAllowed RequestGuarantee = "abstraction.inference/hosted-allowed@1"
)

// RequestGuaranteeValues returns every member of RequestGuarantee in declaration order, in a new slice.
func RequestGuaranteeValues() []RequestGuarantee {
	return []RequestGuarantee{RequestGuaranteeLocalOnly, RequestGuaranteeHostedAllowed}
}

// Known reports whether v is a member of RequestGuarantee.
func (v RequestGuarantee) Known() bool {
	switch v {
	case RequestGuaranteeLocalOnly, RequestGuaranteeHostedAllowed:
		return true
	}
	return false
}

var Kinds = []string{"inference"}

var ExecutionGuarantees = []string{"abstraction.inference/recoverable-upstream@1"}

// The durable image-shaped request. Its fields and bounds match
// abstraction.inference/image@1 ImageRequest. Keeping this job document
// self-contained lets the job SDK persist and reconcile it without importing a
// service transport codec.
type ImageRequest struct {
	Model              string
	Mode               Mode
	Prompt             string
	Size               string
	Count              int64
	ImageDigest        string
	ImageMediaType     string
	MaskDigest         string
	MaskMediaType      string
	Guarantees         []RequestGuarantee
	Credential         string
	RequiredExtensions []string
	Extensions         map[string]string
}

// A typed result reference with the same meaning as
// abstraction.inference/image@1 Delivery.
type Delivery struct {
	Digest    string
	MediaType string
	Size      int64
	Location  string
}

// Durable inference work submitted as job kind inference. video carries an
// image-shaped generate request and duration_ms of 1..600000; image_batch
// carries duration zero and count 1..10. The embedded request retains its
// digest, guarantee, credential and extension bounds. The recoverable-upstream
// guarantee means the executor durably marks submission before the paid call,
// records a returned provider handle, resumes a known handle, and invokes the
// adapter's reconciliation path after an uncertain submit. It does not promise
// eventual resolution: an adapter such as Replicate that offers no lookup by
// caller operation keeps the job waiting as upstream:uncertain and never
// blindly submits it again. No URL, path, header, credential bytes or inline
// media crosses this value.
type Request struct {
	Profile    Profile
	Image      ImageRequest
	DurationMs int64
}

// The immutable successful result returned by the job operation. deliveries are
// ordered typed references committed for the original caller. Local references
// are canonical SHA-256 digests readable through that caller's authorized
// content reader; remote locations state their owning trust domain.
type JobResult struct {
	Profile    Profile
	Deliveries []Delivery
	Host       string
	Model      string
}

// Exactly one of request or result is present. Request documents are opaque job
// submission spec bytes. Result documents are immutable operation result bytes
// read through abstraction.job/operations@1. The job layer does not parse
// either variant.
type Document struct {
	Request *Request
	Result  *JobResult
}

func encImageRequest(out []byte, v *ImageRequest, depth int) []byte {
	if !(v.Mode).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "model")
	out = append(out, ':', ' ')
	out = esc(out, v.Model)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "mode")
	out = append(out, ':', ' ')
	out = esc(out, v.Mode.String())
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "prompt")
	out = append(out, ':', ' ')
	out = esc(out, v.Prompt)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "size")
	out = append(out, ':', ' ')
	out = esc(out, v.Size)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "count")
	out = append(out, ':', ' ')
	out = num(out, v.Count)
	if v.ImageDigest != "" {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "image_digest")
		out = append(out, ':', ' ')
		out = esc(out, v.ImageDigest)
	}
	if v.ImageMediaType != "" {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "image_media_type")
		out = append(out, ':', ' ')
		out = esc(out, v.ImageMediaType)
	}
	if v.MaskDigest != "" {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "mask_digest")
		out = append(out, ':', ' ')
		out = esc(out, v.MaskDigest)
	}
	if v.MaskMediaType != "" {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "mask_media_type")
		out = append(out, ':', ' ')
		out = esc(out, v.MaskMediaType)
	}
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "guarantees")
	out = append(out, ':', ' ')
	out = enumStrs(out, v.Guarantees, depth+1, func(v RequestGuarantee) string { return string(v) })
	if v.Credential != "" {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "credential")
		out = append(out, ':', ' ')
		out = esc(out, v.Credential)
	}
	if len(v.RequiredExtensions) != 0 {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "required_extensions")
		out = append(out, ':', ' ')
		out = strs(out, v.RequiredExtensions, depth+1)
	}
	if len(v.Extensions) != 0 {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "extensions")
		out = append(out, ':', ' ')
		out = strmap(out, v.Extensions, depth+1)
	}
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encDelivery(out []byte, v *Delivery, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "digest")
	out = append(out, ':', ' ')
	out = esc(out, v.Digest)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "media_type")
	out = append(out, ':', ' ')
	out = esc(out, v.MediaType)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "size")
	out = append(out, ':', ' ')
	out = num(out, v.Size)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "location")
	out = append(out, ':', ' ')
	out = esc(out, v.Location)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encRequest(out []byte, v *Request, depth int) []byte {
	if !(v.Profile).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "profile")
	out = append(out, ':', ' ')
	out = esc(out, v.Profile.String())
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "image")
	out = append(out, ':', ' ')
	out = encImageRequest(out, &v.Image, depth+1)
	if v.DurationMs != 0 {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "duration_ms")
		out = append(out, ':', ' ')
		out = num(out, v.DurationMs)
	}
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encJobResult(out []byte, v *JobResult, depth int) []byte {
	if !(v.Profile).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "profile")
	out = append(out, ':', ' ')
	out = esc(out, v.Profile.String())
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "deliveries")
	out = append(out, ':', ' ')
	out = encList(out, v.Deliveries, depth+1, encDelivery)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "host")
	out = append(out, ':', ' ')
	out = esc(out, v.Host)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "model")
	out = append(out, ':', ' ')
	out = esc(out, v.Model)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encDocument(out []byte, v *Document, depth int) []byte {
	out = append(out, '{')
	first := true
	if v.Request != nil {
		first = false
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "request")
		out = append(out, ':', ' ')
		out = encRequest(out, v.Request, depth+1)
	}
	if v.Result != nil {
		if !first {
			out = append(out, ',')
		}
		first = false
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "result")
		out = append(out, ':', ' ')
		out = encJobResult(out, v.Result, depth+1)
	}
	if !first {
		out = append(out, '\n')
		out = pad(out, depth)
	}
	return append(out, '}')
}

func Encode(v *Document) []byte {
	return append(encDocument(nil, v, 0), '\n')
}

type Refusal struct {
	Word   string
	Offset int
}

func (r *Refusal) Error() string {
	return "refused: " + r.Word + " at byte " + decimal(int64(r.Offset))
}

func decimal(n int64) string { return string(num(nil, n)) }

const depthLimit = 64

type reader struct {
	buf   []byte
	pos   int
	depth int
}

func (r *reader) refuse(word string) error { return &Refusal{Word: word, Offset: r.pos} }

func (r *reader) at() byte {
	if r.pos < len(r.buf) {
		return r.buf[r.pos]
	}
	return 0
}

func (r *reader) ws() {
	for r.pos < len(r.buf) {
		switch r.buf[r.pos] {
		case ' ', '\t', '\n', '\r':
			r.pos++
		default:
			return
		}
	}
}

func (r *reader) enter() error {
	r.depth++
	if r.depth > depthLimit {
		return r.refuse("depth_exceeded")
	}
	return nil
}

func (r *reader) str() (string, error) {
	if r.at() != '"' {
		return "", r.refuse("wrong_type")
	}
	r.pos++
	var out []byte
	for {
		if r.pos >= len(r.buf) {
			return "", r.refuse("malformed")
		}
		c := r.buf[r.pos]
		switch {
		case c == '"':
			r.pos++
			if !validUTF8(out) {
				return "", r.refuse("bad_string")
			}
			return string(out), nil
		case c < 0x20:
			return "", r.refuse("bad_string")
		case c == '\\':
			var err error
			if out, err = r.escape(out); err != nil {
				return "", err
			}
		default:
			out = append(out, c)
			r.pos++
		}
	}
}

func (r *reader) escape(out []byte) ([]byte, error) {
	r.pos++
	if r.pos >= len(r.buf) {
		return nil, r.refuse("malformed")
	}
	c := r.buf[r.pos]
	r.pos++
	switch c {
	case '"', '\\', '/':
		return append(out, c), nil
	case 'b':
		return append(out, 0x08), nil
	case 'f':
		return append(out, 0x0c), nil
	case 'n':
		return append(out, '\n'), nil
	case 'r':
		return append(out, '\r'), nil
	case 't':
		return append(out, '\t'), nil
	case 'u':
		u, err := r.hex4()
		if err != nil {
			return nil, err
		}
		if u >= 0xDC00 && u <= 0xDFFF {
			return nil, r.refuse("bad_string")
		}
		if u >= 0xD800 && u <= 0xDBFF {
			if r.pos+1 >= len(r.buf) || r.buf[r.pos] != '\\' || r.buf[r.pos+1] != 'u' {
				return nil, r.refuse("bad_string")
			}
			r.pos += 2
			lo, err := r.hex4()
			if err != nil {
				return nil, err
			}
			if lo < 0xDC00 || lo > 0xDFFF {
				return nil, r.refuse("bad_string")
			}
			u = 0x10000 + (u-0xD800)<<10 + (lo - 0xDC00)
		}
		return appendRune(out, u), nil
	}
	return nil, r.refuse("bad_string")
}

func (r *reader) hex4() (int32, error) {
	if r.pos+4 > len(r.buf) {
		return 0, r.refuse("bad_string")
	}
	var u int32
	for i := 0; i < 4; i++ {
		c := r.buf[r.pos+i]
		switch {
		case c >= '0' && c <= '9':
			u = u<<4 | int32(c-'0')
		case c >= 'a' && c <= 'f':
			u = u<<4 | int32(c-'a'+10)
		case c >= 'A' && c <= 'F':
			u = u<<4 | int32(c-'A'+10)
		default:
			return 0, r.refuse("bad_string")
		}
	}
	r.pos += 4
	return u, nil
}

func appendRune(out []byte, cp int32) []byte {
	switch {
	case cp < 0x80:
		return append(out, byte(cp))
	case cp < 0x800:
		return append(out, byte(0xC0|cp>>6), byte(0x80|cp&0x3F))
	case cp < 0x10000:
		return append(out, byte(0xE0|cp>>12), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
	}
	return append(out, byte(0xF0|cp>>18), byte(0x80|cp>>12&0x3F), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
}

func validUTF8(b []byte) bool {
	for i := 0; i < len(b); {
		c := b[i]
		var n int
		var cp int32
		switch {
		case c < 0x80:
			i++
			continue
		case c>>5 == 0x6:
			n, cp = 2, int32(c&0x1F)
		case c>>4 == 0xE:
			n, cp = 3, int32(c&0x0F)
		case c>>3 == 0x1E:
			n, cp = 4, int32(c&0x07)
		default:
			return false
		}
		if i+n > len(b) {
			return false
		}
		for k := 1; k < n; k++ {
			if b[i+k]>>6 != 0x2 {
				return false
			}
			cp = cp<<6 | int32(b[i+k]&0x3F)
		}
		lowest := []int32{0, 0, 0x80, 0x800, 0x10000}[n]
		if cp < lowest || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF) {
			return false
		}
		i += n
	}
	return true
}

func (r *reader) integer(min, max int64) (int64, error) {
	c := r.at()
	if c != '-' && (c < '0' || c > '9') {
		return 0, r.refuse("wrong_type")
	}
	neg := c == '-'
	if neg {
		r.pos++
	}
	d := r.at()
	if d < '0' || d > '9' {
		return 0, r.refuse("malformed")
	}
	var u uint64
	if d == '0' {
		r.pos++
	} else {
		for d = r.at(); d >= '0' && d <= '9'; d = r.at() {
			if u > 922337203685477580 {
				return 0, r.refuse("number_spelling")
			}
			u = u*10 + uint64(d-'0')
			r.pos++
		}
	}
	switch c := r.at(); {
	case c == '.' || c == 'e' || c == 'E' || (c >= '0' && c <= '9'):
		return 0, r.refuse("number_spelling")
	}
	if neg && u == 0 {
		return 0, r.refuse("number_spelling")
	}
	var n int64
	switch {
	case neg && u == 1<<63:
		n = -1 << 63
	case u > 1<<63-1:
		return 0, r.refuse("number_spelling")
	case neg:
		n = -int64(u)
	default:
		n = int64(u)
	}
	if n < min || n > max {
		return 0, r.refuse("number_spelling")
	}
	return n, nil
}

func (r *reader) boolean() (bool, error) {
	switch r.at() {
	case 't':
		return true, r.literal("true")
	case 'f':
		return false, r.literal("false")
	}
	return false, r.refuse("wrong_type")
}

func (r *reader) literal(word string) error {
	if r.pos+len(word) > len(r.buf) || string(r.buf[r.pos:r.pos+len(word)]) != word {
		return r.refuse("malformed")
	}
	r.pos += len(word)
	return nil
}

func (r *reader) strList() ([]string, error) {
	if r.at() != '[' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := []string{}
	r.ws()
	if r.at() != ']' {
		for {
			r.ws()
			s, err := r.str()
			if err != nil {
				return nil, err
			}
			out = append(out, s)
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != ']' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawMap() (map[string]Raw, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := map[string]Raw{}
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			k, err := r.str()
			if err != nil {
				return nil, err
			}
			if _, again := out[k]; again {
				return nil, r.refuse("duplicate_key")
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			v, err := r.rawValue()
			if err != nil {
				return nil, err
			}
			out[k] = v
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawValue() (Raw, error) {
	start := r.pos
	if err := r.skipValue(); err != nil {
		return "", err
	}
	return Raw(r.buf[start:r.pos]), nil
}

func (r *reader) skipValue() error {
	c := r.at()
	switch {
	case c == '"':
		return r.skipString()
	case c == '{' || c == '[':
		return r.skipContainer()
	case c == 't':
		return r.literal("true")
	case c == 'f':
		return r.literal("false")
	case c == 'n':
		return r.literal("null")
	case c == '-' || (c >= '0' && c <= '9'):
		return r.skipNumber()
	}
	return r.refuse("malformed")
}

// An opaque value is validated and carried, never interpreted. Its syntax is
// the record's own — the same string reader, so an escape, a control byte or a
// lone surrogate is judged identically at any depth — and what it is free to
// spell, it keeps: the bytes between these two offsets are what a writer
// re-emits. A number is walked, never converted, so a value no host type holds
// survives the reader that carried it.
func (r *reader) skipString() error {
	_, err := r.str()
	return err
}

func (r *reader) skipNumber() error {
	if r.at() == '-' {
		r.pos++
	}
	switch c := r.at(); {
	case c == '0':
		r.pos++
	case c >= '1' && c <= '9':
		for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
			r.pos++
		}
	default:
		return r.refuse("number_spelling")
	}
	if r.at() == '.' {
		r.pos++
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	if c := r.at(); c == 'e' || c == 'E' {
		r.pos++
		if c := r.at(); c == '+' || c == '-' {
			r.pos++
		}
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	return nil
}

func (r *reader) someDigits() error {
	n := 0
	for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
		r.pos++
		n++
	}
	if n == 0 {
		return r.refuse("number_spelling")
	}
	return nil
}

func (r *reader) skipContainer() error {
	open := r.buf[r.pos]
	shut := byte('}')
	if open == '[' {
		shut = ']'
	}
	if err := r.enter(); err != nil {
		return err
	}
	r.pos++
	r.ws()
	seen := map[string]bool{}
	if r.at() != shut {
		for {
			r.ws()
			if open == '{' {
				if r.at() != '"' {
					return r.refuse("malformed")
				}
				k, err := r.str()
				if err != nil {
					return err
				}
				if seen[k] {
					return r.refuse("duplicate_key")
				}
				seen[k] = true
				r.ws()
				if r.at() != ':' {
					return r.refuse("malformed")
				}
				r.pos++
				r.ws()
			}
			if err := r.skipValue(); err != nil {
				return err
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != shut {
		return r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return nil
}

func (r *reader) strMap() (map[string]string, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := map[string]string{}
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			k, err := r.str()
			if err != nil {
				return nil, err
			}
			if _, again := out[k]; again {
				return nil, r.refuse("duplicate_key")
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			v, err := r.str()
			if err != nil {
				return nil, err
			}
			out[k] = v
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func decodeList[T any](r *reader, elem func(*reader) (*T, error)) ([]T, error) {
	if r.at() != '[' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := []T{}
	r.ws()
	if r.at() != ']' {
		for {
			r.ws()
			v, err := elem(r)
			if err != nil {
				return nil, err
			}
			out = append(out, *v)
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != ']' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) decodeImageRequest() (*ImageRequest, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &ImageRequest{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "model":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Model = x
			case "mode":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseMode(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Mode = word
			case "prompt":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Prompt = x
			case "size":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Size = x
			case "count":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.Count = x
			case "image_digest":
				if seen&32 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 32
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.ImageDigest = x
			case "image_media_type":
				if seen&64 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 64
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.ImageMediaType = x
			case "mask_digest":
				if seen&128 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 128
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.MaskDigest = x
			case "mask_media_type":
				if seen&256 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 256
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.MaskMediaType = x
			case "guarantees":
				if seen&512 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 512
				x, err := r.strList()
				if err != nil {
					return nil, err
				}
				words := make([]RequestGuarantee, len(x))
				for i, raw := range x {
					words[i] = RequestGuarantee(raw)
				}
				v.Guarantees = words
			case "credential":
				if seen&1024 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1024
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Credential = x
			case "required_extensions":
				if seen&2048 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2048
				x, err := r.strList()
				if err != nil {
					return nil, err
				}
				v.RequiredExtensions = x
			case "extensions":
				if seen&4096 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4096
				x, err := r.strMap()
				if err != nil {
					return nil, err
				}
				v.Extensions = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&543 != 543 {
		return nil, r.refuse("missing_field")
	}
	if !(v.Mode).Known() {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeDelivery() (*Delivery, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &Delivery{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "digest":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Digest = x
			case "media_type":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.MediaType = x
			case "size":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.Size = x
			case "location":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Location = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeRequest() (*Request, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &Request{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "profile":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseProfile(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Profile = word
			case "image":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.decodeImageRequest()
				if err != nil {
					return nil, err
				}
				v.Image = *x
			case "duration_ms":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.DurationMs = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	if !(v.Profile).Known() {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeJobResult() (*JobResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &JobResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "profile":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseProfile(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Profile = word
			case "deliveries":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := decodeList(r, (*reader).decodeDelivery)
				if err != nil {
					return nil, err
				}
				v.Deliveries = x
			case "host":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Host = x
			case "model":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Model = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	if !(v.Profile).Known() {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeDocument() (*Document, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &Document{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "request":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeRequest()
				if err != nil {
					return nil, err
				}
				v.Request = x
			case "result":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.decodeJobResult()
				if err != nil {
					return nil, err
				}
				v.Result = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return v, nil
}

func Decode(in []byte) (*Document, error) {
	r := &reader{buf: in}
	r.ws()
	v, err := r.decodeDocument()
	if err != nil {
		return nil, err
	}
	r.ws()
	if r.pos < len(r.buf) {
		return nil, r.refuse("trailing_bytes")
	}
	return v, nil
}

// refusals is in the order two of them are chosen between.

var refusals = []string{"malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"}

func refusalRank(word string) int {
	for i, w := range refusals {
		if w == word {
			return i
		}
	}
	return -1
}
