// Code generated by abstraction-idl from abstraction-inference/job.thrift. DO NOT EDIT.

#pragma once

#include <cstddef>
#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace abstraction::inference::job {

using Raw = std::string;

class Refusal : public std::runtime_error {
public:
    Refusal(const char* word, std::size_t offset)
        : std::runtime_error(std::string("refused: ") + word + " at byte " + std::to_string(offset)),
          word(word),
          offset(offset) {}
    const char* word;
    std::size_t offset;
};

enum class Profile : std::int32_t {
    Video = 1,
    ImageBatch = 2,
};

// The member's name on the wire; empty for a value that names no member.
inline constexpr std::string_view wire_name(Profile value) {
    switch (value) {
        case Profile::Video: return "video";
        case Profile::ImageBatch: return "image_batch";
    }
    return {};
}

// The member a wire name spells; empty for a name this vocabulary refuses.
inline std::optional<Profile> parse_profile(std::string_view name) {
    if (name == "video") return Profile::Video;
    if (name == "image_batch") return Profile::ImageBatch;
    return std::nullopt;
}

// A member equals its wire name, so code holding the contract's word compares directly.
inline constexpr bool operator==(Profile value, std::string_view name) { return wire_name(value) == name; }
inline constexpr bool operator!=(Profile value, std::string_view name) { return wire_name(value) != name; }
inline constexpr bool operator==(std::string_view name, Profile value) { return wire_name(value) == name; }
inline constexpr bool operator!=(std::string_view name, Profile value) { return wire_name(value) != name; }

inline const std::vector<std::string> kProfileNames = {"video", "image_batch"};

enum class Mode : std::int32_t {
    Generate = 1,
    Edit = 2,
};

// The member's name on the wire; empty for a value that names no member.
inline constexpr std::string_view wire_name(Mode value) {
    switch (value) {
        case Mode::Generate: return "generate";
        case Mode::Edit: return "edit";
    }
    return {};
}

// The member a wire name spells; empty for a name this vocabulary refuses.
inline std::optional<Mode> parse_mode(std::string_view name) {
    if (name == "generate") return Mode::Generate;
    if (name == "edit") return Mode::Edit;
    return std::nullopt;
}

// A member equals its wire name, so code holding the contract's word compares directly.
inline constexpr bool operator==(Mode value, std::string_view name) { return wire_name(value) == name; }
inline constexpr bool operator!=(Mode value, std::string_view name) { return wire_name(value) != name; }
inline constexpr bool operator==(std::string_view name, Mode value) { return wire_name(value) == name; }
inline constexpr bool operator!=(std::string_view name, Mode value) { return wire_name(value) != name; }

inline const std::vector<std::string> kModeNames = {"generate", "edit"};

inline const std::vector<std::string> kRequestGuaranteeNames = {"abstraction.inference/local-only@1", "abstraction.inference/hosted-allowed@1"};
inline constexpr std::string_view kRequestGuaranteeLocalOnly = "abstraction.inference/local-only@1";
inline constexpr std::string_view kRequestGuaranteeHostedAllowed = "abstraction.inference/hosted-allowed@1";

inline const std::vector<std::string> kKinds = {"inference"};

inline const std::vector<std::string> kExecutionGuarantees = {"abstraction.inference/recoverable-upstream@1"};

// The durable image-shaped request. Its fields and bounds match
// abstraction.inference/image@1 ImageRequest. Keeping this job document
// self-contained lets the job SDK persist and reconcile it without importing a
// service transport codec.
struct ImageRequest {
    std::string model;
    Mode mode{};
    std::string prompt;
    std::string size;
    std::int64_t count = 0;
    std::string image_digest;
    std::string image_media_type;
    std::string mask_digest;
    std::string mask_media_type;
    std::vector<std::string> guarantees;
    std::string credential;
    std::vector<std::string> required_extensions;
    std::map<std::string, std::string> extensions;
};

// A typed result reference with the same meaning as
// abstraction.inference/image@1 Delivery.
struct Delivery {
    std::string digest;
    std::string media_type;
    std::int64_t size = 0;
    std::string location;
};

// Durable inference work submitted as job kind inference. video carries an
// image-shaped generate request and duration_ms of 1..600000; image_batch
// carries duration zero and count 1..10. The embedded request retains its
// digest, guarantee, credential and extension bounds. The recoverable-upstream
// guarantee means the executor durably marks submission before the paid call,
// records a returned provider handle, resumes a known handle, and invokes the
// adapter's reconciliation path after an uncertain submit. It does not promise
// eventual resolution: an adapter such as Replicate that offers no lookup by
// caller operation keeps the job waiting as upstream:uncertain and never
// blindly submits it again. No URL, path, header, credential bytes or inline
// media crosses this value.
struct Request {
    Profile profile{};
    ImageRequest image;
    std::int64_t duration_ms = 0;
};

// The immutable successful result returned by the job operation. deliveries are
// ordered typed references committed for the original caller. Local references
// are canonical SHA-256 digests readable through that caller's authorized
// content reader; remote locations state their owning trust domain.
struct JobResult {
    Profile profile{};
    std::vector<Delivery> deliveries;
    std::string host;
    std::string model;
};

// Exactly one of request or result is present. Request documents are opaque job
// submission spec bytes. Result documents are immutable operation result bytes
// read through abstraction.job/operations@1. The job layer does not parse
// either variant.
struct Document {
    std::optional<Request> request;
    std::optional<JobResult> result;
};

// Codec machinery. Nothing here is API; it may change in any release.
namespace detail {

inline void esc(std::string& out, const std::string& s);

inline void esc_byte(std::string& out, unsigned char c) {
    static const char* kHex = "0123456789abcdef";
    switch (c) {
        case '"': out += "\\\""; return;
        case '\\': out += "\\\\"; return;
        case 0x08: out += "\\b"; return;
        case 0x0c: out += "\\f"; return;
        case '\n': out += "\\n"; return;
        case '\r': out += "\\r"; return;
        case '\t': out += "\\t"; return;
        default: break;
    }
    if (c < 0x20) {
        out += "\\u00";
        out += kHex[c >> 4];
        out += kHex[c & 0x0F];
    } else {
        out += static_cast<char>(c);
    }
}

inline void num(std::string& out, std::int64_t n) { out += std::to_string(n); }

inline void pad(std::string& out, int depth) {
    out.append(static_cast<std::size_t>(depth) * 2, ' ');
}

inline void strs(std::string& out, const std::vector<std::string>& v, int depth) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        esc(out, v[i]);
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}

template <typename E>
inline void enum_strs(std::string& out, const std::vector<E>& v, int depth) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        esc(out, std::string(wire_name(v[i])));
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}


inline bool ws(unsigned char c) { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }

inline void raw(std::string& out, const std::string& s, int depth) {
    const std::size_t n = s.size();
    for (std::size_t i = 0; i < n;) {
        const unsigned char c = static_cast<unsigned char>(s[i]);
        if (ws(c)) {
            ++i;
        } else if (c == '"') {
            std::size_t j = i + 1;
            while (j < n) {
                if (s[j] == '\\') { j += 2; continue; }
                if (s[j] == '"') { ++j; break; }
                ++j;
            }
            out.append(s, i, j - i);
            i = j;
        } else if (c == '{' || c == '[') {
            out += static_cast<char>(c);
            ++i;
            std::size_t j = i;
            while (j < n && ws(static_cast<unsigned char>(s[j]))) ++j;
            if (j < n && (s[j] == '}' || s[j] == ']')) {
                out += s[j];
                i = j + 1;
            } else {
                ++depth;
                out += '\n';
                pad(out, depth);
            }
        } else if (c == '}' || c == ']') {
            --depth;
            out += '\n';
            pad(out, depth);
            out += static_cast<char>(c);
            ++i;
        } else if (c == ',') {
            out += ",\n";
            pad(out, depth);
            ++i;
        } else if (c == ':') {
            out += ": ";
            ++i;
        } else {
            out += static_cast<char>(c);
            ++i;
        }
    }
}

// std::char_traits<char>::compare is specified to order by unsigned char, so a
// std::map<std::string, ...> already walks its keys in UTF-8 byte order — which
// is what the definition declares. Nothing sorts here because nothing needs to.
inline void rawmap(std::string& out, const std::map<std::string, Raw>& m, int depth) {
    if (m.empty()) { out += "{}"; return; }
    out += "{\n";
    std::size_t i = 0;
    for (const auto& kv : m) {
        pad(out, depth + 1);
        esc(out, kv.first);
        out += ": ";
        raw(out, kv.second, depth + 1);
        if (++i < m.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += '}';
}

inline void esc(std::string& out, const std::string& s) {
    out += '"';
    for (unsigned char c : s) esc_byte(out, c);
    out += '"';
}

inline void strmap(std::string& out, const std::map<std::string, std::string>& m, int depth) {
    if (m.empty()) { out += "{}"; return; }
    out += "{\n";
    std::size_t i = 0;
    for (const auto& kv : m) {
        pad(out, depth + 1);
        esc(out, kv.first);
        out += ": ";
        esc(out, kv.second);
        if (++i < m.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += '}';
}

template <typename T>
inline void enc_list(std::string& out, const std::vector<T>& v, int depth,
                     void (*enc)(std::string&, const T&, int)) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        enc(out, v[i], depth + 1);
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}
inline void enc_image_request(std::string&, const ImageRequest&, int);
inline void enc_delivery(std::string&, const Delivery&, int);
inline void enc_request(std::string&, const Request&, int);
inline void enc_job_result(std::string&, const JobResult&, int);
inline void enc_document(std::string&, const Document&, int);

inline void enc_image_request(std::string& out, const ImageRequest& v, int depth) {
    if (wire_name(v.mode).empty()) throw Refusal("bad_enum", 0);
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "model");
    out += ": ";
    esc(out, v.model);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "mode");
    out += ": ";
    esc(out, std::string(wire_name(v.mode)));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "prompt");
    out += ": ";
    esc(out, v.prompt);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "size");
    out += ": ";
    esc(out, v.size);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "count");
    out += ": ";
    num(out, v.count);
    if (!v.image_digest.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "image_digest");
        out += ": ";
        esc(out, v.image_digest);
    }
    if (!v.image_media_type.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "image_media_type");
        out += ": ";
        esc(out, v.image_media_type);
    }
    if (!v.mask_digest.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "mask_digest");
        out += ": ";
        esc(out, v.mask_digest);
    }
    if (!v.mask_media_type.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "mask_media_type");
        out += ": ";
        esc(out, v.mask_media_type);
    }
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "guarantees");
    out += ": ";
    strs(out, v.guarantees, depth + 1);
    if (!v.credential.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "credential");
        out += ": ";
        esc(out, v.credential);
    }
    if (!v.required_extensions.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "required_extensions");
        out += ": ";
        strs(out, v.required_extensions, depth + 1);
    }
    if (!v.extensions.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "extensions");
        out += ": ";
        strmap(out, v.extensions, depth + 1);
    }
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_delivery(std::string& out, const Delivery& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "digest");
    out += ": ";
    esc(out, v.digest);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "media_type");
    out += ": ";
    esc(out, v.media_type);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "size");
    out += ": ";
    num(out, v.size);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "location");
    out += ": ";
    esc(out, v.location);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_request(std::string& out, const Request& v, int depth) {
    if (wire_name(v.profile).empty()) throw Refusal("bad_enum", 0);
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "profile");
    out += ": ";
    esc(out, std::string(wire_name(v.profile)));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "image");
    out += ": ";
    enc_image_request(out, v.image, depth + 1);
    if (v.duration_ms != 0) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "duration_ms");
        out += ": ";
        num(out, v.duration_ms);
    }
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_job_result(std::string& out, const JobResult& v, int depth) {
    if (wire_name(v.profile).empty()) throw Refusal("bad_enum", 0);
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "profile");
    out += ": ";
    esc(out, std::string(wire_name(v.profile)));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "deliveries");
    out += ": ";
    enc_list<Delivery>(out, v.deliveries, depth + 1, enc_delivery);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "host");
    out += ": ";
    esc(out, v.host);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "model");
    out += ": ";
    esc(out, v.model);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_document(std::string& out, const Document& v, int depth) {
    out += '{';
    bool first = true;
    if (v.request.has_value()) {
        first = false;
        out += '\n';
        pad(out, depth + 1);
        esc(out, "request");
        out += ": ";
        enc_request(out, *v.request, depth + 1);
    }
    if (v.result.has_value()) {
        if (!first) out += ',';
        first = false;
        out += '\n';
        pad(out, depth + 1);
        esc(out, "result");
        out += ": ";
        enc_job_result(out, *v.result, depth + 1);
    }
    if (!first) { out += '\n'; pad(out, depth); }
    out += '}';
}

inline constexpr int kDepthLimit = 64;
inline constexpr std::size_t kI64Digits = 19;

inline void append_rune(std::string& out, std::uint32_t cp) {
    if (cp < 0x80) {
        out += static_cast<char>(cp);
    } else if (cp < 0x800) {
        out += static_cast<char>(0xC0 | (cp >> 6));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else if (cp < 0x10000) {
        out += static_cast<char>(0xE0 | (cp >> 12));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else {
        out += static_cast<char>(0xF0 | (cp >> 18));
        out += static_cast<char>(0x80 | ((cp >> 12) & 0x3F));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    }
}

inline bool valid_utf8(const std::string& b) {
    for (std::size_t i = 0; i < b.size();) {
        const unsigned char c = static_cast<unsigned char>(b[i]);
        if (c < 0x80) { ++i; continue; }
        std::size_t n = 0;
        std::uint32_t cp = 0;
        if ((c >> 5) == 0x6) { n = 2; cp = c & 0x1Fu; }
        else if ((c >> 4) == 0xE) { n = 3; cp = c & 0x0Fu; }
        else if ((c >> 3) == 0x1E) { n = 4; cp = c & 0x07u; }
        else return false;
        if (i + n > b.size()) return false;
        for (std::size_t k = 1; k < n; ++k) {
            const unsigned char t = static_cast<unsigned char>(b[i + k]);
            if ((t >> 6) != 0x2) return false;
            cp = cp << 6 | (t & 0x3Fu);
        }
        static const std::uint32_t kLowest[5] = {0, 0, 0x80, 0x800, 0x10000};
        if (cp < kLowest[n] || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) return false;
        i += n;
    }
    return true;
}

struct Reader {
    std::string_view buf;
    std::size_t pos = 0;
    int depth = 0;

    [[noreturn]] void refuse(const char* word) const { throw Refusal(word, pos); }

    unsigned char at() const {
        return pos < buf.size() ? static_cast<unsigned char>(buf[pos]) : 0;
    }

    bool digit() const { return at() >= '0' && at() <= '9'; }

    void skip_ws() {
        while (pos < buf.size() && ws(static_cast<unsigned char>(buf[pos]))) ++pos;
    }

    void enter() {
        if (++depth > kDepthLimit) refuse("depth_exceeded");
    }

    std::string str() {
        if (at() != '"') refuse("wrong_type");
        ++pos;
        std::string out;
        for (;;) {
            if (pos >= buf.size()) refuse("malformed");
            const unsigned char c = static_cast<unsigned char>(buf[pos]);
            if (c == '"') {
                ++pos;
                if (!valid_utf8(out)) refuse("bad_string");
                return out;
            }
            if (c < 0x20) refuse("bad_string");
            if (c == '\\') {
                escape(out);
            } else {
                out += static_cast<char>(c);
                ++pos;
            }
        }
    }

    void escape(std::string& out) {
        ++pos;
        if (pos >= buf.size()) refuse("malformed");
        const unsigned char c = static_cast<unsigned char>(buf[pos]);
        ++pos;
        switch (c) {
            case '"': case '\\': case '/': out += static_cast<char>(c); return;
            case 'b': out += static_cast<char>(0x08); return;
            case 'f': out += static_cast<char>(0x0c); return;
            case 'n': out += '\n'; return;
            case 'r': out += '\r'; return;
            case 't': out += '\t'; return;
            case 'u': break;
            default: refuse("bad_string");
        }
        std::uint32_t u = hex4();
        if (u >= 0xDC00 && u <= 0xDFFF) refuse("bad_string");
        if (u >= 0xD800 && u <= 0xDBFF) {
            if (pos + 1 >= buf.size() || buf[pos] != '\\' || buf[pos + 1] != 'u') refuse("bad_string");
            pos += 2;
            const std::uint32_t low = hex4();
            if (low < 0xDC00 || low > 0xDFFF) refuse("bad_string");
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
        }
        append_rune(out, u);
    }

    std::uint32_t hex4() {
        if (pos + 4 > buf.size()) refuse("bad_string");
        std::uint32_t u = 0;
        for (std::size_t i = 0; i < 4; ++i) {
            const unsigned char c = static_cast<unsigned char>(buf[pos + i]);
            if (c >= '0' && c <= '9') u = u << 4 | static_cast<std::uint32_t>(c - '0');
            else if (c >= 'a' && c <= 'f') u = u << 4 | static_cast<std::uint32_t>(c - 'a' + 10);
            else if (c >= 'A' && c <= 'F') u = u << 4 | static_cast<std::uint32_t>(c - 'A' + 10);
            else refuse("bad_string");
        }
        pos += 4;
        return u;
    }

    std::int64_t integer(std::int64_t low, std::int64_t high) {
        const unsigned char c = at();
        if (c != '-' && !digit()) refuse("wrong_type");
        const bool negative = c == '-';
        if (negative) ++pos;
        if (!digit()) refuse("malformed");
        std::uint64_t u = 0;
        if (at() == '0') {
            ++pos;
        } else {
            while (digit()) {
                if (u > 922337203685477580ULL) refuse("number_spelling");
                u = u * 10 + static_cast<std::uint64_t>(at() - '0');
                ++pos;
            }
        }
        const unsigned char after = at();
        if (after == '.' || after == 'e' || after == 'E' || digit()) refuse("number_spelling");
        if (negative && u == 0) refuse("number_spelling");
        std::int64_t n = 0;
        if (negative) {
            if (u > (1ULL << 63)) refuse("number_spelling");
            n = u == (1ULL << 63) ? INT64_MIN : -static_cast<std::int64_t>(u);
        } else {
            if (u > static_cast<std::uint64_t>(INT64_MAX)) refuse("number_spelling");
            n = static_cast<std::int64_t>(u);
        }
        if (n < low || n > high) refuse("number_spelling");
        return n;
    }

    bool boolean() {
        if (at() == 't') { literal("true"); return true; }
        if (at() == 'f') { literal("false"); return false; }
        refuse("wrong_type");
    }

    void literal(std::string_view word) {
        if (buf.substr(pos, word.size()) != word) refuse("malformed");
        pos += word.size();
    }

    std::vector<std::string> str_list() {
        if (at() != '[') refuse("wrong_type");
        enter();
        ++pos;
        std::vector<std::string> out;
        skip_ws();
        if (at() != ']') {
            for (;;) {
                skip_ws();
                out.push_back(str());
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != ']') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    std::map<std::string, Raw> raw_map() {
        if (at() != '{') refuse("wrong_type");
        enter();
        ++pos;
        std::map<std::string, Raw> out;
        skip_ws();
        if (at() != '}') {
            for (;;) {
                skip_ws();
                if (at() != '"') refuse("malformed");
                const std::string k = str();
                if (out.count(k) != 0) refuse("duplicate_key");
                skip_ws();
                if (at() != ':') refuse("malformed");
                ++pos;
                skip_ws();
                out[k] = raw_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != '}') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    Raw raw_value() {
        const std::size_t start = pos;
        skip_value();
        return std::string(buf.substr(start, pos - start));
    }

    void skip_value() {
        const unsigned char c = at();
        if (c == '"') skip_string();
        else if (c == '{' || c == '[') skip_container();
        else if (c == 't') literal("true");
        else if (c == 'f') literal("false");
        else if (c == 'n') literal("null");
        else if (c == '-' || digit()) skip_number();
        else refuse("malformed");
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    void skip_string() { str(); }

    void some_digits() {
        int n = 0;
        while (digit()) { ++pos; ++n; }
        if (n == 0) refuse("number_spelling");
    }

    void skip_number() {
        if (at() == '-') ++pos;
        const unsigned char c = at();
        if (c == '0') ++pos;
        else if (c >= '1' && c <= '9') { while (digit()) ++pos; }
        else refuse("number_spelling");
        if (at() == '.') { ++pos; some_digits(); }
        if (at() == 'e' || at() == 'E') {
            ++pos;
            if (at() == '+' || at() == '-') ++pos;
            some_digits();
        }
    }

    void skip_container() {
        const unsigned char opener = at();
        const char shut = opener == '{' ? '}' : ']';
        enter();
        ++pos;
        skip_ws();
        std::map<std::string, bool> seen;
        if (at() != static_cast<unsigned char>(shut)) {
            for (;;) {
                skip_ws();
                if (opener == '{') {
                    if (at() != '"') refuse("malformed");
                    const std::string k = str();
                    if (!seen.emplace(k, true).second) refuse("duplicate_key");
                    skip_ws();
                    if (at() != ':') refuse("malformed");
                    ++pos;
                    skip_ws();
                }
                skip_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != static_cast<unsigned char>(shut)) refuse("malformed");
        ++pos;
        --depth;
    }
};

inline std::map<std::string, std::string> str_map(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    std::map<std::string, std::string> out;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string k = r.str();
            if (out.count(k) != 0) r.refuse("duplicate_key");
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            out[k] = r.str();
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    return out;
}

template <typename T>
inline std::vector<T> decode_list(Reader& r, T (*elem)(Reader&)) {
    if (r.at() != '[') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    std::vector<T> out;
    r.skip_ws();
    if (r.at() != ']') {
        for (;;) {
            r.skip_ws();
            out.push_back(elem(r));
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != ']') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    return out;
}

inline ImageRequest decode_image_request(Reader& r);
inline Delivery decode_delivery(Reader& r);
inline Request decode_request(Reader& r);
inline JobResult decode_job_result(Reader& r);
inline Document decode_document(Reader& r);

inline ImageRequest decode_image_request(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    ImageRequest v;
    std::optional<std::string> wire_mode;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "model") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.model = r.str();
            } else if (key == "mode") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                wire_mode = r.str();
            } else if (key == "prompt") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.prompt = r.str();
            } else if (key == "size") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.size = r.str();
            } else if (key == "count") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.count = r.integer(INT64_MIN, INT64_MAX);
            } else if (key == "image_digest") {
                if (seen & 32u) r.refuse("duplicate_field");
                seen |= 32u;
                v.image_digest = r.str();
            } else if (key == "image_media_type") {
                if (seen & 64u) r.refuse("duplicate_field");
                seen |= 64u;
                v.image_media_type = r.str();
            } else if (key == "mask_digest") {
                if (seen & 128u) r.refuse("duplicate_field");
                seen |= 128u;
                v.mask_digest = r.str();
            } else if (key == "mask_media_type") {
                if (seen & 256u) r.refuse("duplicate_field");
                seen |= 256u;
                v.mask_media_type = r.str();
            } else if (key == "guarantees") {
                if (seen & 512u) r.refuse("duplicate_field");
                seen |= 512u;
                v.guarantees = r.str_list();
            } else if (key == "credential") {
                if (seen & 1024u) r.refuse("duplicate_field");
                seen |= 1024u;
                v.credential = r.str();
            } else if (key == "required_extensions") {
                if (seen & 2048u) r.refuse("duplicate_field");
                seen |= 2048u;
                v.required_extensions = r.str_list();
            } else if (key == "extensions") {
                if (seen & 4096u) r.refuse("duplicate_field");
                seen |= 4096u;
                v.extensions = str_map(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 543u) != 543u) r.refuse("missing_field");
    if (wire_mode) {
        const auto parsed = parse_mode(*wire_mode);
        if (!parsed) r.refuse("bad_enum");
        v.mode = *parsed;
    }
    return v;
}

inline Delivery decode_delivery(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Delivery v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "digest") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.digest = r.str();
            } else if (key == "media_type") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.media_type = r.str();
            } else if (key == "size") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.size = r.integer(INT64_MIN, INT64_MAX);
            } else if (key == "location") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.location = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    return v;
}

inline Request decode_request(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Request v;
    std::optional<std::string> wire_profile;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "profile") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                wire_profile = r.str();
            } else if (key == "image") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.image = decode_image_request(r);
            } else if (key == "duration_ms") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.duration_ms = r.integer(INT64_MIN, INT64_MAX);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    if (wire_profile) {
        const auto parsed = parse_profile(*wire_profile);
        if (!parsed) r.refuse("bad_enum");
        v.profile = *parsed;
    }
    return v;
}

inline JobResult decode_job_result(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    JobResult v;
    std::optional<std::string> wire_profile;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "profile") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                wire_profile = r.str();
            } else if (key == "deliveries") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.deliveries = decode_list<Delivery>(r, decode_delivery);
            } else if (key == "host") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.host = r.str();
            } else if (key == "model") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.model = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    if (wire_profile) {
        const auto parsed = parse_profile(*wire_profile);
        if (!parsed) r.refuse("bad_enum");
        v.profile = *parsed;
    }
    return v;
}

inline Document decode_document(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Document v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "request") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.request = decode_request(r);
            } else if (key == "result") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.result = decode_job_result(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    return v;
}

}  // namespace detail

inline std::string encode(const Document& v) {
    std::string out;
    detail::enc_document(out, v, 0);
    out += '\n';
    return out;
}

inline Document decode(std::string_view data) {
    detail::Reader r{data};
    r.skip_ws();
    Document v = detail::decode_document(r);
    r.skip_ws();
    if (r.pos < r.buf.size()) r.refuse("trailing_bytes");
    return v;
}

namespace detail {
// kRefusals is in the order two of them are chosen between.
inline const std::vector<std::string> kRefusals = {"malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"};

inline int refusal_rank(std::string_view word) {
    for (std::size_t i = 0; i < kRefusals.size(); ++i)
        if (kRefusals[i] == word) return static_cast<int>(i);
    return -1;
}
}  // namespace detail

}  // namespace abstraction::inference::job
