// Code generated by abstraction-idl from abstraction-inference/job.thrift. DO NOT EDIT.

// abstraction.inference.job: declarations for index.mjs.

// A typed result reference with the same meaning as
// abstraction.inference/image@1 Delivery.
export interface Delivery {
  digest: string;
  mediaType: string;
  size: bigint;
  location: string;
}

// Exactly one of request or result is present. Request documents are opaque job
// submission spec bytes. Result documents are immutable operation result bytes
// read through abstraction.job/operation@1. The job layer does not parse either
// variant.
export interface Document {
  request: Request | null;
  result: JobResult | null;
}

// The durable image-shaped request. Its fields and bounds match
// abstraction.inference/image@1 ImageRequest. Keeping this job document
// self-contained lets the job SDK persist and reconcile it without importing a
// service transport codec.
export interface ImageRequest {
  model: string;
  mode: Mode;
  prompt: string;
  size: string;
  count: bigint;
  imageDigest: string;
  imageMediaType: string;
  maskDigest: string;
  maskMediaType: string;
  guarantees: Array<RequestGuarantee | (string & {})>;
  credential: string;
  requiredExtensions: string[];
  extensions: { [key: string]: string };
}

// The immutable successful result returned by the job operation. deliveries are
// ordered typed references committed for the original caller. Local references
// are canonical SHA-256 digests readable through that caller's authorized
// content reader; remote locations state their owning trust domain.
export interface JobResult {
  profile: Profile;
  deliveries: Delivery[];
  host: string;
  model: string;
}

export type Mode = (typeof Mode)[keyof typeof Mode];
export declare const Mode: Readonly<{ Generate: "generate"; Edit: "edit" }>;

export type Profile = (typeof Profile)[keyof typeof Profile];
export declare const Profile: Readonly<{ Video: "video"; ImageBatch: "image_batch" }>;

export declare class Refusal extends Error {
  constructor(word: string, offset: number);
  word: "malformed" | "bad_string" | "number_spelling" | "wrong_type" | "depth_exceeded" | "duplicate_key" | "duplicate_field" | "unknown_field" | "missing_field" | "bad_enum" | "trailing_bytes";
  offset: number;
}

// Durable inference work submitted as job kind inference. video carries an
// image-shaped generate request and duration_ms of 1..600000; image_batch
// carries duration zero and count 1..10. The embedded request retains its
// digest, guarantee, credential and extension bounds. The recoverable-upstream
// guarantee means the executor durably marks submission before the paid call,
// records a returned provider handle, resumes a known handle, and invokes the
// adapter's reconciliation path after an uncertain submit. It does not promise
// eventual resolution: an adapter such as Replicate that offers no lookup by
// caller operation keeps the job waiting as upstream:uncertain and never
// blindly submits it again. No URL, path, header, credential bytes or inline
// media crosses this value.
export interface Request {
  profile: Profile;
  image: ImageRequest;
  durationMs: bigint;
}

export type RequestGuarantee = (typeof RequestGuarantee)[keyof typeof RequestGuarantee];
export declare const RequestGuarantee: Readonly<{ LocalOnly: "abstraction.inference/local-only@1"; HostedAllowed: "abstraction.inference/hosted-allowed@1" }>;

export declare function decode(data: Uint8Array): Document;

export declare function encode(v: Document): Uint8Array;

export declare const executionGuarantees: readonly ["abstraction.inference/recoverable-upstream@1"];

export declare const kinds: readonly ["inference"];

export declare function newDelivery(): Delivery;

export declare function newDocument(): Document;

export declare function newImageRequest(): ImageRequest;

export declare function newJobResult(): JobResult;

export declare function newRequest(): Request;

export {};
