// Code generated by abstraction-idl from abstraction-inference/job.thrift. DO NOT EDIT.

const HEX = "0123456789abcdef";
const ENC = new TextEncoder();
const SHORT = { 0x22: '\\"', 0x5c: "\\\\", 0x08: "\\b", 0x0c: "\\f", 0x0a: "\\n", 0x0d: "\\r", 0x09: "\\t" };

class Out {
  constructor() { this.b = []; }
  byte(c) { this.b.push(c); }
  ascii(s) { for (let i = 0; i < s.length; i++) this.b.push(s.charCodeAt(i)); }
  bytes() { return Uint8Array.from(this.b); }
}

function escByte(out, c) {
  const short = SHORT[c];
  if (short !== undefined) out.ascii(short);
  else if (c < 0x20) out.ascii("\\u00" + HEX[c >> 4] + HEX[c & 0xf]);
  else out.byte(c);
}

// Every integer the definition calls i64 is a BigInt here, because Number
// rounds above 2^53 and two values in the conformance record are i64 extremes.
function num(out, n) { out.ascii(BigInt(n).toString()); }

function pad(out, depth) { for (let i = 0; i < depth * 2; i++) out.byte(0x20); }

function strs(out, v, depth) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    esc(out, v[i]);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

const isWs = (c) => c === 0x20 || c === 0x09 || c === 0x0a || c === 0x0d;

function raw(out, s, depth) {
  const b = typeof s === "string" ? ENC.encode(s) : s;
  let i = 0;
  while (i < b.length) {
    const c = b[i];
    if (isWs(c)) { i++; continue; }
    if (c === 0x22) {
      let j = i + 1;
      while (j < b.length) {
        if (b[j] === 0x5c) { j += 2; continue; }
        if (b[j] === 0x22) { j++; break; }
        j++;
      }
      for (let k = i; k < j; k++) out.byte(b[k]);
      i = j;
    } else if (c === 0x7b || c === 0x5b) {
      out.byte(c);
      i++;
      let j = i;
      while (j < b.length && isWs(b[j])) j++;
      if (j < b.length && (b[j] === 0x7d || b[j] === 0x5d)) { out.byte(b[j]); i = j + 1; }
      else { depth++; out.byte(0x0a); pad(out, depth); }
    } else if (c === 0x7d || c === 0x5d) {
      depth--;
      out.byte(0x0a);
      pad(out, depth);
      out.byte(c);
      i++;
    } else if (c === 0x2c) {
      out.ascii(",\n");
      pad(out, depth);
      i++;
    } else if (c === 0x3a) {
      out.ascii(": ");
      i++;
    } else {
      out.byte(c);
      i++;
    }
  }
}

// A JavaScript string sorts by UTF-16 code unit, which puts U+1D11E before
// U+FFFD where every other target puts it after. The definition declares UTF-8
// byte order, so the comparison is done on the encoded bytes.
function byteLess(a, b) {
  const x = ENC.encode(a), y = ENC.encode(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return x.length - y.length;
}

function rawmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    raw(out, m[keys[i]], depth + 1);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

function esc(out, s) {
  out.byte(0x22);
  for (const c of ENC.encode(s)) escByte(out, c);
  out.byte(0x22);
}

function strmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    esc(out, m[keys[i]]);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

function writeList(out, v, depth, enc) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    enc(out, v[i], depth + 1);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

export const Profile = Object.freeze({
  Video: "video",
  ImageBatch: "image_batch",
});

export const Mode = Object.freeze({
  Generate: "generate",
  Edit: "edit",
});

export const RequestGuarantee = Object.freeze({
  LocalOnly: "abstraction.inference/local-only@1",
  HostedAllowed: "abstraction.inference/hosted-allowed@1",
});

export const kinds = ["inference"];

export const executionGuarantees = ["abstraction.inference/recoverable-upstream@1"];

function writeImageRequest(out, v, depth) {
    if (typeof v.mode !== "string") throw new Refusal("wrong_type",0);
    if (v.mode !== "generate" && v.mode !== "edit") { throw new Refusal("bad_enum",0); }
    for (const item of v.guarantees) {
        if (typeof item !== "string") throw new Refusal("wrong_type",0);
    }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "model");
  out.ascii(": ");
  esc(out, v.model);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "mode");
  out.ascii(": ");
  esc(out, v.mode);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "prompt");
  out.ascii(": ");
  esc(out, v.prompt);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "size");
  out.ascii(": ");
  esc(out, v.size);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "count");
  out.ascii(": ");
  num(out, v.count);
  if (v.imageDigest !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "image_digest");
    out.ascii(": ");
    esc(out, v.imageDigest);
  }
  if (v.imageMediaType !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "image_media_type");
    out.ascii(": ");
    esc(out, v.imageMediaType);
  }
  if (v.maskDigest !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "mask_digest");
    out.ascii(": ");
    esc(out, v.maskDigest);
  }
  if (v.maskMediaType !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "mask_media_type");
    out.ascii(": ");
    esc(out, v.maskMediaType);
  }
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "guarantees");
  out.ascii(": ");
  strs(out, v.guarantees, depth + 1);
  if (v.credential !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "credential");
    out.ascii(": ");
    esc(out, v.credential);
  }
  if (v.requiredExtensions.length !== 0) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "required_extensions");
    out.ascii(": ");
    strs(out, v.requiredExtensions, depth + 1);
  }
  if (Object.keys(v.extensions).length !== 0) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "extensions");
    out.ascii(": ");
    strmap(out, v.extensions, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeDelivery(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "digest");
  out.ascii(": ");
  esc(out, v.digest);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "media_type");
  out.ascii(": ");
  esc(out, v.mediaType);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "size");
  out.ascii(": ");
  num(out, v.size);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "location");
  out.ascii(": ");
  esc(out, v.location);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeRequest(out, v, depth) {
    if (typeof v.profile !== "string") throw new Refusal("wrong_type",0);
    if (v.profile !== "video" && v.profile !== "image_batch") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "profile");
  out.ascii(": ");
  esc(out, v.profile);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "image");
  out.ascii(": ");
  writeImageRequest(out, v.image, depth + 1);
  if (v.durationMs !== 0n) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "duration_ms");
    out.ascii(": ");
    num(out, v.durationMs);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeJobResult(out, v, depth) {
    if (typeof v.profile !== "string") throw new Refusal("wrong_type",0);
    if (v.profile !== "video" && v.profile !== "image_batch") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "profile");
  out.ascii(": ");
  esc(out, v.profile);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "deliveries");
  out.ascii(": ");
  writeList(out, v.deliveries, depth + 1, writeDelivery);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "host");
  out.ascii(": ");
  esc(out, v.host);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "model");
  out.ascii(": ");
  esc(out, v.model);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeDocument(out, v, depth) {
  out.byte(0x7b);
  let first = true;
  if (v.request !== undefined && v.request !== null) {
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "request");
    out.ascii(": ");
    writeRequest(out, v.request, depth + 1);
  }
  if (v.result !== undefined && v.result !== null) {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "result");
    out.ascii(": ");
    writeJobResult(out, v.result, depth + 1);
  }
  if (!first) { out.byte(0x0a); pad(out, depth); }
  out.byte(0x7d);
}

export function encode(v) {
  const out = new Out();
  writeDocument(out, v, 0);
  out.byte(0x0a);
  return out.bytes();
}

// A BOM inside a JSON string is data, not a stream signature.
const DEC = new TextDecoder("utf-8", {ignoreBOM: true});
const DEPTH_LIMIT = 64;
const I64_DIGITS = 19;
const UNESCAPE = { 0x22: 0x22, 0x5c: 0x5c, 0x2f: 0x2f, 0x62: 0x08, 0x66: 0x0c, 0x6e: 0x0a, 0x72: 0x0d, 0x74: 0x09 };

export class Refusal extends Error {
  constructor(word, offset) {
    super("refused: " + word + " at byte " + offset);
    this.name = "Refusal";
    this.word = word;
    this.offset = offset;
  }
}

function appendRune(out, cp) {
  if (cp < 0x80) out.push(cp);
  else if (cp < 0x800) out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
  else if (cp < 0x10000) out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
  else out.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 0x3f), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
}

// TextDecoder substitutes U+FFFD for a bad sequence rather than reporting it, so
// the bytes are checked before they are decoded and the refusal says so.
function validUtf8(b) {
  for (let i = 0; i < b.length; ) {
    const c = b[i];
    if (c < 0x80) { i++; continue; }
    let n, cp;
    if (c >> 5 === 0x6) { n = 2; cp = c & 0x1f; }
    else if (c >> 4 === 0xe) { n = 3; cp = c & 0x0f; }
    else if (c >> 3 === 0x1e) { n = 4; cp = c & 0x07; }
    else return false;
    if (i + n > b.length) return false;
    for (let k = 1; k < n; k++) {
      if (b[i + k] >> 6 !== 0x2) return false;
      cp = (cp << 6) | (b[i + k] & 0x3f);
    }
    const lowest = [0, 0, 0x80, 0x800, 0x10000][n];
    if (cp < lowest || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return false;
    i += n;
  }
  return true;
}

class Reader {
  constructor(buf) { this.buf = buf; this.pos = 0; this.depth = 0; }

  refuse(word) { return new Refusal(word, this.pos); }

  at() { return this.pos < this.buf.length ? this.buf[this.pos] : 0; }

  digit() { const c = this.at(); return c >= 0x30 && c <= 0x39; }

  ws() { while (this.pos < this.buf.length && isWs(this.buf[this.pos])) this.pos++; }

  enter() {
    this.depth++;
    if (this.depth > DEPTH_LIMIT) throw this.refuse("depth_exceeded");
  }

  string() {
    if (this.at() !== 0x22) throw this.refuse("wrong_type");
    this.pos++;
    const out = [];
    for (;;) {
      if (this.pos >= this.buf.length) throw this.refuse("malformed");
      const c = this.buf[this.pos];
      if (c === 0x22) {
        this.pos++;
        const bytes = Uint8Array.from(out);
        if (!validUtf8(bytes)) throw this.refuse("bad_string");
        return DEC.decode(bytes);
      }
      if (c < 0x20) throw this.refuse("bad_string");
      if (c === 0x5c) this.escape(out);
      else { out.push(c); this.pos++; }
    }
  }

  escape(out) {
    this.pos++;
    if (this.pos >= this.buf.length) throw this.refuse("malformed");
    const c = this.buf[this.pos];
    this.pos++;
    const plain = UNESCAPE[c];
    if (plain !== undefined) { out.push(plain); return; }
    if (c !== 0x75) throw this.refuse("bad_string");
    let u = this.hex4();
    if (u >= 0xdc00 && u <= 0xdfff) throw this.refuse("bad_string");
    if (u >= 0xd800 && u <= 0xdbff) {
      if (this.pos + 1 >= this.buf.length || this.buf[this.pos] !== 0x5c || this.buf[this.pos + 1] !== 0x75)
        throw this.refuse("bad_string");
      this.pos += 2;
      const low = this.hex4();
      if (low < 0xdc00 || low > 0xdfff) throw this.refuse("bad_string");
      u = 0x10000 + ((u - 0xd800) << 10) + (low - 0xdc00);
    }
    appendRune(out, u);
  }

  hex4() {
    if (this.pos + 4 > this.buf.length) throw this.refuse("bad_string");
    let u = 0;
    for (let i = 0; i < 4; i++) {
      const c = this.buf[this.pos + i];
      if (c >= 0x30 && c <= 0x39) u = (u << 4) | (c - 0x30);
      else if (c >= 0x61 && c <= 0x66) u = (u << 4) | (c - 0x61 + 10);
      else if (c >= 0x41 && c <= 0x46) u = (u << 4) | (c - 0x41 + 10);
      else throw this.refuse("bad_string");
    }
    this.pos += 4;
    return u;
  }

  integer(low, high) {
    const c = this.at();
    if (c !== 0x2d && (c < 0x30 || c > 0x39)) throw this.refuse("wrong_type");
    const negative = c === 0x2d;
    if (negative) this.pos++;
    if (!this.digit()) throw this.refuse("malformed");
    const start = this.pos;
    if (this.at() === 0x30) this.pos++;
    else while (this.digit()) this.pos++;
    const after = this.at();
    if (after === 0x2e || after === 0x65 || after === 0x45 || this.digit()) throw this.refuse("number_spelling");
    if (this.pos - start > I64_DIGITS) throw this.refuse("number_spelling");
    let n = BigInt(String.fromCharCode(...this.buf.subarray(start, this.pos)));
    if (negative) {
      if (n === 0n) throw this.refuse("number_spelling");
      n = -n;
    }
    if (n < low || n > high) throw this.refuse("number_spelling");
    return n;
  }

  boolean() {
    if (this.at() === 0x74) { this.literal("true"); return true; }
    if (this.at() === 0x66) { this.literal("false"); return false; }
    throw this.refuse("wrong_type");
  }

  literal(word) {
    for (let i = 0; i < word.length; i++)
      if (this.buf[this.pos + i] !== word.charCodeAt(i)) throw this.refuse("malformed");
    this.pos += word.length;
  }

  strList() {
    if (this.at() !== 0x5b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = [];
    this.ws();
    if (this.at() !== 0x5d) {
      for (;;) {
        this.ws();
        out.push(this.string());
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x5d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawMap() {
    if (this.at() !== 0x7b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = Object.create(null);
    this.ws();
    if (this.at() !== 0x7d) {
      for (;;) {
        this.ws();
        if (this.at() !== 0x22) throw this.refuse("malformed");
        const k = this.string();
        if (k in out) throw this.refuse("duplicate_key");
        this.ws();
        if (this.at() !== 0x3a) throw this.refuse("malformed");
        this.pos++;
        this.ws();
        out[k] = this.rawValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x7d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawValue() {
    const start = this.pos;
    this.skipValue();
    return this.buf.subarray(start, this.pos);
  }

  skipValue() {
    const c = this.at();
    if (c === 0x22) this.skipString();
    else if (c === 0x7b || c === 0x5b) this.skipContainer();
    else if (c === 0x74) this.literal("true");
    else if (c === 0x66) this.literal("false");
    else if (c === 0x6e) this.literal("null");
    else if (c === 0x2d || (c >= 0x30 && c <= 0x39)) this.skipNumber();
    else throw this.refuse("malformed");
  }

  // An opaque value is validated and carried, never interpreted. Its syntax is
  // the record's own — the same string reader, so an escape, a control byte or a
  // lone surrogate is judged identically at any depth — and what it is free to
  // spell, it keeps: the bytes between these two offsets are what a writer
  // re-emits. A number is walked, never converted, so a value no host type holds
  // survives the reader that carried it.
  skipString() {
    this.string();
  }

  someDigits() {
    let n = 0;
    while (this.at() >= 0x30 && this.at() <= 0x39) { this.pos++; n++; }
    if (n === 0) throw this.refuse("number_spelling");
  }

  skipNumber() {
    if (this.at() === 0x2d) this.pos++;
    const c = this.at();
    if (c === 0x30) this.pos++;
    else if (c > 0x30 && c <= 0x39) { while (this.at() >= 0x30 && this.at() <= 0x39) this.pos++; }
    else throw this.refuse("number_spelling");
    if (this.at() === 0x2e) { this.pos++; this.someDigits(); }
    if (this.at() === 0x65 || this.at() === 0x45) {
      this.pos++;
      if (this.at() === 0x2b || this.at() === 0x2d) this.pos++;
      this.someDigits();
    }
  }

  skipContainer() {
    const opener = this.at();
    const shut = opener === 0x7b ? 0x7d : 0x5d;
    this.enter();
    this.pos++;
    this.ws();
    const seen = new Set();
    if (this.at() !== shut) {
      for (;;) {
        this.ws();
        if (opener === 0x7b) {
          if (this.at() !== 0x22) throw this.refuse("malformed");
          const k = this.string();
          if (seen.has(k)) throw this.refuse("duplicate_key");
          seen.add(k);
          this.ws();
          if (this.at() !== 0x3a) throw this.refuse("malformed");
          this.pos++;
          this.ws();
        }
        this.skipValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== shut) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
  }
}

function strMap(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = Object.create(null);
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const k = r.string();
      if (k in out) throw r.refuse("duplicate_key");
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      out[k] = r.string();
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

function readList(r, elem) {
  if (r.at() !== 0x5b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = [];
  r.ws();
  if (r.at() !== 0x5d) {
    for (;;) {
      r.ws();
      out.push(elem(r));
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x5d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

// The durable image-shaped request. Its fields and bounds match
// abstraction.inference/image@1 ImageRequest. Keeping this job document
// self-contained lets the job SDK persist and reconcile it without importing a
// service transport codec.
export function newImageRequest() {
  return { model: "", mode: "", prompt: "", size: "", count: 0n, imageDigest: "", imageMediaType: "", maskDigest: "", maskMediaType: "", guarantees: [], credential: "", requiredExtensions: [], extensions: {} };
}

// A typed result reference with the same meaning as
// abstraction.inference/image@1 Delivery.
export function newDelivery() {
  return { digest: "", mediaType: "", size: 0n, location: "" };
}

// Durable inference work submitted as job kind inference. video carries an
// image-shaped generate request and duration_ms of 1..600000; image_batch
// carries duration zero and count 1..10. The embedded request retains its
// digest, guarantee, credential and extension bounds. The recoverable-upstream
// guarantee means the executor durably marks submission before the paid call,
// records a returned provider handle, resumes a known handle, and invokes the
// adapter's reconciliation path after an uncertain submit. It does not promise
// eventual resolution: an adapter such as Replicate that offers no lookup by
// caller operation keeps the job waiting as upstream:uncertain and never
// blindly submits it again. No URL, path, header, credential bytes or inline
// media crosses this value.
export function newRequest() {
  return { profile: "", image: newImageRequest(), durationMs: 0n };
}

// The immutable successful result returned by the job operation. deliveries are
// ordered typed references committed for the original caller. Local references
// are canonical SHA-256 digests readable through that caller's authorized
// content reader; remote locations state their owning trust domain.
export function newJobResult() {
  return { profile: "", deliveries: [], host: "", model: "" };
}

// Exactly one of request or result is present. Request documents are opaque job
// submission spec bytes. Result documents are immutable operation result bytes
// read through abstraction.job/operations@1. The job layer does not parse
// either variant.
export function newDocument() {
  return { request: null, result: null };
}

function readImageRequest(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newImageRequest();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "model") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.model = r.string();
      } else if (key === "mode") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.mode = r.string();
      } else if (key === "prompt") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.prompt = r.string();
      } else if (key === "size") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.size = r.string();
      } else if (key === "count") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.count = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "image_digest") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.imageDigest = r.string();
      } else if (key === "image_media_type") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.imageMediaType = r.string();
      } else if (key === "mask_digest") {
        if (seen & 128) throw r.refuse("duplicate_field");
        seen |= 128;
        v.maskDigest = r.string();
      } else if (key === "mask_media_type") {
        if (seen & 256) throw r.refuse("duplicate_field");
        seen |= 256;
        v.maskMediaType = r.string();
      } else if (key === "guarantees") {
        if (seen & 512) throw r.refuse("duplicate_field");
        seen |= 512;
        v.guarantees = r.strList();
      } else if (key === "credential") {
        if (seen & 1024) throw r.refuse("duplicate_field");
        seen |= 1024;
        v.credential = r.string();
      } else if (key === "required_extensions") {
        if (seen & 2048) throw r.refuse("duplicate_field");
        seen |= 2048;
        v.requiredExtensions = r.strList();
      } else if (key === "extensions") {
        if (seen & 4096) throw r.refuse("duplicate_field");
        seen |= 4096;
        v.extensions = strMap(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 543) >>> 0) !== 543) throw r.refuse("missing_field");
    if (v.mode !== "generate" && v.mode !== "edit") { throw r.refuse("bad_enum"); }
  return v;
}

function readDelivery(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newDelivery();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "digest") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.digest = r.string();
      } else if (key === "media_type") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.mediaType = r.string();
      } else if (key === "size") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.size = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "location") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.location = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function readRequest(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newRequest();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "profile") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.profile = r.string();
      } else if (key === "image") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.image = readImageRequest(r);
      } else if (key === "duration_ms") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.durationMs = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
    if (v.profile !== "video" && v.profile !== "image_batch") { throw r.refuse("bad_enum"); }
  return v;
}

function readJobResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newJobResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "profile") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.profile = r.string();
      } else if (key === "deliveries") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.deliveries = readList(r, readDelivery);
      } else if (key === "host") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.host = r.string();
      } else if (key === "model") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.model = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
    if (v.profile !== "video" && v.profile !== "image_batch") { throw r.refuse("bad_enum"); }
  return v;
}

function readDocument(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newDocument();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "request") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.request = readRequest(r);
      } else if (key === "result") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.result = readJobResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return v;
}

export function decode(data) {
  const r = new Reader(data);
  r.ws();
  const v = readDocument(r);
  r.ws();
  if (r.pos < r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

// refusals is in the order two of them are chosen between.
const refusals = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"];

function refusalRank(word) {
  return refusals.indexOf(word);
}
