package inference

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"math"
	"net/http"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	wire "github.com/openabstractions/abstraction-inference/go/abstraction/inference/api"
	router "github.com/openabstractions/abstraction-router/go"
)

const ImageContract = "abstraction.inference/image@1"

type localImageDeliveryContextKey struct{}

// WithLocalImageDelivery requires StartImage to choose a host whose completed
// delivery can be read from this service's content store. Compatibility
// gateways use this when their response format contains the generated bytes.
func WithLocalImageDelivery(ctx context.Context) context.Context {
	return context.WithValue(ctx, localImageDeliveryContextKey{}, true)
}

func localImageDeliveryRequired(ctx context.Context) bool {
	required, _ := ctx.Value(localImageDeliveryContextKey{}).(bool)
	return required
}

type resolvedImageInput struct {
	data      []byte
	mediaType string
}

type generatedImage struct {
	data      []byte
	mediaType string
}

type imageBackendReply struct {
	outcome wire.ReplyOutcome
	reason  string
	images  []generatedImage
	usage   wire.Usage
	cost    *wire.Cost
}

func validateImageRequest(req wire.ImageRequest) string {
	if req.Model == "" || len(req.Model) > 256 || !utf8.ValidString(req.Model) {
		return "model"
	}
	if !req.Mode.Known() {
		return "mode"
	}
	if req.Prompt == "" || len(req.Prompt) > 32768 || !utf8.ValidString(req.Prompt) {
		return "prompt"
	}
	if _, _, ok := imageDimensions(req.Size); !ok {
		return "size"
	}
	if req.Count < 1 || req.Count > 10 {
		return "count"
	}
	if req.Mode == wire.ImageModeGenerate {
		if req.ImageDigest != "" || req.ImageMediaType != "" || req.MaskDigest != "" || req.MaskMediaType != "" {
			return "mode"
		}
	} else {
		if !canonicalSHA256(req.ImageDigest) || !generatedInputMedia(req.ImageMediaType) {
			return "image"
		}
		if (req.MaskDigest == "") != (req.MaskMediaType == "") || req.MaskDigest != "" && (!canonicalSHA256(req.MaskDigest) || req.MaskMediaType != "image/png") {
			return "mask"
		}
	}
	for key := range req.Extensions {
		owner, name, ok := strings.Cut(key, "/")
		if !ok || owner == "" || name == "" || len(key) > 128 || len(req.Extensions[key]) > 32768 {
			return "extensions"
		}
	}
	for _, key := range req.RequiredExtensions {
		if _, ok := req.Extensions[key]; !ok {
			return "extensions"
		}
	}
	local, hosted := false, false
	for _, guarantee := range req.Guarantees {
		switch guarantee {
		case wire.RequestGuaranteeLocalOnly:
			local = true
		case wire.RequestGuaranteeHostedAllowed:
			hosted = true
		default:
			return "guarantees"
		}
	}
	if local && hosted {
		return "guarantees"
	}
	if req.Credential != "" && (len(req.Credential) > 64 || !nameChars(req.Credential, "_-.")) {
		return "credential"
	}
	return ""
}

func imageDimensions(size string) (int, int, bool) {
	if size == "auto" {
		return 0, 0, true
	}
	w, h, ok := strings.Cut(size, "x")
	if !ok || w == "" || h == "" || strings.HasPrefix(w, "0") || strings.HasPrefix(h, "0") {
		return 0, 0, false
	}
	width, errW := strconv.Atoi(w)
	height, errH := strconv.Atoi(h)
	if errW != nil || errH != nil || width < 64 || height < 64 || width > 4096 || height > 4096 || width%8 != 0 || height%8 != 0 {
		return 0, 0, false
	}
	return width, height, true
}

func generatedInputMedia(media string) bool {
	return media == "image/png" || media == "image/jpeg" || media == "image/webp"
}

func imageAdapterFor(host *router.Host) string {
	switch {
	case host.Wire == router.WireRemote:
		return "remote"
	case host.Name == "comfyui":
		return "comfyui"
	case host.Name == "swarmui":
		return "swarmui"
	case host.Wire == router.WireStabilityV2Beta:
		return "stability"
	case host.Wire == router.WireFalQueue:
		return "fal"
	case host.Wire == router.WireReplicatePredictions:
		return "replicate"
	case host.Wire == "" || host.Wire == router.WireOpenAICompatible:
		return "openai"
	}
	return ""
}

func unsupportedImage(kind string, host *router.Host, req wire.ImageRequest) string {
	known := map[string]bool{}
	switch kind {
	case "comfyui":
		known = map[string]bool{"comfyui/steps": true, "comfyui/cfg": true, "comfyui/sampler": true, "comfyui/negative-prompt": true}
	case "swarmui":
		known = map[string]bool{"swarmui/negative-prompt": true}
	case "replicate":
		known = map[string]bool{"replicate/version": true}
	}
	for _, key := range req.RequiredExtensions {
		if !known[key] {
			return "extension:" + key
		}
	}
	switch kind {
	case "openai":
		if host.Name != "lemonade" && req.Size != "auto" {
			supported := map[string]bool{"256x256": true, "512x512": true, "1024x1024": true, "1536x1024": true, "1024x1536": true, "1792x1024": true, "1024x1792": true}
			if !supported[req.Size] {
				return "size:" + req.Size
			}
		}
	case "stability":
		if req.Count != 1 || req.Size != "auto" || req.Mode == wire.ImageModeEdit && req.MaskDigest == "" {
			return "image:request"
		}
	case "fal", "replicate", "comfyui", "swarmui":
		if req.Mode != wire.ImageModeGenerate {
			return "mode:edit"
		}
	case "remote":
	default:
		return "wire"
	}
	return ""
}

func (p *Provider) resolveImageInput(ctx context.Context, subject Subject, digest, media string) (resolvedImageInput, wire.StartOutcome, string) {
	if p.cfg.ResolveContent == nil {
		return resolvedImageInput{}, wire.StartOutcomeUnavailable, "content:unavailable"
	}
	data, outcome := p.cfg.ResolveContent(ctx, subject, digest, p.cfg.MaxImageBytes)
	if ctx.Err() != nil {
		return resolvedImageInput{}, wire.StartOutcomeUnavailable, "content:unavailable"
	}
	switch outcome {
	case ContentResolved:
	case ContentUnknown:
		return resolvedImageInput{}, wire.StartOutcomeInvalid, "content:unknown"
	case ContentForbidden:
		return resolvedImageInput{}, wire.StartOutcomeForbidden, "content:forbidden"
	case ContentTooLarge:
		return resolvedImageInput{}, wire.StartOutcomeInvalid, "content:too-large"
	default:
		return resolvedImageInput{}, wire.StartOutcomeUnavailable, "content:unavailable"
	}
	if int64(len(data)) > p.cfg.MaxImageBytes {
		return resolvedImageInput{}, wire.StartOutcomeInvalid, "content:too-large"
	}
	sum := sha256.Sum256(data)
	if digest != "sha256:"+hex.EncodeToString(sum[:]) {
		return resolvedImageInput{}, wire.StartOutcomeInvalid, "content:digest"
	}
	if http.DetectContentType(data) != media {
		return resolvedImageInput{}, wire.StartOutcomeInvalid, "content:media-type"
	}
	return resolvedImageInput{data: append([]byte(nil), data...), mediaType: media}, 0, ""
}

func (p *Provider) StartImage(ctx context.Context, subject Subject, req wire.ImageRequest) wire.Admission {
	started, via := p.cfg.Now(), routeOf(ctx)
	if via.name == RouteRemote {
		via.claim = req.Extensions[ClaimExtension]
	}
	refuse := func(outcome wire.StartOutcome, reason string, host *router.Host, model string) wire.Admission {
		record := Record{Profile: router.ProfileImage, Route: via.name, Rung: via.rung, Account: subject.Account, Program: subject.Program, Model: req.Model,
			Family: familyOf(req.Model), Credential: req.Credential, Outcome: outcome.String(), Reason: reason, WallMS: p.cfg.Now().Sub(started).Milliseconds(), Domain: via.domain, Claim: via.claim}
		if host != nil {
			record.Host, record.Model = host.Name, model
			if host.Wire == router.WireRemote {
				record.Domain = host.Domain
			}
		}
		if p.cfg.Ceilings != nil && req.Credential != "" {
			record.Ceiling = p.cfg.Ceilings.State(req.Credential)
		}
		p.record(record)
		return refusal(outcome, reason)
	}
	if subject.Account == "" || subject.Program == "" {
		return refuse(wire.StartOutcomeForbidden, "caller", nil, "")
	}
	if reason := validateImageRequest(req); reason != "" {
		return refuse(wire.StartOutcomeInvalid, reason, nil, "")
	}
	host, model, reason := p.pick(ctx, req.Model, requestGuaranteeWords(req.Guarantees), req.Credential, router.ProfileImage)
	if host == nil {
		return refuse(wire.StartOutcomeNoHost, reason, nil, "")
	}
	if host.Wire == router.WireRemote && localImageDeliveryRequired(ctx) {
		return refuse(wire.StartOutcomeUnsupportedFeature, "delivery:remote", host, model)
	}
	kind := imageAdapterFor(host)
	if kind == "" || host.ImageURL() == "" {
		return refuse(wire.StartOutcomeUnsupportedFeature, "wire:"+host.Wire, host, model)
	}
	if reason := unsupportedImage(kind, host, req); reason != "" {
		return refuse(wire.StartOutcomeUnsupportedFeature, reason, host, model)
	}
	word, err := p.cfg.Decide(ctx, subject, ActionComplete, ResourceHost(host.Name))
	if err != nil || ctx.Err() != nil {
		p.report(err)
		return refuse(wire.StartOutcomeUnavailable, "rights:unavailable", host, model)
	}
	switch word {
	case "permitted":
	case "denied", "not_granted", "unknown_action":
		return refuse(wire.StartOutcomeNotPermitted, "rights:"+word, host, model)
	default:
		return refuse(wire.StartOutcomeUnavailable, "rights:unavailable", host, model)
	}
	remote := host.Wire == router.WireRemote
	inputs := map[string]resolvedImageInput{}
	if !remote && req.Mode == wire.ImageModeEdit {
		input, outcome, why := p.resolveImageInput(ctx, subject, req.ImageDigest, req.ImageMediaType)
		if why != "" {
			return refuse(outcome, why, host, model)
		}
		inputs[req.ImageDigest] = input
		if req.MaskDigest != "" {
			mask, outcome, why := p.resolveImageInput(ctx, subject, req.MaskDigest, req.MaskMediaType)
			if why != "" {
				return refuse(outcome, why, host, model)
			}
			inputs[req.MaskDigest] = mask
		}
	}
	var commits []ContentCommitter
	if !remote {
		if p.cfg.PrepareContentWrite == nil {
			return refuse(wire.StartOutcomeUnavailable, "output:unavailable", host, model)
		}
		for i := int64(0); i < req.Count; i++ {
			commit, outcome := p.cfg.PrepareContentWrite(ctx, subject, "image", "image/*", p.cfg.MaxGeneratedImageBytes)
			switch outcome {
			case ContentResolved:
			case ContentForbidden:
				return refuse(wire.StartOutcomeForbidden, "output:forbidden", host, model)
			default:
				return refuse(wire.StartOutcomeUnavailable, "output:unavailable", host, model)
			}
			if commit == nil {
				return refuse(wire.StartOutcomeUnavailable, "output:unavailable", host, model)
			}
			commits = append(commits, commit)
		}
	}
	credential := ""
	if host.Hosted {
		credential = host.Credential
	}
	if credential != "" && p.cfg.Ceilings != nil && !remote {
		if unit, over := p.cfg.Ceilings.Exceeded(credential); over {
			return refuse(wire.StartOutcomeBudgetExceeded, "ceiling:"+unit+":"+credential, host, model)
		}
	}
	if p.active(subject) >= p.cfg.MaxOperations {
		return refuse(wire.StartOutcomeExhausted, "capacity", host, model)
	}
	var headers map[string]string
	if credential != "" && !remote {
		headers, word = p.cfg.Apply(ctx, subject, ImageContract, credential, router.Target(host.Base))
		switch word {
		case "applied":
		case "unavailable", "":
			return refuse(wire.StartOutcomeUnavailable, "credential:unavailable:"+credential, host, model)
		default:
			return refuse(wire.StartOutcomeNotPermitted, "credential:"+word+":"+credential, host, model)
		}
	}
	id, err := operationID()
	if err != nil {
		clear(headers)
		return refuse(wire.StartOutcomeUnavailable, "capacity", host, model)
	}
	op := newOperation(id, subject, host, model, credential, p.cfg.RetainedDeltas, started)
	op.profile, op.route, op.remote = router.ProfileImage, via, remote
	runCtx, cancel := context.WithCancel(p.ctx)
	op.cancel = cancel
	if outcome := p.admitOperation(op); outcome != wire.StartOutcomeAccepted {
		cancel()
		clear(headers)
		reason = "capacity"
		if outcome == wire.StartOutcomeUnavailable {
			reason = "provider:closed"
		}
		return refuse(outcome, reason, host, model)
	}
	go p.runImage(runCtx, op, kind, req, inputs, commits, headers)
	admission := wire.Admission{Outcome: wire.StartOutcomeAccepted, Operation: id, Host: host.Name, Model: model}
	p.bounds(&admission)
	return admission
}

func (p *Provider) ObserveImage(ctx context.Context, subject Subject, id string, cursor, maxDeltas, maxBytes, waitMS int64) wire.DeltaPage {
	return p.observeProfile(ctx, subject, id, router.ProfileImage, cursor, maxDeltas, maxBytes, waitMS)
}

func (p *Provider) CancelImage(subject Subject, id string) wire.Cancellation {
	return p.cancelProfile(subject, id, router.ProfileImage)
}

func (p *Provider) runImage(ctx context.Context, op *operation, kind string, req wire.ImageRequest, inputs map[string]resolvedImageInput, commits []ContentCommitter, headers map[string]string) {
	defer p.runs.Done()
	defer close(op.finished)
	defer op.cancel()
	emitProgress := func(percent int64, message string) {
		if percent < 0 || percent > 100 || len(message) > 4096 || !utf8.ValidString(message) {
			return
		}
		op.emit(wire.Delta{Kind: wire.DeltaKindImageProgress, ImageProgress: &wire.ImageProgress{Percent: percent, Message: message}}, p.cfg.Now())
	}
	var end wire.ImageReply
	if kind == "remote" {
		end = p.runRemoteImage(ctx, op, req)
	} else {
		bounds := imageOutputBounds{each: p.cfg.MaxGeneratedImageBytes, total: p.cfg.MaxImageOutputBytes}
		backend := runImageBackend(ctx, p.cfg.HTTP, op.host, op.model, kind, req, inputs, headers, bounds, emitProgress)
		if backend.outcome == wire.ReplyOutcomeCompleted {
			emitProgress(100, "completed")
		}
		end = p.publishImages(ctx, op, req, backend, commits)
	}
	clear(headers)
	if reason := op.stopped(); reason != "" {
		end.Outcome, end.Reason = wire.ReplyOutcomeCancelled, reason
	} else if p.ctx.Err() != nil || ctx.Err() != nil && end.Outcome == wire.ReplyOutcomeUnavailable {
		end.Outcome, end.Reason = wire.ReplyOutcomeCancelled, "caller"
	}
	end.Host, end.Model = op.host.Name, op.model
	if op.credential != "" && p.cfg.Ceilings != nil && !op.remote {
		var micros int64
		if end.Cost != nil {
			micros = end.Cost.Micros
		}
		if err := p.cfg.Ceilings.AddModalities(op.credential, end.Usage.Input+end.Usage.Output, micros, end.Images, 0, 0); err != nil {
			p.report(err)
		}
	}
	now := p.cfg.Now()
	op.emit(wire.Delta{Kind: wire.DeltaKindEnd, ImageEnd: &end}, now)
	record := Record{Operation: op.id, Profile: router.ProfileImage, Route: op.route.name, Rung: op.route.rung, Account: op.subject.Account, Program: op.subject.Program,
		Host: op.host.Name, Model: op.model, Family: familyOf(op.model), Credential: op.credential, Outcome: end.Outcome.String(), Reason: end.Reason,
		TokensIn: end.Usage.Input, TokensOut: end.Usage.Output, Images: end.Images, WallMS: now.Sub(op.started).Milliseconds(), Domain: op.route.domain, Claim: op.route.claim}
	if op.remote {
		record.Domain = op.host.Domain
	}
	if op.credential != "" && p.cfg.Ceilings != nil && !op.remote {
		record.Ceiling = p.cfg.Ceilings.State(op.credential)
	}
	p.record(record)
}

func (p *Provider) publishImages(ctx context.Context, op *operation, req wire.ImageRequest, backend imageBackendReply, commits []ContentCommitter) wire.ImageReply {
	end := wire.ImageReply{Outcome: backend.outcome, Reason: backend.reason, Usage: backend.usage, Cost: backend.cost, Deliveries: []wire.Delivery{}, Images: int64(len(backend.images))}
	if backend.outcome != wire.ReplyOutcomeCompleted {
		return end
	}
	if int64(len(backend.images)) != req.Count || len(commits) != len(backend.images) {
		return wire.ImageReply{Outcome: wire.ReplyOutcomeUnavailable, Reason: "upstream:count", Images: int64(len(backend.images)), Usage: backend.usage, Cost: backend.cost, Deliveries: []wire.Delivery{}}
	}
	var total int64
	for _, output := range backend.images {
		if !generatedInputMedia(output.mediaType) || len(output.data) == 0 || int64(len(output.data)) > p.cfg.MaxGeneratedImageBytes || int64(len(output.data)) > p.cfg.MaxImageOutputBytes-total || http.DetectContentType(output.data) != output.mediaType {
			return wire.ImageReply{Outcome: wire.ReplyOutcomeUnavailable, Reason: "upstream:image", Images: int64(len(backend.images)), Usage: backend.usage, Cost: backend.cost, Deliveries: []wire.Delivery{}}
		}
		total += int64(len(output.data))
	}
	if !op.beginCompletion() {
		return wire.ImageReply{Outcome: wire.ReplyOutcomeCancelled, Reason: "cancel", Images: int64(len(backend.images)), Usage: backend.usage, Cost: backend.cost, Deliveries: []wire.Delivery{}}
	}
	for index, output := range backend.images {
		sum := sha256.Sum256(output.data)
		digest := "sha256:" + hex.EncodeToString(sum[:])
		switch commits[index](ctx, digest, output.data) {
		case ContentResolved:
		case ContentForbidden:
			return wire.ImageReply{Outcome: wire.ReplyOutcomeForbidden, Reason: "output:forbidden", Images: int64(len(backend.images)), Usage: backend.usage, Cost: backend.cost, Deliveries: []wire.Delivery{}}
		default:
			return wire.ImageReply{Outcome: wire.ReplyOutcomeUnavailable, Reason: "output:unavailable", Images: int64(len(backend.images)), Usage: backend.usage, Cost: backend.cost, Deliveries: []wire.Delivery{}}
		}
		delivery := wire.Delivery{Digest: digest, MediaType: output.mediaType, Size: int64(len(output.data)), Location: "local"}
		end.Deliveries = append(end.Deliveries, delivery)
		op.emit(wire.Delta{Kind: wire.DeltaKindImageResult, ImageResult: &wire.ImageResult{Index: int64(index), Delivery: delivery}}, p.cfg.Now())
	}
	return end
}

func imageFailure(outcome wire.ReplyOutcome, reason string) wire.ImageReply {
	return wire.ImageReply{Outcome: outcome, Reason: reason, Deliveries: []wire.Delivery{}}
}

func validateRemoteImageDelivery(req wire.ImageRequest, results []wire.ImageResult, end wire.ImageReply) string {
	if int64(len(results)) != req.Count || len(end.Deliveries) != len(results) || end.Images != int64(len(results)) {
		return "remote:count"
	}
	for i, result := range results {
		if result.Index != int64(i) || result.Delivery != end.Deliveries[i] || !canonicalSHA256(result.Delivery.Digest) || !generatedInputMedia(result.Delivery.MediaType) || result.Delivery.Size < 1 || result.Delivery.Location != "local" {
			return "remote:delivery"
		}
	}
	return ""
}

func remoteImageDeltaShape(delta wire.Delta) string {
	n := 0
	for _, present := range []bool{delta.Part != nil, delta.Usage != nil, delta.End != nil, delta.Segment != nil, delta.TranscriptionEnd != nil, delta.Audio != nil,
		delta.SpeechEnd != nil, delta.Transcript != nil, delta.LiveEnd != nil, delta.ImageProgress != nil, delta.ImageResult != nil, delta.ImageEnd != nil} {
		if present {
			n++
		}
	}
	if n != 1 {
		return "remote:page"
	}
	switch delta.Kind {
	case wire.DeltaKindImageProgress:
		if delta.ImageProgress == nil || delta.ImageProgress.Percent < 0 || delta.ImageProgress.Percent > 100 || len(delta.ImageProgress.Message) > 4096 || !utf8.ValidString(delta.ImageProgress.Message) {
			return "remote:progress"
		}
	case wire.DeltaKindImageResult:
		if delta.ImageResult == nil {
			return "remote:page"
		}
	case wire.DeltaKindEnd:
		if delta.ImageEnd == nil {
			return "remote:terminal"
		}
	default:
		return "remote:page"
	}
	return ""
}

func validateRemoteImageTerminal(req wire.ImageRequest, results []wire.ImageResult, end wire.ImageReply) string {
	if !end.Outcome.Known() {
		return "remote:terminal"
	}
	if end.Outcome == wire.ReplyOutcomeCompleted {
		return validateRemoteImageDelivery(req, results, end)
	}
	if len(results) != 0 || len(end.Deliveries) != 0 || end.Images != 0 {
		return "remote:terminal"
	}
	return ""
}

func validateRemoteImagePage(page wire.DeltaPage, cursor int64) string {
	if cursor < 0 || len(page.Deltas) > 256 || cursor > math.MaxInt64-int64(len(page.Deltas)) || page.Next != cursor+int64(len(page.Deltas)) {
		return "remote:page"
	}
	for i, delta := range page.Deltas {
		if delta.Sequence != cursor+int64(i) {
			return "remote:page"
		}
		if delta.ImageEnd != nil && (i != len(page.Deltas)-1 || !page.AtEnd) {
			return "remote:terminal"
		}
	}
	return ""
}

func (p *Provider) runRemoteImage(ctx context.Context, op *operation, req wire.ImageRequest) wire.ImageReply {
	transport, ok := op.host.RemoteTransport()
	if !ok {
		return imageFailure(wire.ReplyOutcomeUnavailable, "remote:transport")
	}
	forwarded := req
	forwarded.Model = op.model
	forwarded.Extensions = cloneStrings(req.Extensions)
	if forwarded.Extensions == nil {
		forwarded.Extensions = map[string]string{}
	}
	forwarded.Extensions[ClaimExtension] = op.subject.Program
	client := wire.NewImageClient(transport.WithContext(ctx))
	admission, err := client.Start(forwarded)
	if err != nil {
		return imageFailure(wire.ReplyOutcomeUnavailable, "remote:unreachable")
	}
	if admission.Outcome != wire.StartOutcomeAccepted {
		outcome := replyFromStart(admission.Outcome)
		if !outcome.Known() {
			outcome = wire.ReplyOutcomeUnavailable
		}
		return imageFailure(outcome, "remote:"+admission.Reason)
	}
	cancelRemote := func() {
		stop, done := context.WithTimeout(context.Background(), 5*time.Second)
		defer done()
		_, _ = wire.NewImageClient(transport.WithContext(stop)).Cancel(admission.Operation)
	}
	var results []wire.ImageResult
	for cursor := int64(0); ; {
		page, err := client.Observe(admission.Operation, cursor, 256, 65536, remoteObserveWaitMS)
		if ctx.Err() != nil {
			cancelRemote()
			return imageFailure(wire.ReplyOutcomeCancelled, "caller")
		}
		if err != nil || page.Outcome != wire.PageOutcomePage {
			cancelRemote()
			return imageFailure(wire.ReplyOutcomeUnavailable, "remote:unreachable")
		}
		if reason := validateRemoteImagePage(page, cursor); reason != "" {
			cancelRemote()
			return imageFailure(wire.ReplyOutcomeUnavailable, reason)
		}
		for _, delta := range page.Deltas {
			if reason := remoteImageDeltaShape(delta); reason != "" {
				cancelRemote()
				return imageFailure(wire.ReplyOutcomeUnavailable, reason)
			}
			switch delta.Kind {
			case wire.DeltaKindImageProgress:
				progress := *delta.ImageProgress
				op.emit(wire.Delta{Kind: wire.DeltaKindImageProgress, ImageProgress: &progress}, p.cfg.Now())
			case wire.DeltaKindImageResult:
				result := *delta.ImageResult
				if int64(len(results)) >= req.Count || result.Index != int64(len(results)) || !canonicalSHA256(result.Delivery.Digest) || !generatedInputMedia(result.Delivery.MediaType) || result.Delivery.Size < 1 || result.Delivery.Location != "local" {
					cancelRemote()
					return imageFailure(wire.ReplyOutcomeUnavailable, "remote:delivery")
				}
				results = append(results, result)
			case wire.DeltaKindEnd:
				end := *delta.ImageEnd
				if reason := validateRemoteImageTerminal(req, results, end); reason != "" {
					cancelRemote()
					return imageFailure(wire.ReplyOutcomeUnavailable, reason)
				}
				if end.Outcome == wire.ReplyOutcomeCompleted {
					if !op.beginCompletion() {
						cancelRemote()
						return imageFailure(wire.ReplyOutcomeCancelled, "cancel")
					}
					for i := range end.Deliveries {
						end.Deliveries[i].Location = op.host.Domain
						results[i].Delivery.Location = op.host.Domain
						result := results[i]
						op.emit(wire.Delta{Kind: wire.DeltaKindImageResult, ImageResult: &result}, p.cfg.Now())
					}
				}
				return end
			}
		}
		if page.AtEnd {
			cancelRemote()
			return imageFailure(wire.ReplyOutcomeUnavailable, "remote:terminal")
		}
		if len(page.Deltas) == 0 && !waitImagePoll(ctx, minimumImagePollDelay) {
			cancelRemote()
			return imageFailure(wire.ReplyOutcomeCancelled, "caller")
		}
		cursor = page.Next
	}
}
