// Package inference is the runtime provider of abstraction.inference/chat@1.
// It picks a host through the router, decides abstraction.inference/complete
// for the bound caller, holds per-credential ceilings, applies a hosted host's
// credential through the credentials applier for each outgoing request, and
// streams the upstream reply as retained deltas observed in bounded pages.
package inference

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"net/http"
	"sort"
	"sync"
	"time"

	wire "github.com/openabstractions/abstraction-inference/go/abstraction/inference/api"
	router "github.com/openabstractions/abstraction-router/go"
)

// Contract names and vocabulary this provider serves.
const (
	Contract           = "abstraction.inference/chat@1"
	ActionComplete     = "abstraction.inference/complete"
	ActionHostManage   = "abstraction.inference/host.manage"
	ActionKeyIssue     = "abstraction.inference/key.issue"
	ActionAuditRead    = "abstraction.inference/audit.read"
	GuaranteeLocalOnly = "abstraction.inference/local-only@1"
	GuaranteeHosted    = "abstraction.inference/hosted-allowed@1"
	FeatureTools       = "abstraction.inference/tools@1"
	FeatureJSONSchema  = "abstraction.inference/json-schema@1"
	FeatureVision      = "abstraction.inference/vision@1"
)

// ResourceHost is the rights resource of complete for one host.
func ResourceHost(name string) string { return "host:" + name }

// requestGuaranteeWords projects typed request choices into the router's open
// guarantee vocabulary. Validation runs before this boundary.
func requestGuaranteeWords(values []wire.RequestGuarantee) []string {
	words := make([]string, len(values))
	for i, value := range values {
		words[i] = string(value)
	}
	return words
}

// Subject is the bound caller: account identifier and normalized absolute
// executable path, asserted by the receiving boundary from Program proof.
type Subject struct{ Account, Program string }

// Decider answers a rights decision with its outcome word (permitted, denied,
// not_granted, unknown_action). An error means the decision point could not
// answer, and reads unavailable.
type Decider func(ctx context.Context, subject Subject, action, resource string) (string, error)

// Applier applies credential name for one outgoing request of subject to
// target, a lowercase host name, as consumer. It returns the headers and
// "applied", or nil and the applier's outcome word ("unavailable" when the
// holder or its decision point cannot answer).
type Applier func(ctx context.Context, subject Subject, consumer, name, target string) (map[string]string, string)

// Admitter is a check a provider registers for work its own program does on
// the picked host before a call is decided: a load, a warm-up, anything that
// keeps its own refusal word instead of turning into an upstream failure. A
// false answer carries the provider's own reason word and refuses the
// operation before Decide runs (INF-A5).
type Admitter func(ctx context.Context, host *router.Host, model string) (reason string, ok bool)

// ContentOutcome is the result of resolving one digest for the original
// caller. The resolver enforces the caller's content scope before returning
// bytes.
type ContentOutcome string

const (
	ContentResolved    ContentOutcome = "resolved"
	ContentUnknown     ContentOutcome = "unknown"
	ContentForbidden   ContentOutcome = "forbidden"
	ContentUnavailable ContentOutcome = "unavailable"
	ContentTooLarge    ContentOutcome = "too_large"
)

// ContentResolver reads at most maxBytes of digest for subject. Resolved bytes
// must be the complete content named by the canonical SHA-256 digest.
type ContentResolver func(ctx context.Context, subject Subject, digest string, maxBytes int64) ([]byte, ContentOutcome)

// ContentCommitter publishes generated bytes under digest after rechecking the
// same authorization PrepareContentWrite preflighted. It is single-use.
type ContentCommitter func(ctx context.Context, digest string, data []byte) ContentOutcome

// ContentWritePreparer authorizes a generated output before upstream spend.
// profile is the stable output resource suffix (for speech, output:speech).
type ContentWritePreparer func(ctx context.Context, subject Subject, profile, mediaType string, maxBytes int64) (ContentCommitter, ContentOutcome)

// Routes a caller reaches chat@1 by, recorded in Record.Route.
const (
	RouteNative = "native"
	RouteWindow = "window"
	RouteRemote = "remote"
)

// ClaimExtension is the request extension a delegating runtime sets to the
// program that asked it. A remote runtime records it as a claim attributed to
// the mapped caller and decides nothing on it.
const ClaimExtension = "openabstractions/claimed-program"

type routeKey struct{}

type executionPlacementKey struct{}
type leafExecutionKey struct{}
type executionBindingKey struct{}

// ExecutionPlacement is the fixed execution policy of the endpoint that
// admitted a call. It is attached by the service boundary, independent of
// request fields.
type ExecutionPlacement uint8

const (
	ExecutionAny ExecutionPlacement = iota
	ExecutionLocal
	ExecutionRemote
)

// WithExecutionPlacement attaches the immutable policy of the receiving
// endpoint to an admitting call.
func WithExecutionPlacement(ctx context.Context, placement ExecutionPlacement) context.Context {
	return context.WithValue(ctx, executionPlacementKey{}, placement)
}

func executionPlacementOf(ctx context.Context) ExecutionPlacement {
	if placement, ok := ctx.Value(executionPlacementKey{}).(ExecutionPlacement); ok {
		return placement
	}
	return ExecutionAny
}

// WithLeafExecution marks an endpoint as an initial one-hop provider. Its
// requests may execute on leaf backends and cannot delegate to another OA
// native or remote runtime.
func WithLeafExecution(ctx context.Context) context.Context {
	return context.WithValue(ctx, leafExecutionKey{}, true)
}

// ExecutionBinding pins admission to the logical host and declaration
// generation selected by a mediated service endpoint.
type ExecutionBinding struct {
	Host      string
	BindingID string
}

// WithExecutionBinding attaches the route selected by resolution. An empty
// binding leaves ordinary router selection in effect.
func WithExecutionBinding(ctx context.Context, binding ExecutionBinding) context.Context {
	return context.WithValue(ctx, executionBindingKey{}, binding)
}

type route struct{ name, rung, domain, claim string }

// WithRoute marks ctx with the route a caller took and the rung of proof its
// boundary bound it at (identity Peer.Rung). Start records both.
func WithRoute(ctx context.Context, name, rung string) context.Context {
	return context.WithValue(ctx, routeKey{}, route{name: name, rung: rung})
}

// WithRemote marks ctx as a call over the remote transport from the caller
// its certificate maps to, domain. Start records the route, the rung and the
// domain, and the request's claim extension as a claim.
func WithRemote(ctx context.Context, domain, rung string) context.Context {
	return context.WithValue(ctx, routeKey{}, route{name: RouteRemote, rung: rung, domain: domain})
}

func routeOf(ctx context.Context) route {
	if r, ok := ctx.Value(routeKey{}).(route); ok {
		return r
	}
	return route{name: RouteNative}
}

// Record is one log record: an ended operation or an admission refusal. It
// carries names and counts, never header values or message content.
type Record struct {
	Operation string
	// Profile is the host profile of the call: embed for embed@1, "" for chat.
	Profile      string
	Route        string
	Rung         string
	Account      string
	Program      string
	Host         string
	Model        string
	Family       string
	Credential   string
	Outcome      string
	Reason       string
	Ceiling      string
	TokensIn     int64
	TokensOut    int64
	AudioSeconds int64
	Characters   int64
	Images       int64
	WallMS       int64
	// Domain is the remote host a delegated operation went to, or on the
	// remote runtime the caller its certificate maps to.
	Domain string
	// Claim is the program a delegating runtime says asked, attributed to Domain.
	Claim string
}

// Config composes a provider. Router, Decide and Apply are required.
type Config struct {
	Router *router.Router
	Decide Decider
	Apply  Applier
	// Admit runs after pick and before Decide, once a host is picked. Nil runs
	// nothing. A false answer refuses the operation `unavailable` with the
	// hook's reason, or `not_permitted` when the reason is exactly that word
	// (INF-A5).
	Admit Admitter
	// ResolveContent reads image digests after host authorization and before
	// credentials or an upstream request. It is required by requests that use
	// vision@1 and receives the original bound caller.
	ResolveContent ContentResolver
	// MaxImageBytes bounds each resolved image; default 20 MiB.
	MaxImageBytes int64
	// MaxVisionBytes bounds the sum of image payload bytes after every digest
	// occurrence is expanded in one request; default 64 MiB.
	MaxVisionBytes int64
	// MaxAudioBytes bounds one transcription input; default 16 MiB.
	MaxAudioBytes int64
	// PrepareContentWrite authorizes and returns a single-use generated-output
	// commit capability. Speech requires it before upstream spend.
	PrepareContentWrite ContentWritePreparer
	// MaxSpeechBytes bounds one generated speech result; default 64 MiB.
	MaxSpeechBytes int64
	// MaxGeneratedImageBytes bounds each generated image; default 20 MiB.
	MaxGeneratedImageBytes int64
	// MaxImageOutputBytes bounds all generated images in one operation; default 64 MiB.
	MaxImageOutputBytes int64
	// Ceilings holds per-credential limits and counts; nil means none.
	Ceilings *Ceilings
	// Record receives one record per ended operation and per admission refusal.
	Record func(Record)
	// OnError receives provider faults. Messages carry no header value.
	OnError func(error)
	// HTTP sends upstream requests; nil uses a client without a total timeout,
	// because a stream lasts as long as the model writes.
	HTTP *http.Client
	// LiveDialer opens local vendor realtime sessions after the service applies
	// rights, budget, credential and redirect policy. Nil leaves local realtime
	// unavailable; remote live sessions use the shared transport independently.
	LiveDialer LiveDialer
	// Retention keeps an ended operation observable; default one minute.
	Retention time.Duration
	// Idle cancels an operation nobody observes; default ten seconds.
	Idle time.Duration
	// RetainedDeltas bounds the readable deltas per operation; default 4096.
	RetainedDeltas int
	// MaxOperations bounds a subject's unended operations; default 8.
	MaxOperations int
	// SurveyAge re-reads the router's hosts when its snapshot is older; default 30 s.
	SurveyAge time.Duration
	// Now is the clock; nil uses time.Now.
	Now func() time.Time
}

// Provider serves chat@1 for bound subjects.
type Provider struct {
	cfg      Config
	mu       sync.Mutex
	ops      map[string]*operation
	surveyed time.Time
	survey   sync.Mutex
	ctx      context.Context
	stop     context.CancelFunc
	done     chan struct{}
	runs     sync.WaitGroup
}

// New starts a provider and its idle and retention watchdog. Close stops it.
func New(cfg Config) (*Provider, error) {
	if cfg.Router == nil || cfg.Decide == nil || cfg.Apply == nil {
		return nil, errors.New("inference: router, decision function and applier required")
	}
	if cfg.HTTP == nil {
		cfg.HTTP = &http.Client{}
	}
	if cfg.MaxImageBytes <= 0 {
		cfg.MaxImageBytes = 20 << 20
	}
	if cfg.MaxVisionBytes <= 0 {
		cfg.MaxVisionBytes = 64 << 20
	}
	if cfg.MaxAudioBytes <= 0 {
		cfg.MaxAudioBytes = 16 << 20
	}
	if cfg.MaxSpeechBytes <= 0 {
		cfg.MaxSpeechBytes = 64 << 20
	}
	if cfg.MaxGeneratedImageBytes <= 0 {
		cfg.MaxGeneratedImageBytes = 20 << 20
	}
	if cfg.MaxImageOutputBytes <= 0 {
		cfg.MaxImageOutputBytes = 64 << 20
	}
	if cfg.Retention <= 0 {
		cfg.Retention = time.Minute
	}
	if cfg.Idle <= 0 {
		cfg.Idle = 10 * time.Second
	}
	if cfg.RetainedDeltas <= 0 {
		cfg.RetainedDeltas = 4096
	}
	if cfg.MaxOperations <= 0 {
		cfg.MaxOperations = 8
	}
	if cfg.SurveyAge <= 0 {
		cfg.SurveyAge = 30 * time.Second
	}
	if cfg.Now == nil {
		cfg.Now = time.Now
	}
	ctx, stop := context.WithCancel(context.Background())
	p := &Provider{cfg: cfg, ops: map[string]*operation{}, ctx: ctx, stop: stop, done: make(chan struct{})}
	go p.watch()
	return p, nil
}

// Close cancels every unended operation, waits for their upstream requests to
// close, and stops the watchdog.
func (p *Provider) Close() error {
	p.mu.Lock()
	p.stop()
	p.mu.Unlock()
	<-p.done
	p.runs.Wait()
	return nil
}

func (p *Provider) report(err error) {
	if err != nil && p.cfg.OnError != nil {
		p.cfg.OnError(err)
	}
}

func (p *Provider) record(r Record) {
	if p.cfg.Record != nil {
		p.cfg.Record(r)
	}
}

// Admission bounds this provider reports.
func (p *Provider) bounds(a *wire.Admission) {
	a.RetentionMs = p.cfg.Retention.Milliseconds()
	a.IdleMs = p.cfg.Idle.Milliseconds()
	a.RetainedDeltas = int64(p.cfg.RetainedDeltas)
}

// admitStartOutcome is the Start outcome for a false Admit answer: the
// provider's own word, `not_permitted` reading as that outcome and every
// other word reading as `unavailable`.
func admitStartOutcome(reason string) wire.StartOutcome {
	if reason == "not_permitted" {
		return wire.StartOutcomeNotPermitted
	}
	return wire.StartOutcomeUnavailable
}

// admitEmbedOutcome mirrors admitStartOutcome for embed@1.
func admitEmbedOutcome(reason string) wire.EmbedOutcome {
	if reason == "not_permitted" {
		return wire.EmbedOutcomeNotPermitted
	}
	return wire.EmbedOutcomeUnavailable
}

func refusal(outcome wire.StartOutcome, reason string) wire.Admission {
	return wire.Admission{Outcome: outcome, Reason: reason}
}

// Start admits one request for subject in the contract's order (INF-A2) and
// begins its upstream request. Nothing leaves the service before every check
// passes.
func (p *Provider) Start(ctx context.Context, subject Subject, req wire.Request) wire.Admission {
	started := p.cfg.Now()
	via := routeOf(ctx)
	if via.name == RouteRemote {
		via.claim = req.Extensions[ClaimExtension]
	}
	refuse := func(outcome wire.StartOutcome, reason string, host *router.Host, model string) wire.Admission {
		r := Record{Route: via.name, Rung: via.rung, Account: subject.Account, Program: subject.Program, Model: req.Model, Family: familyOf(req.Model),
			Credential: req.Credential, Outcome: outcome.String(), Reason: reason, WallMS: p.cfg.Now().Sub(started).Milliseconds(), Domain: via.domain, Claim: via.claim}
		if host != nil {
			r.Host, r.Model = host.Name, model
			if host.Wire == router.WireRemote {
				r.Domain = host.Domain
			}
		}
		if p.cfg.Ceilings != nil && req.Credential != "" {
			r.Ceiling = p.cfg.Ceilings.State(req.Credential)
		}
		p.record(r)
		return refusal(outcome, reason)
	}
	if subject.Account == "" || subject.Program == "" {
		return refuse(wire.StartOutcomeForbidden, "caller", nil, "")
	}
	if reason := validate(req); reason != "" {
		return refuse(wire.StartOutcomeInvalid, reason, nil, "")
	}
	host, model, reason := p.pick(ctx, req.Model, requestGuaranteeWords(req.Guarantees), req.Credential, router.ProfileChat)
	if host == nil {
		return refuse(wire.StartOutcomeNoHost, reason, nil, "")
	}
	if p.cfg.Admit != nil {
		if admitReason, ok := p.cfg.Admit(ctx, host, model); !ok {
			return refuse(admitStartOutcome(admitReason), admitReason, host, model)
		}
	}
	adapter := adapterFor(host.Wire)
	if host.Wire == "" {
		adapter = adapterFor(router.WireOpenAICompatible)
	}
	if adapter == nil {
		return refuse(wire.StartOutcomeUnsupportedFeature, "wire:"+host.Wire, host, model)
	}
	if reason := adapter.unsupported(req); reason != "" {
		return refuse(wire.StartOutcomeUnsupportedFeature, reason, host, model)
	}
	word, err := p.cfg.Decide(ctx, subject, ActionComplete, ResourceHost(host.Name))
	if err != nil || ctx.Err() != nil {
		p.report(err)
		return refuse(wire.StartOutcomeUnavailable, "rights:unavailable", host, model)
	}
	switch word {
	case "permitted":
	case "denied", "not_granted", "unknown_action":
		return refuse(wire.StartOutcomeNotPermitted, "rights:"+word, host, model)
	default:
		return refuse(wire.StartOutcomeUnavailable, "rights:unavailable", host, model)
	}
	images := map[string][]byte(nil)
	if host.Wire != router.WireRemote {
		var outcome wire.StartOutcome
		var contentReason string
		images, outcome, contentReason = p.resolveImages(ctx, subject, req)
		if contentReason != "" {
			return refuse(outcome, contentReason, host, model)
		}
	}
	credential := ""
	if host.Hosted {
		credential = host.Credential
	}
	// A remote runtime holds, applies and limits its own credential.
	remote := host.Wire == router.WireRemote
	if credential != "" && p.cfg.Ceilings != nil && !remote {
		if unit, over := p.cfg.Ceilings.Exceeded(credential); over {
			return refuse(wire.StartOutcomeBudgetExceeded, "ceiling:"+unit+":"+credential, host, model)
		}
	}
	if p.active(subject) >= p.cfg.MaxOperations {
		return refuse(wire.StartOutcomeExhausted, "capacity", host, model)
	}
	var headers map[string]string
	if credential != "" && !remote {
		var outcome string
		headers, outcome = p.cfg.Apply(ctx, subject, Contract, credential, router.Target(host.Base))
		switch outcome {
		case "applied":
		case "unavailable", "":
			return refuse(wire.StartOutcomeUnavailable, "credential:unavailable:"+credential, host, model)
		default:
			return refuse(wire.StartOutcomeNotPermitted, "credential:"+outcome+":"+credential, host, model)
		}
	}
	id, err := operationID()
	if err != nil {
		clear(headers)
		p.report(err)
		return refuse(wire.StartOutcomeUnavailable, "capacity", host, model)
	}
	op := newOperation(id, subject, host, model, credential, p.cfg.RetainedDeltas, started)
	op.route, op.remote = via, remote
	if binding, pinned := ctx.Value(executionBindingKey{}).(ExecutionBinding); pinned {
		op.bindingID = binding.BindingID
	}
	runCtx, cancel := context.WithCancel(p.ctx)
	op.cancel = cancel
	if outcome := p.admitOperation(op); outcome != wire.StartOutcomeAccepted {
		cancel()
		clear(headers)
		reason := "capacity"
		if outcome == wire.StartOutcomeUnavailable {
			reason = "provider:closed"
		}
		return refuse(outcome, reason, host, model)
	}
	go p.run(runCtx, op, adapter, req, images, headers)
	a := wire.Admission{Outcome: wire.StartOutcomeAccepted, Operation: id, Host: host.Name, Model: model}
	p.bounds(&a)
	return a
}

func operationID() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	return "op-" + hex.EncodeToString(b[:]), nil
}

func (p *Provider) active(subject Subject) int {
	p.mu.Lock()
	defer p.mu.Unlock()
	n := 0
	for _, op := range p.ops {
		if op.subject == subject && !op.isEnded() {
			n++
		}
	}
	return n
}

// HasBindingOperations reports whether an operation selected from bindingID is
// still active or retained for observation. Service endpoint lifecycle uses it
// to keep a withdrawn generation reachable only for its existing operations.
func (p *Provider) HasBindingOperations(bindingID string) bool {
	if bindingID == "" {
		return false
	}
	p.mu.Lock()
	defer p.mu.Unlock()
	for _, op := range p.ops {
		if op.bindingID == bindingID || op.bindingID == "" && op.host != nil && op.host.BindingID == bindingID {
			return true
		}
	}
	return false
}

// ActiveForModel reports whether an operation for model is still active or
// retained for observation. A provider whose Admit hook loads model as an
// object uses it to tell a started or still-open operation from one that has
// fully ended and aged out of retention, so its own idle clock can keep the
// object it loaded for as long as the operation is open (INF-A5).
func (p *Provider) ActiveForModel(model string) bool {
	if model == "" {
		return false
	}
	p.mu.Lock()
	defer p.mu.Unlock()
	for _, op := range p.ops {
		if op.model == model {
			return true
		}
	}
	return false
}

// pick selects a host serving profile through the router within the request's
// guarantees and credential.
func (p *Provider) pick(ctx context.Context, model string, guarantees []string, credential, profile string) (*router.Host, string, string) {
	hosted := false
	localOnly := false
	for _, g := range guarantees {
		if g == GuaranteeHosted {
			hosted = true
		}
		if g == GuaranteeLocalOnly {
			localOnly = true
		}
	}
	placement := executionPlacementOf(ctx)
	binding, pinned := ctx.Value(executionBindingKey{}).(ExecutionBinding)
	if placement == ExecutionRemote && localOnly {
		return nil, "", "placement:remote"
	}
	hosts := p.cfg.Router.Hosts()
	allowed := []string{}
	byName := map[string]*router.Host{}
	for _, h := range hosts {
		if !h.Servable() {
			continue
		}
		if pinned && (h.Name != binding.Host || h.BindingID == "" || h.BindingID != binding.BindingID) {
			continue
		}
		if placement == ExecutionLocal && h.Hosted || placement == ExecutionRemote && !h.Hosted {
			continue
		}
		if leaf, _ := ctx.Value(leafExecutionKey{}).(bool); leaf && (h.Wire == router.WireNative || h.Wire == router.WireRemote) {
			continue
		}
		if !h.Hosted || hosted && h.Credential == credential {
			allowed = append(allowed, h.Name)
			byName[h.Name] = h
		}
	}
	fresh := false
	p.survey.Lock()
	if now := p.cfg.Now(); now.Sub(p.surveyed) >= p.cfg.SurveyAge {
		fresh, p.surveyed = true, now
	}
	d, _ := p.cfg.Router.Route(router.Request{Model: model, Fresh: fresh, Hosts: &allowed, Profile: profile})
	p.survey.Unlock()
	switch d.Verdict {
	case router.Resident, router.WouldLoad, router.Hosted:
		if h := byName[d.Host]; h != nil {
			if pinned && (h.Name != binding.Host || h.BindingID != binding.BindingID) {
				return nil, "", "binding:stale"
			}
			return h, d.Model, ""
		}
	}
	return nil, "", "router:" + d.Verdict
}

// Observe reads a bounded page of subject's operation from cursor, waiting up
// to waitMS for a first delta. ctx ends the wait when the caller disconnects.
func (p *Provider) Observe(ctx context.Context, subject Subject, id string, cursor, maxDeltas, maxBytes, waitMS int64) wire.DeltaPage {
	return p.observeProfile(ctx, subject, id, router.ProfileChat, cursor, maxDeltas, maxBytes, waitMS)
}

func (p *Provider) observeProfile(ctx context.Context, subject Subject, id, profile string, cursor, maxDeltas, maxBytes, waitMS int64) wire.DeltaPage {
	refused := func(outcome wire.PageOutcome) wire.DeltaPage {
		return wire.DeltaPage{Outcome: outcome, Deltas: []wire.Delta{}, Next: cursor}
	}
	if subject.Account == "" || subject.Program == "" {
		return refused(wire.PageOutcomeForbidden)
	}
	if maxDeltas < 1 || maxDeltas > 256 || maxBytes < 1 || maxBytes > 65536 || waitMS < 0 || waitMS > 30000 || cursor < 0 || len(id) == 0 || len(id) > 128 {
		return refused(wire.PageOutcomeInvalid)
	}
	op := p.visibleProfile(subject, id, profile)
	if op == nil {
		return refused(wire.PageOutcomeUnknown)
	}
	op.observeBegin()
	defer op.observeEnd(p.cfg.Now())
	return op.page(ctx, cursor, maxDeltas, maxBytes, time.Duration(waitMS)*time.Millisecond)
}

// Cancel stops subject's operation and closes its upstream request.
func (p *Provider) Cancel(subject Subject, id string) wire.Cancellation {
	return p.cancelProfile(subject, id, router.ProfileChat)
}

func (p *Provider) cancelProfile(subject Subject, id, profile string) wire.Cancellation {
	if subject.Account == "" || subject.Program == "" {
		return wire.Cancellation{Outcome: wire.CancelOutcomeForbidden}
	}
	if len(id) == 0 || len(id) > 128 {
		return wire.Cancellation{Outcome: wire.CancelOutcomeInvalid}
	}
	op := p.visibleProfile(subject, id, profile)
	if op == nil {
		return wire.Cancellation{Outcome: wire.CancelOutcomeUnknown}
	}
	if outcome, ended := op.endedOutcome(); ended {
		return wire.Cancellation{Outcome: wire.CancelOutcomeEnded, ReplyOutcome: &outcome}
	}
	stopped := op.stop("cancel")
	select {
	case <-op.finished:
	case <-time.After(5 * time.Second):
		return wire.Cancellation{Outcome: wire.CancelOutcomeUnavailable}
	}
	outcome, _ := op.endedOutcome()
	if !stopped || outcome != wire.ReplyOutcomeCancelled {
		return wire.Cancellation{Outcome: wire.CancelOutcomeEnded, ReplyOutcome: &outcome}
	}
	return wire.Cancellation{Outcome: wire.CancelOutcomeCancelled, ReplyOutcome: &outcome}
}

func (p *Provider) visible(subject Subject, id string) *operation {
	return p.visibleProfile(subject, id, router.ProfileChat)
}

func (p *Provider) visibleProfile(subject Subject, id, profile string) *operation {
	p.mu.Lock()
	defer p.mu.Unlock()
	op := p.ops[id]
	if op == nil || op.subject != subject || op.profile != profile {
		return nil
	}
	return op
}

// watch cancels idle operations and retires ended ones after retention.
func (p *Provider) watch() {
	defer close(p.done)
	tick := time.NewTicker(100 * time.Millisecond)
	defer tick.Stop()
	for {
		select {
		case <-p.ctx.Done():
			return
		case <-tick.C:
		}
		now := p.cfg.Now()
		p.mu.Lock()
		var idle []*operation
		ids := make([]string, 0, len(p.ops))
		for id := range p.ops {
			ids = append(ids, id)
		}
		sort.Strings(ids)
		for _, id := range ids {
			op := p.ops[id]
			if ended, at := op.endedAt(); ended {
				if now.Sub(at) >= p.cfg.Retention {
					delete(p.ops, id)
				}
			} else if op.idleSince(now) >= p.cfg.Idle {
				idle = append(idle, op)
			}
		}
		p.mu.Unlock()
		for _, op := range idle {
			op.stopIdle(now, p.cfg.Idle)
		}
	}
}
