# Code generated by abstraction-idl from abstraction-inference/job.thrift. DO NOT EDIT.

"""abstraction.inference.job: generated contract types, vocabularies and service clients."""

from ._codec import (
    Delivery,
    Document,
    EXECUTION_GUARANTEES,
    ImageRequest,
    JobResult,
    KINDS,
    Mode,
    Profile,
    Refusal,
    Request,
    RequestGuarantee,
    decode,
    encode,
)

__all__ = [
    "Delivery",
    "Document",
    "EXECUTION_GUARANTEES",
    "ImageRequest",
    "JobResult",
    "KINDS",
    "Mode",
    "Profile",
    "Refusal",
    "Request",
    "RequestGuarantee",
    "decode",
    "encode",
]

# Report every class and function as a member of this package, so help(),
# tracebacks and pickles name the import an application writes.
for _name in __all__:
    _value = globals()[_name]
    if isinstance(_value, type) or callable(_value):
        _value.__module__ = __name__
del _name, _value
