# Code generated by abstraction-idl from abstraction-inference/job.thrift. DO NOT EDIT.

from __future__ import annotations

import dataclasses
import enum

_HEX = b"0123456789abcdef"
_WS = (0x20, 0x09, 0x0A, 0x0D)
_SHORT = {0x22: b'\\"', 0x5C: b"\\\\", 0x08: b"\\b", 0x0C: b"\\f",
          0x0A: b"\\n", 0x0D: b"\\r", 0x09: b"\\t"}


def _esc_byte(out, c):
    short = _SHORT.get(c)
    if short is not None:
        out += short
    elif c < 0x20:
        out += b"\\u00" + bytes([_HEX[c >> 4], _HEX[c & 0xF]])
    else:
        out.append(c)


def _num(out, n):
    out += str(int(n)).encode("ascii")


def _pad(out, depth):
    out += b" " * (depth * 2)


def _strs(out, v, depth):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, s in enumerate(v):
        _pad(out, depth + 1)
        _esc(out, s)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"]"


def _raw(out, s, depth):
    b = s.encode("utf-8") if isinstance(s, str) else s
    i, n = 0, len(b)
    while i < n:
        c = b[i]
        if c in _WS:
            i += 1
        elif c == 0x22:
            j = i + 1
            while j < n:
                if b[j] == 0x5C:
                    j += 2
                    continue
                if b[j] == 0x22:
                    j += 1
                    break
                j += 1
            out += b[i:j]
            i = j
        elif c in (0x7B, 0x5B):
            out.append(c)
            i += 1
            j = i
            while j < n and b[j] in _WS:
                j += 1
            if j < n and b[j] in (0x7D, 0x5D):
                out.append(b[j])
                i = j + 1
            else:
                depth += 1
                out += b"\n"
                _pad(out, depth)
        elif c in (0x7D, 0x5D):
            depth -= 1
            out += b"\n"
            _pad(out, depth)
            out.append(c)
            i += 1
        elif c == 0x2C:
            out += b",\n"
            _pad(out, depth)
            i += 1
        elif c == 0x3A:
            out += b": "
            i += 1
        else:
            out.append(c)
            i += 1


def _rawmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        _pad(out, depth + 1)
        _esc(out, k)
        out += b": "
        _raw(out, m[k], depth + 1)
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"}"

def _esc(out, s):
    out += b'"'
    for c in s.encode("utf-8"):
        _esc_byte(out, c)
    out += b'"'


def _strmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        _pad(out, depth + 1)
        _esc(out, k)
        out += b": "
        _esc(out, m[k])
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_list(out, v, depth, enc):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, x in enumerate(v):
        _pad(out, depth + 1)
        enc(out, x, depth + 1)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"]"


try:
    from enum import StrEnum as _StrEnum
except ImportError:  # Python 3.10
    class _StrEnum(str, enum.Enum):
        def __str__(self):
            return self.value


def _closed_enum(cls, value):
    if value is not None and not isinstance(value, str):
        raise Refusal("wrong_type", 0)
    try:
        cls(value)
    except ValueError:
        raise Refusal("bad_enum", 0) from None


def _open_enum(cls, value):
    try:
        return cls(value)
    except ValueError:
        return value


class Profile(_StrEnum):
    VIDEO = "video"
    IMAGE_BATCH = "image_batch"


class Mode(_StrEnum):
    GENERATE = "generate"
    EDIT = "edit"


class RequestGuarantee(_StrEnum):
    LOCAL_ONLY = "abstraction.inference/local-only@1"
    HOSTED_ALLOWED = "abstraction.inference/hosted-allowed@1"


KINDS = ["inference"]


EXECUTION_GUARANTEES = ["abstraction.inference/recoverable-upstream@1"]


@dataclasses.dataclass(kw_only=True)
class ImageRequest:
    """The durable image-shaped request. Its fields and bounds match
    abstraction.inference/image@1 ImageRequest. Keeping this job document
    self-contained lets the job SDK persist and reconcile it without importing a
    service transport codec."""

    model: str = ""
    mode: Mode | None = None
    prompt: str = ""
    size: str = ""
    count: int = 0
    image_digest: str = ""
    image_media_type: str = ""
    mask_digest: str = ""
    mask_media_type: str = ""
    guarantees: list[RequestGuarantee | str] = dataclasses.field(default_factory=list)
    credential: str = ""
    required_extensions: list[str] = dataclasses.field(default_factory=list)
    extensions: dict[str, str] = dataclasses.field(default_factory=dict)


@dataclasses.dataclass(kw_only=True)
class Delivery:
    """A typed result reference with the same meaning as
    abstraction.inference/image@1 Delivery."""

    digest: str = ""
    media_type: str = ""
    size: int = 0
    location: str = ""


@dataclasses.dataclass(kw_only=True)
class Request:
    """Durable inference work submitted as job kind inference. video carries an
    image-shaped generate request and duration_ms of 1..600000; image_batch
    carries duration zero and count 1..10. The embedded request retains its
    digest, guarantee, credential and extension bounds. The recoverable-upstream
    guarantee means the executor durably marks submission before the paid call,
    records a returned provider handle, resumes a known handle, and invokes the
    adapter's reconciliation path after an uncertain submit. It does not promise
    eventual resolution: an adapter such as Replicate that offers no lookup by
    caller operation keeps the job waiting as upstream:uncertain and never
    blindly submits it again. No URL, path, header, credential bytes or inline
    media crosses this value."""

    profile: Profile | None = None
    image: ImageRequest = dataclasses.field(default_factory=ImageRequest)
    duration_ms: int = 0


@dataclasses.dataclass(kw_only=True)
class JobResult:
    """The immutable successful result returned by the job operation. deliveries
    are ordered typed references committed for the original caller. Local
    references are canonical SHA-256 digests readable through that caller's
    authorized content reader; remote locations state their owning trust domain."""

    profile: Profile | None = None
    deliveries: list[Delivery] = dataclasses.field(default_factory=list)
    host: str = ""
    model: str = ""


@dataclasses.dataclass(kw_only=True)
class Document:
    """Exactly one of request or result is present. Request documents are opaque
    job submission spec bytes. Result documents are immutable operation result
    bytes read through abstraction.job/operation@1. The job layer does not parse
    either variant."""

    request: Request | None = None
    result: JobResult | None = None


def _write_image_request(out, v, depth):
    _closed_enum(Mode, v.mode)
    for item in v.guarantees:
        if not isinstance(item, str):
            raise Refusal("wrong_type", 0)
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "model")
    out += b": "
    _esc(out, v.model)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "mode")
    out += b": "
    _esc(out, v.mode)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "prompt")
    out += b": "
    _esc(out, v.prompt)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "size")
    out += b": "
    _esc(out, v.size)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "count")
    out += b": "
    _num(out, v.count)
    if v.image_digest:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "image_digest")
        out += b": "
        _esc(out, v.image_digest)
    if v.image_media_type:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "image_media_type")
        out += b": "
        _esc(out, v.image_media_type)
    if v.mask_digest:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "mask_digest")
        out += b": "
        _esc(out, v.mask_digest)
    if v.mask_media_type:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "mask_media_type")
        out += b": "
        _esc(out, v.mask_media_type)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "guarantees")
    out += b": "
    _strs(out, v.guarantees, depth + 1)
    if v.credential:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "credential")
        out += b": "
        _esc(out, v.credential)
    if v.required_extensions:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "required_extensions")
        out += b": "
        _strs(out, v.required_extensions, depth + 1)
    if v.extensions:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "extensions")
        out += b": "
        _strmap(out, v.extensions, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_delivery(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "digest")
    out += b": "
    _esc(out, v.digest)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "media_type")
    out += b": "
    _esc(out, v.media_type)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "size")
    out += b": "
    _num(out, v.size)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "location")
    out += b": "
    _esc(out, v.location)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_request(out, v, depth):
    _closed_enum(Profile, v.profile)
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "profile")
    out += b": "
    _esc(out, v.profile)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "image")
    out += b": "
    _write_image_request(out, v.image, depth + 1)
    if v.duration_ms != 0:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "duration_ms")
        out += b": "
        _num(out, v.duration_ms)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_job_result(out, v, depth):
    _closed_enum(Profile, v.profile)
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "profile")
    out += b": "
    _esc(out, v.profile)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "deliveries")
    out += b": "
    _write_list(out, v.deliveries, depth + 1, _write_delivery)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "host")
    out += b": "
    _esc(out, v.host)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "model")
    out += b": "
    _esc(out, v.model)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_document(out, v, depth):
    out += b"{"
    first = True
    if v.request is not None:
        first = False
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "request")
        out += b": "
        _write_request(out, v.request, depth + 1)
    if v.result is not None:
        if not first:
            out += b","
        first = False
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "result")
        out += b": "
        _write_job_result(out, v.result, depth + 1)
    if not first:
        out += b"\n"
        _pad(out, depth)
    out += b"}"


def encode(v):
    out = bytearray()
    _write_document(out, v, 0)
    out += b"\n"
    return bytes(out)


_QUOTE, _BACKSLASH, _COLON, _COMMA = 0x22, 0x5C, 0x3A, 0x2C
_LBRACE, _RBRACE, _LBRACK, _RBRACK = 0x7B, 0x7D, 0x5B, 0x5D
_MINUS, _ZERO, _NINE, _DOT, _LOWER_U, _LOWER_N = 0x2D, 0x30, 0x39, 0x2E, 0x75, 0x6E
_UNESCAPE = {0x22: 0x22, 0x5C: 0x5C, 0x2F: 0x2F, 0x62: 0x08,
             0x66: 0x0C, 0x6E: 0x0A, 0x72: 0x0D, 0x74: 0x09}
_DEPTH_LIMIT = 64
_I64_DIGITS = 19


class Refusal(ValueError):
    """Bytes the contract refuses: word names the rule, offset the byte."""

    def __init__(self, word, offset):
        super().__init__("refused: %s at byte %d" % (word, offset))
        self.word = word
        self.offset = offset


class _Reader:
    __slots__ = ("buf", "pos", "depth")

    def __init__(self, buf):
        self.buf = buf
        self.pos = 0
        self.depth = 0

    def refuse(self, word):
        return Refusal(word, self.pos)

    def at(self):
        return self.buf[self.pos] if self.pos < len(self.buf) else 0

    def ws(self):
        while self.pos < len(self.buf) and self.buf[self.pos] in _WS:
            self.pos += 1

    def enter(self):
        self.depth += 1
        if self.depth > _DEPTH_LIMIT:
            raise self.refuse("depth_exceeded")

    def digit(self):
        return _ZERO <= self.at() <= _NINE

    def string(self):
        if self.at() != _QUOTE:
            raise self.refuse("wrong_type")
        self.pos += 1
        out = bytearray()
        while True:
            if self.pos >= len(self.buf):
                raise self.refuse("malformed")
            c = self.buf[self.pos]
            if c == _QUOTE:
                self.pos += 1
                try:
                    return out.decode("utf-8")
                except UnicodeDecodeError:
                    raise self.refuse("bad_string") from None
            if c < 0x20:
                raise self.refuse("bad_string")
            if c == _BACKSLASH:
                self.escape(out)
            else:
                out.append(c)
                self.pos += 1

    def escape(self, out):
        self.pos += 1
        if self.pos >= len(self.buf):
            raise self.refuse("malformed")
        c = self.buf[self.pos]
        self.pos += 1
        plain = _UNESCAPE.get(c)
        if plain is not None:
            out.append(plain)
            return
        if c != _LOWER_U:
            raise self.refuse("bad_string")
        u = self.hex4()
        if 0xDC00 <= u <= 0xDFFF:
            raise self.refuse("bad_string")
        if 0xD800 <= u <= 0xDBFF:
            if (self.pos + 1 >= len(self.buf) or self.buf[self.pos] != _BACKSLASH
                    or self.buf[self.pos + 1] != _LOWER_U):
                raise self.refuse("bad_string")
            self.pos += 2
            low = self.hex4()
            if not 0xDC00 <= low <= 0xDFFF:
                raise self.refuse("bad_string")
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00)
        out += chr(u).encode("utf-8")

    def hex4(self):
        if self.pos + 4 > len(self.buf):
            raise self.refuse("bad_string")
        u = 0
        for i in range(4):
            c = self.buf[self.pos + i]
            if _ZERO <= c <= _NINE:
                u = u << 4 | (c - _ZERO)
            elif 0x61 <= c <= 0x66:
                u = u << 4 | (c - 0x61 + 10)
            elif 0x41 <= c <= 0x46:
                u = u << 4 | (c - 0x41 + 10)
            else:
                raise self.refuse("bad_string")
        self.pos += 4
        return u

    def integer(self, low, high):
        c = self.at()
        if c != _MINUS and not _ZERO <= c <= _NINE:
            raise self.refuse("wrong_type")
        negative = c == _MINUS
        if negative:
            self.pos += 1
        if not self.digit():
            raise self.refuse("malformed")
        start = self.pos
        if self.at() == _ZERO:
            self.pos += 1
        else:
            while self.digit():
                self.pos += 1
        if self.at() in (_DOT, 0x65, 0x45) or self.digit():
            raise self.refuse("number_spelling")
        if self.pos - start > _I64_DIGITS:
            raise self.refuse("number_spelling")
        n = int(self.buf[start:self.pos])
        if negative:
            if n == 0:
                raise self.refuse("number_spelling")
            n = -n
        if n < low or n > high:
            raise self.refuse("number_spelling")
        return n

    def boolean(self):
        if self.at() == 0x74:
            self.literal(b"true")
            return True
        if self.at() == 0x66:
            self.literal(b"false")
            return False
        raise self.refuse("wrong_type")

    def literal(self, word):
        if self.buf[self.pos:self.pos + len(word)] != word:
            raise self.refuse("malformed")
        self.pos += len(word)

    def str_list(self):
        if self.at() != _LBRACK:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = []
        self.ws()
        if self.at() != _RBRACK:
            while True:
                self.ws()
                out.append(self.string())
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACK:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                if k in out:
                    raise self.refuse("duplicate_key")
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.raw_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_value(self):
        start = self.pos
        self.skip_value()
        return self.buf[start:self.pos]

    def skip_value(self):
        c = self.at()
        if c == _QUOTE:
            self.skip_string()
        elif c in (_LBRACE, _LBRACK):
            self.skip_container()
        elif c == 0x74:
            self.literal(b"true")
        elif c == 0x66:
            self.literal(b"false")
        elif c == 0x6E:
            self.literal(b"null")
        elif c == _MINUS or _ZERO <= c <= _NINE:
            self.skip_number()
        else:
            raise self.refuse("malformed")

    # An opaque value is validated and carried, never interpreted. Its syntax is
    # the record's own — the same string reader, so an escape, a control byte or
    # a lone surrogate is judged identically at any depth — and what it is free
    # to spell, it keeps: the bytes between these two offsets are what a writer
    # re-emits. A number is walked, never converted, so a value no host type
    # holds survives the reader that carried it.
    def skip_string(self):
        self.string()

    def some_digits(self):
        n = 0
        while _ZERO <= self.at() <= _NINE:
            self.pos += 1
            n += 1
        if n == 0:
            raise self.refuse("number_spelling")

    def skip_number(self):
        if self.at() == _MINUS:
            self.pos += 1
        c = self.at()
        if c == _ZERO:
            self.pos += 1
        elif _ZERO < c <= _NINE:
            while _ZERO <= self.at() <= _NINE:
                self.pos += 1
        else:
            raise self.refuse("number_spelling")
        if self.at() == _DOT:
            self.pos += 1
            self.some_digits()
        if self.at() in (0x65, 0x45):
            self.pos += 1
            if self.at() in (0x2B, _MINUS):
                self.pos += 1
            self.some_digits()

    def skip_container(self):
        opener = self.at()
        shut = _RBRACE if opener == _LBRACE else _RBRACK
        self.enter()
        self.pos += 1
        self.ws()
        seen = set()
        if self.at() != shut:
            while True:
                self.ws()
                if opener == _LBRACE:
                    if self.at() != _QUOTE:
                        raise self.refuse("malformed")
                    k = self.string()
                    if k in seen:
                        raise self.refuse("duplicate_key")
                    seen.add(k)
                    self.ws()
                    if self.at() != _COLON:
                        raise self.refuse("malformed")
                    self.pos += 1
                    self.ws()
                self.skip_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != shut:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1

    def str_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                if k in out:
                    raise self.refuse("duplicate_key")
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.string()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out


def _read_list(r, elem):
    if r.at() != _LBRACK:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    out = []
    r.ws()
    if r.at() != _RBRACK:
        while True:
            r.ws()
            out.append(elem(r))
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACK:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return out


def _read_image_request(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = ImageRequest()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "model":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.model = r.string()
            elif key == "mode":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.mode = r.string()
            elif key == "prompt":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.prompt = r.string()
            elif key == "size":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.size = r.string()
            elif key == "count":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.count = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "image_digest":
                if seen & 32:
                    raise r.refuse("duplicate_field")
                seen |= 32
                v.image_digest = r.string()
            elif key == "image_media_type":
                if seen & 64:
                    raise r.refuse("duplicate_field")
                seen |= 64
                v.image_media_type = r.string()
            elif key == "mask_digest":
                if seen & 128:
                    raise r.refuse("duplicate_field")
                seen |= 128
                v.mask_digest = r.string()
            elif key == "mask_media_type":
                if seen & 256:
                    raise r.refuse("duplicate_field")
                seen |= 256
                v.mask_media_type = r.string()
            elif key == "guarantees":
                if seen & 512:
                    raise r.refuse("duplicate_field")
                seen |= 512
                v.guarantees = r.str_list()
            elif key == "credential":
                if seen & 1024:
                    raise r.refuse("duplicate_field")
                seen |= 1024
                v.credential = r.string()
            elif key == "required_extensions":
                if seen & 2048:
                    raise r.refuse("duplicate_field")
                seen |= 2048
                v.required_extensions = r.str_list()
            elif key == "extensions":
                if seen & 4096:
                    raise r.refuse("duplicate_field")
                seen |= 4096
                v.extensions = r.str_map()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 543 != 543:
        raise r.refuse("missing_field")
    try:
        v.mode = Mode(v.mode)
    except ValueError:
        raise r.refuse("bad_enum") from None
    v.guarantees = [_open_enum(RequestGuarantee, item) for item in v.guarantees]
    return v


def _read_delivery(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Delivery()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "digest":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.digest = r.string()
            elif key == "media_type":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.media_type = r.string()
            elif key == "size":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.size = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "location":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.location = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _read_request(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Request()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "profile":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.profile = r.string()
            elif key == "image":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.image = _read_image_request(r)
            elif key == "duration_ms":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.duration_ms = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    try:
        v.profile = Profile(v.profile)
    except ValueError:
        raise r.refuse("bad_enum") from None
    return v


def _read_job_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = JobResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "profile":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.profile = r.string()
            elif key == "deliveries":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.deliveries = _read_list(r, _read_delivery)
            elif key == "host":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.host = r.string()
            elif key == "model":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.model = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    try:
        v.profile = Profile(v.profile)
    except ValueError:
        raise r.refuse("bad_enum") from None
    return v


def _read_document(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Document()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "request":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.request = _read_request(r)
            elif key == "result":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.result = _read_job_result(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return v


def decode(data):
    r = _Reader(bytes(data))
    r.ws()
    v = _read_document(r)
    r.ws()
    if r.pos < len(r.buf):
        raise r.refuse("trailing_bytes")
    return v


# _REFUSALS is in the order two of them are chosen between.

_REFUSALS = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"]


def _refusal_rank(word):
    return _REFUSALS.index(word) if word in _REFUSALS else -1
